export const STONELORE_G2 = {
  "s213": {
    tr: "Adını Yunanca 'magnesia' bölgesinden alan magnezit, antik çağda Anadolu ve Ege'deki manyezit yataklarından bilinirdi; aynı kökten 'mıknatıs' ve 'magnezyum' kelimeleri de doğdu. Beyaz, porselen benzeri dokusunun saflığı ve sakinliği simgelediğine inanılırdı. Taç çakranın toprak taşı olarak gevşemeyi ve öz-sevgiyi anımsatır.",
    en: "Magnesite takes its name from Magnesia, the ancient region of Anatolia and the Aegean whose deposits also gave us the words 'magnet' and 'magnesium.' Its smooth, porcelain-white surface was believed to embody purity and calm. As an earth stone of the crown chakra, it recalls deep relaxation and self-love.",
    de: "Magnesit verdankt seinen Namen Magnesia, der antiken Region Anatoliens und der Ägäis, deren Vorkommen auch die Wörter 'Magnet' und 'Magnesium' hervorbrachten. Seine glatte, porzellanweiße Oberfläche galt als Sinnbild für Reinheit und Ruhe. Als Erdstein des Kronenchakras erinnert er an tiefe Entspannung und Selbstliebe.",
    es: "La magnesita debe su nombre a Magnesia, la antigua región de Anatolia y el Egeo cuyos yacimientos también originaron las palabras 'imán' y 'magnesio'. Se creía que su superficie lisa y blanca como la porcelana encarnaba la pureza y la calma. Como piedra de tierra del chakra corona, evoca la relajación profunda y el amor propio.",
    fr: "La magnésite tire son nom de Magnésie, l'antique région d'Anatolie et de la mer Égée dont les gisements ont aussi donné les mots 'aimant' et 'magnésium'. On croyait que sa surface lisse et blanche comme la porcelaine incarnait la pureté et le calme. Pierre de terre du chakra couronne, elle évoque la détente profonde et l'amour de soi.",
    ja: "マグネサイトの名は、アナトリアとエーゲ海に広がる古代の地マグネシアに由来し、その鉱床は『磁石』や『マグネシウム』という言葉も生んだ。陶器のように滑らかな白い表面は、純粋さと静けさの象徴と信じられていた。クラウンチャクラの大地の石として、深いくつろぎと自己愛を思い起こさせる。",
    pt: "A magnesita recebe o nome de Magnésia, a antiga região da Anatólia e do Egeu cujos depósitos também deram origem às palavras 'íman' e 'magnésio'. Acreditava-se que a sua superfície lisa e branca como a porcelana encarnava a pureza e a calma. Como pedra de terra do chakra coroa, evoca o relaxamento profundo e o amor-próprio."
  },
  "s214": {
    tr: "Vanadinit, adını İskandinav güzellik tanrıçası Vanadis'ten (Freyja) alan vanadyum elementinden taşır; element bunca renkli bileşik verdiği için tanrıçanın adıyla anılmıştır. Fas'ın Atlas Dağları'ndaki parlak kırmızı-turuncu kristalleri ateşi ve canlılığı çağrıştırır. Kök çakranın bu ateş taşının enerjiyi ve kararlılığı tutuşturduğuna inanılırdı.",
    en: "Vanadinite carries the name of vanadium, the element named for Vanadis, the Norse goddess of beauty (Freyja), chosen because the element forms so many richly colored compounds. Its vivid red-orange crystals from Morocco's Atlas Mountains evoke fire and vitality. This fire stone of the root chakra was believed to kindle energy and resolve.",
    de: "Vanadinit trägt den Namen des Elements Vanadium, benannt nach Vanadis, der nordischen Göttin der Schönheit (Freyja), gewählt, weil das Element so viele farbenprächtige Verbindungen bildet. Seine leuchtend rot-orangen Kristalle aus dem marokkanischen Atlasgebirge erinnern an Feuer und Lebenskraft. Diesem Feuerstein des Wurzelchakras schrieb man zu, Energie und Entschlossenheit zu entfachen.",
    es: "La vanadinita lleva el nombre del vanadio, elemento bautizado en honor a Vanadis, la diosa nórdica de la belleza (Freyja), elegido porque forma compuestos de muchos colores intensos. Sus vivos cristales rojo-anaranjados de las montañas del Atlas marroquí evocan el fuego y la vitalidad. Se creía que esta piedra de fuego del chakra raíz encendía la energía y la determinación.",
    fr: "La vanadinite porte le nom du vanadium, élément baptisé d'après Vanadis, déesse nordique de la beauté (Freyja), choisi parce qu'il forme tant de composés aux couleurs vives. Ses cristaux rouge-orangé éclatants des montagnes de l'Atlas marocain évoquent le feu et la vitalité. On croyait que cette pierre de feu du chakra racine attisait l'énergie et la détermination.",
    ja: "バナジナイトは、北欧の美の女神ヴァナディス（フレイヤ）にちなんで名づけられた元素バナジウムの名を持つ。色鮮やかな化合物を数多く生むことから女神の名が選ばれた。モロッコのアトラス山脈で採れる鮮烈な赤橙の結晶は、炎と生命力を呼び起こす。ルートチャクラのこの炎の石は、エネルギーと決意を燃え立たせると信じられていた。",
    pt: "A vanadinita carrega o nome do vanádio, elemento batizado em honra a Vanadis, a deusa nórdica da beleza (Freyja), escolhido por formar compostos de cores tão intensas. Os seus vivos cristais vermelho-alaranjados das montanhas do Atlas marroquino evocam o fogo e a vitalidade. Acreditava-se que esta pedra de fogo do chakra raiz acendia a energia e a determinação."
  },
  "s215": {
    tr: "Larvikit, adını Norveç'in Larvik kasabasından alır; bu mavi-gri, ışık oynaşan taş 1200 milyon yıl önce Oslo çatlak bölgesinde oluşmuş Norveç'in ulusal kayasıdır. Feldispat kristallerinin ışıkla titreşen 'schiller' parıltısı, derinlikten yükselen netliği simgelerdi. Kök çakranın bu toprak taşının topraklama ve koruma sağladığına inanılırdı.",
    en: "Larvikite is named for the town of Larvik in Norway; this blue-grey, shimmering stone is Norway's national rock, formed some 1,200 million years ago in the Oslo rift. The light that flickers across its feldspar crystals, the 'schiller' sheen, was seen as clarity rising from the depths. This earth stone of the root chakra was believed to grant grounding and protection.",
    de: "Larvikit ist nach der Stadt Larvik in Norwegen benannt; dieser blaugraue, schimmernde Stein ist Norwegens Nationalgestein, vor etwa 1200 Millionen Jahren im Oslo-Graben entstanden. Das über seine Feldspatkristalle flackernde Licht, der 'Schiller', galt als aus der Tiefe aufsteigende Klarheit. Diesem Erdstein des Wurzelchakras schrieb man Erdung und Schutz zu.",
    es: "La larvikita debe su nombre a la ciudad de Larvik, en Noruega; esta piedra azul-gris y reluciente es la roca nacional noruega, formada hace unos 1.200 millones de años en el rift de Oslo. El brillo que titila sobre sus cristales de feldespato, el 'schiller', se veía como claridad surgiendo de las profundidades. Se creía que esta piedra de tierra del chakra raíz brindaba arraigo y protección.",
    fr: "La larvikite tire son nom de la ville de Larvik, en Norvège ; cette pierre bleu-gris et chatoyante est la roche nationale norvégienne, formée il y a quelque 1 200 millions d'années dans le rift d'Oslo. La lumière qui scintille sur ses cristaux de feldspath, le 'schiller', était perçue comme une clarté montant des profondeurs. On croyait que cette pierre de terre du chakra racine offrait ancrage et protection.",
    ja: "ラルビカイトはノルウェーのラルヴィク町にちなんで名づけられた。青灰色に輝くこの石は、約12億年前にオスロ地溝で生まれたノルウェーの国の石である。長石の結晶の上で揺らめく光、いわゆる『シラー』効果は、深みから立ち昇る明晰さと見なされた。ルートチャクラのこの大地の石は、地に足をつける力と守りを与えると信じられていた。",
    pt: "A larvikita deve o nome à cidade de Larvik, na Noruega; esta pedra azul-acinzentada e reluzente é a rocha nacional norueguesa, formada há cerca de 1.200 milhões de anos no rifte de Oslo. O brilho que cintila sobre os seus cristais de feldspato, o 'schiller', era visto como clareza erguendo-se das profundezas. Acreditava-se que esta pedra de terra do chakra raiz concedia enraizamento e proteção."
  },
  "s216": {
    tr: "Bronzit, adını ışıkla parlayan bronz benzeri metalik pırıltısından alır; bu pirokeen minerali demir içeriği sayesinde sıcak, altın-kahve bir parlaklık taşır. Eski halklar bronzun direnç ve dayanıklılığı temsil ettiğine, taşın da bu gücü taşıdığına inanırdı. Kök çakranın bu toprak taşının topraklama ve kendinden eminlik verdiği söylenir.",
    en: "Bronzite is named for its bronze-like metallic luster; this pyroxene mineral owes its warm, golden-brown shimmer to its iron content. Old peoples held that bronze stood for endurance and steadfastness, and that the stone carried the same strength. This earth stone of the root chakra is said to bring grounding and quiet self-assurance.",
    de: "Bronzit ist nach seinem bronzeähnlichen, metallischen Glanz benannt; dieses Pyroxenmineral verdankt seinen warmen, goldbraunen Schimmer seinem Eisengehalt. Alte Völker hielten Bronze für ein Sinnbild von Ausdauer und Beständigkeit und glaubten, der Stein trage dieselbe Stärke. Diesem Erdstein des Wurzelchakras sagt man Erdung und stilles Selbstvertrauen nach.",
    es: "La broncita debe su nombre a su lustre metálico semejante al bronce; este mineral del grupo de los piroxenos obtiene su cálido brillo pardo-dorado de su contenido en hierro. Los pueblos antiguos sostenían que el bronce representaba la resistencia y la firmeza, y que la piedra portaba esa misma fuerza. Se dice que esta piedra de tierra del chakra raíz aporta arraigo y serena confianza en uno mismo.",
    fr: "La bronzite tire son nom de son éclat métallique semblable au bronze ; ce minéral du groupe des pyroxènes doit son chatoiement chaud, brun doré, à sa teneur en fer. Les peuples anciens voyaient dans le bronze un symbole d'endurance et de fermeté, et croyaient que la pierre portait cette même force. On dit que cette pierre de terre du chakra racine apporte ancrage et calme assurance.",
    ja: "ブロンザイトは、青銅のような金属光沢にちなんで名づけられた。この輝石族の鉱物は、鉄分によって温かな金褐色の輝きを帯びる。古の人々は、青銅が忍耐と不屈を象徴し、この石も同じ強さを宿すと考えた。ルートチャクラのこの大地の石は、地に足をつける力と静かな自信をもたらすと言われている。",
    pt: "A bronzita deve o nome ao seu brilho metálico semelhante ao bronze; este mineral do grupo das piroxenas obtém o seu reflexo quente, castanho-dourado, do seu teor em ferro. Os povos antigos sustentavam que o bronze representava a resistência e a firmeza, e que a pedra carregava essa mesma força. Diz-se que esta pedra de terra do chakra raiz traz enraizamento e uma serena confiança em si mesmo."
  },
  "s217": {
    tr: "Stilbit, adını Yunanca parıltı anlamına gelen 'stilbein' kelimesinden alır; ışıkta inci gibi parlayan bu zeolit minerali ilk kez 18. yüzyıl sonunda tanımlanmıştır. Hindistan'ın bazalt boşluklarında ışıyan şeftali-pembesi demetleri yumuşaklığı çağrıştırır. Kalp çakranın bu su taşının sevgiyi ve sezgiyi yumuşakça açtığına inanılır.",
    en: "Stilbite takes its name from the Greek 'stilbein,' meaning to glitter; this zeolite mineral, with its pearly luster, was first described in the late 18th century. Its peach-pink sheaves glowing in the cavities of Indian basalt evoke gentleness. This water stone of the heart chakra is believed to open love and intuition softly.",
    de: "Stilbit leitet seinen Namen vom griechischen 'stilbein' ab, glänzen; dieses Zeolithmineral mit perlmuttartigem Schimmer wurde erstmals im späten 18. Jahrhundert beschrieben. Seine pfirsichrosa Büschel, die in den Hohlräumen indischen Basalts leuchten, erinnern an Sanftheit. Diesem Wasserstein des Herzchakras schreibt man zu, Liebe und Intuition behutsam zu öffnen.",
    es: "La estilbita toma su nombre del griego 'stilbein', brillar; este mineral del grupo de las zeolitas, de lustre perlado, se describió por primera vez a finales del siglo XVIII. Sus haces rosa-melocotón que brillan en las cavidades del basalto indio evocan la suavidad. Se cree que esta piedra de agua del chakra corazón abre con dulzura el amor y la intuición.",
    fr: "La stilbite tire son nom du grec 'stilbein', briller ; ce minéral du groupe des zéolites, à l'éclat nacré, fut décrit pour la première fois à la fin du XVIIIe siècle. Ses gerbes rose pêche qui luisent dans les cavités du basalte indien évoquent la douceur. On croit que cette pierre d'eau du chakra du cœur ouvre tendrement l'amour et l'intuition.",
    ja: "スティルバイトの名は、輝くを意味するギリシャ語『stilbein』に由来する。真珠のような光沢を持つこの沸石族の鉱物は、18世紀末に初めて記載された。インドの玄武岩の空洞で輝く桃色の束は、やわらかさを呼び起こす。ハートチャクラのこの水の石は、愛と直感をそっと開くと信じられている。",
    pt: "A estilbite recebe o nome do grego 'stilbein', brilhar; este mineral do grupo das zeólitas, de brilho perolado, foi descrito pela primeira vez no final do século XVIII. Os seus feixes cor de pêssego-rosado que reluzem nas cavidades do basalto indiano evocam a suavidade. Acredita-se que esta pedra de água do chakra coração abre com doçura o amor e a intuição."
  },
  "s218": {
    tr: "Şattukit, adını ilk bulunduğu yer olan Arizona'daki Shattuck madeninden alır ve 1915'te tanımlanmıştır. Bakır içeriğinden gelen derin gök mavisi rengi, sakin bir gökyüzünü andırır. Boğaz çakrasının bu su taşının dürüst iletişimi ve içsel sezgiyle uyumlu ifadeyi desteklediğine inanılır.",
    en: "Shattuckite is named for the Shattuck Mine in Arizona, where it was first found, and was described in 1915. Its deep sky-blue, born of copper, recalls a calm heaven. This water stone of the throat chakra is believed to support honest communication and expression in tune with inner intuition.",
    de: "Shattuckit ist nach der Shattuck-Mine in Arizona benannt, wo es zuerst gefunden und 1915 beschrieben wurde. Sein tiefes Himmelblau, dem Kupfer entstammend, erinnert an einen ruhigen Himmel. Diesem Wasserstein des Halschakras schreibt man zu, ehrliche Kommunikation und einen mit der inneren Intuition stimmigen Ausdruck zu fördern.",
    es: "La shattuckita debe su nombre a la mina Shattuck de Arizona, donde se halló por primera vez, y se describió en 1915. Su intenso azul cielo, nacido del cobre, recuerda a un firmamento sereno. Se cree que esta piedra de agua del chakra garganta favorece la comunicación honesta y una expresión en sintonía con la intuición interior.",
    fr: "La shattuckite tire son nom de la mine Shattuck en Arizona, où elle fut découverte pour la première fois, et fut décrite en 1915. Son bleu ciel profond, né du cuivre, rappelle un firmament paisible. On croit que cette pierre d'eau du chakra de la gorge favorise une communication sincère et une expression accordée à l'intuition intérieure.",
    ja: "シャッタカイトは、最初に発見されたアリゾナのシャタック鉱山にちなんで名づけられ、1915年に記載された。銅に由来する深い空色は、穏やかな天空を思わせる。スロートチャクラのこの水の石は、誠実なコミュニケーションと、内なる直感に調和した表現を支えると信じられている。",
    pt: "A shattuckite deve o nome à mina Shattuck, no Arizona, onde foi encontrada pela primeira vez, e foi descrita em 1915. O seu intenso azul-celeste, nascido do cobre, lembra um firmamento sereno. Acredita-se que esta pedra de água do chakra garganta favorece a comunicação honesta e uma expressão em sintonia com a intuição interior."
  },
  "s219": {
    tr: "Tsavorit, 1967'de jeolog Campbell Bridges tarafından Tanzanya'da keşfedilen ve adını Kenya'daki Tsavo Milli Parkı'ndan alan canlı yeşil bir grosular granattır; Tiffany & Co. onu 1974'te dünyaya tanıttı. Yemyeşil rengi büyümeyi ve bereketi simgeler. Kalp çakrasının bu toprak taşının bolluğu ve şefkati beslediği söylenir.",
    en: "Tsavorite is a vivid green grossular garnet, discovered in Tanzania in 1967 by the geologist Campbell Bridges and named for Tsavo National Park in Kenya; Tiffany & Co. introduced it to the world in 1974. Its lush green symbolizes growth and abundance. This earth stone of the heart chakra is said to nourish prosperity and compassion.",
    de: "Tsavorit ist ein leuchtend grüner Grossular-Granat, 1967 in Tansania vom Geologen Campbell Bridges entdeckt und nach dem Tsavo-Nationalpark in Kenia benannt; Tiffany & Co. stellte ihn 1974 der Welt vor. Sein sattes Grün steht für Wachstum und Fülle. Diesem Erdstein des Herzchakras sagt man nach, Wohlstand und Mitgefühl zu nähren.",
    es: "La tsavorita es un granate grosularia de un verde vivo, descubierto en Tanzania en 1967 por el geólogo Campbell Bridges y bautizado por el Parque Nacional de Tsavo, en Kenia; Tiffany & Co. lo dio a conocer al mundo en 1974. Su verde exuberante simboliza el crecimiento y la abundancia. Se dice que esta piedra de tierra del chakra corazón nutre la prosperidad y la compasión.",
    fr: "La tsavorite est un grenat grossulaire d'un vert vif, découvert en Tanzanie en 1967 par le géologue Campbell Bridges et nommé d'après le parc national de Tsavo, au Kenya ; Tiffany & Co. la fit connaître au monde en 1974. Son vert luxuriant symbolise la croissance et l'abondance. On dit que cette pierre de terre du chakra du cœur nourrit la prospérité et la compassion.",
    ja: "ツァボライトは鮮やかな緑のグロッシュラー・ガーネットで、1967年に地質学者キャンベル・ブリッジスがタンザニアで発見し、ケニアのツァボ国立公園にちなんで名づけられた。ティファニーが1974年に世に広めた。瑞々しい緑は成長と豊かさを象徴する。ハートチャクラのこの大地の石は、繁栄と慈しみを育むと言われている。",
    pt: "A tsavorite é uma granada grossulária de um verde vivo, descoberta na Tanzânia em 1967 pelo geólogo Campbell Bridges e batizada com o nome do Parque Nacional de Tsavo, no Quénia; a Tiffany & Co. apresentou-a ao mundo em 1974. O seu verde exuberante simboliza o crescimento e a abundância. Diz-se que esta pedra de terra do chakra coração nutre a prosperidade e a compaixão."
  },
  "s220": {
    tr: "Hayalet kuvars, büyürken araya giren mineral tabakalarının kristal içinde donmuş 'hayalet' siluetleri bıraktığı bir kuvars türüdür; her katman, kristalin büyümesinin durup yeniden başladığı bir anı dondurur. Bu doğal katmanlar büyümenin ve dönüşümün izleri olarak okunurdu. Taç çakranın bu toprak taşının niyeti ve katman katman şifayı simgelediğine inanılır.",
    en: "Phantom quartz is a variety of quartz in which layers of mineral, deposited during growth, leave 'phantom' outlines frozen inside the crystal; each layer marks a moment when growth paused and began again. These natural strata were read as traces of growth and transformation. This earth stone of the crown chakra is believed to symbolize intention and healing, layer by layer.",
    de: "Phantomquarz ist eine Quarzvarietät, in der während des Wachstums abgelagerte Mineralschichten 'Phantom'-Umrisse im Inneren des Kristalls hinterlassen; jede Schicht hält einen Moment fest, in dem das Wachstum innehielt und neu begann. Diese natürlichen Schichten galten als Spuren von Wachstum und Wandlung. Diesem Erdstein des Kronenchakras schreibt man zu, Absicht und Heilung Schicht für Schicht zu versinnbildlichen.",
    es: "El cuarzo fantasma es una variedad de cuarzo en la que las capas de mineral depositadas durante el crecimiento dejan siluetas 'fantasma' congeladas dentro del cristal; cada capa marca un instante en que el crecimiento se detuvo y volvió a empezar. Esos estratos naturales se leían como huellas de crecimiento y transformación. Se cree que esta piedra de tierra del chakra corona simboliza la intención y la sanación, capa a capa.",
    fr: "Le quartz fantôme est une variété de quartz où des couches de minéral, déposées pendant la croissance, laissent des silhouettes 'fantômes' figées à l'intérieur du cristal ; chaque couche fixe un instant où la croissance s'est arrêtée puis a repris. Ces strates naturelles étaient lues comme des traces de croissance et de transformation. On croit que cette pierre de terre du chakra couronne symbolise l'intention et la guérison, couche après couche.",
    ja: "ファントムクォーツは、成長の途中で堆積した鉱物の層が結晶の内部に『幻影』の輪郭を凍りつかせた水晶の一種である。一つひとつの層は、成長が止まり再び始まった瞬間を刻む。これらの自然の層は、成長と変容の痕跡として読み取られてきた。クラウンチャクラのこの大地の石は、意図と、層を重ねるような癒しを象徴すると信じられている。",
    pt: "O quartzo fantasma é uma variedade de quartzo na qual camadas de mineral, depositadas durante o crescimento, deixam silhuetas 'fantasma' congeladas no interior do cristal; cada camada marca um instante em que o crescimento parou e recomeçou. Esses estratos naturais eram lidos como vestígios de crescimento e transformação. Acredita-se que esta pedra de terra do chakra coroa simboliza a intenção e a cura, camada a camada."
  },
  "s221": {
    tr: "Lemurya kuvarsı, 1990'larda Brezilya'da bulunan ve yan yüzeylerinde merdiven benzeri yatay çentikler taşıyan saydam kuvars kristalleridir; adı kayıp Lemurya kıtası efsanesinden gelir. Bu çentiklerin kadim bir bilgeliğin 'kodlandığı' basamaklar olduğuna halk arasında inanılırdı. Taç çakranın bu hava taşının sevgiyi ve bağlantıyı çağrıştırdığı söylenir.",
    en: "Lemurian quartz is a clear quartz, found in Brazil in the 1990s, bearing ladder-like horizontal grooves along its sides; its name comes from the legend of the lost continent of Lemuria. Folk belief held that these grooves were steps in which an ancient wisdom had been 'encoded.' This air stone of the crown chakra is said to evoke love and connection.",
    de: "Lemurischer Quarz ist ein klarer Quarz, in den 1990er Jahren in Brasilien gefunden, mit leiterartigen waagerechten Rillen an seinen Seiten; sein Name stammt aus der Legende vom versunkenen Kontinent Lemuria. Der Volksglaube hielt diese Rillen für Stufen, in denen eine uralte Weisheit 'kodiert' sei. Diesem Luftstein des Kronenchakras sagt man nach, Liebe und Verbindung heraufzubeschwören.",
    es: "El cuarzo lemuriano es un cuarzo transparente, hallado en Brasil en los años noventa, con surcos horizontales a modo de escalera en sus caras; su nombre procede de la leyenda del continente perdido de Lemuria. La creencia popular sostenía que esos surcos eran peldaños donde se había 'codificado' una sabiduría ancestral. Se dice que esta piedra de aire del chakra corona evoca el amor y la conexión.",
    fr: "Le quartz lémurien est un quartz transparent, trouvé au Brésil dans les années 1990, portant sur ses faces des stries horizontales en forme d'échelle ; son nom vient de la légende du continent perdu de la Lémurie. La croyance populaire voyait dans ces stries des marches où une sagesse ancestrale aurait été 'encodée'. On dit que cette pierre d'air du chakra couronne évoque l'amour et la connexion.",
    ja: "レムリアン水晶は、1990年代にブラジルで見つかった透明な水晶で、側面に梯子のような水平の刻みを帯びる。その名は失われた大陸レムリアの伝説に由来する。民間の信仰では、これらの刻みは古の叡智が『刻み込まれた』階段だとされた。クラウンチャクラのこの風の石は、愛とつながりを呼び起こすと言われている。",
    pt: "O quartzo lemuriano é um quartzo transparente, encontrado no Brasil nos anos noventa, com sulcos horizontais em forma de escada nas suas faces; o nome vem da lenda do continente perdido da Lemúria. A crença popular sustentava que esses sulcos eram degraus onde se havia 'codificado' uma sabedoria ancestral. Diz-se que esta pedra de ar do chakra coroa evoca o amor e a conexão."
  },
  "s222": {
    tr: "Krizoberil, adını Yunanca 'altın' (chrysos) ve 'beril' kelimelerinden alan, elmas ve korunddan sonra en sert mücevher taşlarından biridir. Antik çağda altın-yeşil parıltısının kötü gözden koruduğuna ve sahibine şans getirdiğine inanılırdı. Solar pleksus çakrasının bu ateş taşı gücü ve öz-disiplini simgeler.",
    en: "Chrysoberyl takes its name from the Greek 'chrysos' (gold) and 'beryl,' and is one of the hardest gemstones after diamond and corundum. In antiquity its golden-green glow was believed to guard against the evil eye and to bring its owner good fortune. This fire stone of the solar plexus chakra symbolizes strength and self-discipline.",
    de: "Chrysoberyll leitet seinen Namen vom griechischen 'chrysos' (Gold) und 'Beryll' ab und ist nach Diamant und Korund einer der härtesten Edelsteine. In der Antike glaubte man, sein goldgrünes Leuchten schütze vor dem bösen Blick und bringe seinem Besitzer Glück. Dieser Feuerstein des Solarplexus-Chakras versinnbildlicht Stärke und Selbstdisziplin.",
    es: "El crisoberilo toma su nombre del griego 'chrysos' (oro) y 'berilo', y es una de las gemas más duras tras el diamante y el corindón. En la Antigüedad se creía que su brillo dorado-verdoso protegía del mal de ojo y traía buena suerte a su dueño. Esta piedra de fuego del chakra del plexo solar simboliza la fuerza y la autodisciplina.",
    fr: "Le chrysobéryl tire son nom du grec 'chrysos' (or) et 'béryl', et compte parmi les gemmes les plus dures après le diamant et le corindon. Dans l'Antiquité, on croyait que son éclat vert doré protégeait du mauvais œil et portait chance à son possesseur. Cette pierre de feu du chakra du plexus solaire symbolise la force et l'autodiscipline.",
    ja: "クリソベリルの名は、ギリシャ語の『chrysos（金）』と『ベリル』に由来し、ダイヤモンドとコランダムに次いで硬い宝石のひとつである。古代では、その金緑色の輝きが邪視から守り、持ち主に幸運をもたらすと信じられていた。ソーラープレクサスチャクラのこの炎の石は、力と自制を象徴する。",
    pt: "O crisoberilo recebe o nome do grego 'chrysos' (ouro) e 'berilo', e é uma das gemas mais duras depois do diamante e do corindo. Na Antiguidade, acreditava-se que o seu brilho verde-dourado protegia do mau-olhado e trazia boa sorte ao seu dono. Esta pedra de fogo do chakra do plexo solar simboliza a força e a autodisciplina."
  },
  "s223": {
    tr: "Kedi gözü, genellikle krizoberilin ipeksi liflerinin yansıttığı tek bir parlak ışık çizgisiyle tıpkı bir kedinin göz bebeği gibi parlayan taştır; bu 'chatoyance' etkisi adını Fransızca 'kedi' kelimesinden alır. Sri Lanka'da nazarlık olarak takılır, sahibini gizli tehlikelere karşı uyandırık tuttuğuna inanılırdı. Solar pleksus çakrasının bu toprak taşı korumayı ve sezgiyi simgeler.",
    en: "Cat's eye, usually chrysoberyl, glows with a single bright band of light reflected by its silky fibers, just like the slit of a cat's pupil; this 'chatoyance' takes its name from the French word for cat. In Sri Lanka it was worn as an amulet, believed to keep its owner watchful against hidden dangers. This earth stone of the solar plexus chakra symbolizes protection and intuition.",
    de: "Das Katzenauge, meist Chrysoberyll, leuchtet mit einem einzelnen hellen Lichtband, das seine seidigen Fasern zurückwerfen, genau wie der Schlitz einer Katzenpupille; diese 'Chatoyance' leitet ihren Namen vom französischen Wort für Katze ab. In Sri Lanka trug man es als Amulett, das seinen Besitzer wachsam gegen verborgene Gefahren halten sollte. Dieser Erdstein des Solarplexus-Chakras versinnbildlicht Schutz und Intuition.",
    es: "El ojo de gato, por lo general crisoberilo, brilla con una sola banda luminosa que reflejan sus fibras sedosas, igual que la hendidura de la pupila de un gato; esa 'chatoyance' toma su nombre de la palabra francesa para gato. En Sri Lanka se llevaba como amuleto, pues se creía que mantenía a su dueño alerta ante peligros ocultos. Esta piedra de tierra del chakra del plexo solar simboliza la protección y la intuición.",
    fr: "L'œil-de-chat, généralement du chrysobéryl, luit d'une seule bande lumineuse que renvoient ses fibres soyeuses, telle la fente de la pupille d'un chat ; cette 'chatoyance' tire son nom du mot français désignant le chat. À Sri Lanka, on le portait en amulette, censée garder son possesseur en éveil face aux dangers cachés. Cette pierre de terre du chakra du plexus solaire symbolise la protection et l'intuition.",
    ja: "キャッツアイは、たいていクリソベリルで、絹のような繊維が反射する一筋の明るい光の帯によって、まるで猫の瞳孔のように輝く。この『シャトヤンシー（変彩効果）』の名は、フランス語の『猫』に由来する。スリランカでは護符として身につけられ、持ち主を隠れた危険に対して油断なく保つと信じられていた。ソーラープレクサスチャクラのこの大地の石は、守りと直感を象徴する。",
    pt: "O olho-de-gato, geralmente crisoberilo, brilha com uma única faixa luminosa refletida pelas suas fibras sedosas, tal como a fenda da pupila de um gato; essa 'chatoyance' recebe o nome da palavra francesa para gato. No Sri Lanka era usado como amuleto, pois se acreditava que mantinha o dono atento aos perigos ocultos. Esta pedra de terra do chakra do plexo solar simboliza a proteção e a intuição."
  },
  "s224": {
    tr: "Zirkon, Yer'in en yaşlı bilinen minerallerindendir; Avustralya'da bulunan zirkon kristalleri 4,4 milyar yaşındadır. Antik çağda altın-kırmızı taneleri 'hyacinth' ya da 'jacinth' adıyla bilinir, uykuyu koruduğuna ve bilgelik getirdiğine inanılırdı. Adı muhtemelen Farsça 'altın renkli' anlamındaki 'zargun'dan gelir. Taç çakranın bu ateş taşı netliği ve dengeyi simgeler.",
    en: "Zircon is among the oldest known minerals on Earth; zircon crystals found in Australia are some 4.4 billion years old. In antiquity its golden-red grains were known as 'hyacinth' or 'jacinth' and were believed to guard sleep and bring wisdom. Its name likely comes from the Persian 'zargun,' meaning gold-colored. This fire stone of the crown chakra symbolizes clarity and balance.",
    de: "Zirkon zählt zu den ältesten bekannten Mineralen der Erde; in Australien gefundene Zirkonkristalle sind etwa 4,4 Milliarden Jahre alt. In der Antike waren seine goldrot­en Körner als 'Hyazinth' oder 'Jacinth' bekannt und sollten den Schlaf hüten und Weisheit bringen. Sein Name stammt wohl vom persischen 'zargun', goldfarben. Dieser Feuerstein des Kronenchakras versinnbildlicht Klarheit und Gleichgewicht.",
    es: "El circón se cuenta entre los minerales más antiguos que se conocen en la Tierra; los cristales de circón hallados en Australia tienen unos 4.400 millones de años. En la Antigüedad sus granos rojo-dorados se conocían como 'jacinto' y se creía que custodiaban el sueño y traían sabiduría. Su nombre procede probablemente del persa 'zargun', de color dorado. Esta piedra de fuego del chakra corona simboliza la claridad y el equilibrio.",
    fr: "Le zircon compte parmi les plus anciens minéraux connus sur Terre ; des cristaux de zircon trouvés en Australie ont quelque 4,4 milliards d'années. Dans l'Antiquité, ses grains rouge doré étaient appelés 'hyacinthe' ou 'jacinthe' et passaient pour veiller sur le sommeil et apporter la sagesse. Son nom vient probablement du persan 'zargun', de couleur dorée. Cette pierre de feu du chakra couronne symbolise la clarté et l'équilibre.",
    ja: "ジルコンは地球で知られる最古の鉱物のひとつであり、オーストラリアで見つかったジルコンの結晶は約44億年前のものである。古代では、その金赤色の粒は『ヒヤシンス』あるいは『ジャシンス』と呼ばれ、眠りを守り叡智をもたらすと信じられていた。その名はおそらく、金色を意味するペルシャ語『ザルグン』に由来する。クラウンチャクラのこの炎の石は、明晰さと均衡を象徴する。",
    pt: "O zircão está entre os minerais mais antigos conhecidos na Terra; os cristais de zircão encontrados na Austrália têm cerca de 4,4 mil milhões de anos. Na Antiguidade, os seus grãos vermelho-dourados eram conhecidos como 'jacinto' e acreditava-se que guardavam o sono e traziam sabedoria. O seu nome provém provavelmente do persa 'zargun', de cor dourada. Esta pedra de fogo do chakra coroa simboliza a clareza e o equilíbrio."
  },
  "s225": {
    tr: "Heliodor, adını Yunanca 'güneş' (helios) ve 'armağan' (doron) kelimelerinden alır; 'güneşin armağanı' anlamına gelen bu altın-sarı beril ilk kez 1910'da Namibya'da tanımlanmıştır. Sıcak rengi güneş ışığını ve neşeyi çağrıştırır. Solar pleksus çakrasının bu ateş taşının iradeyi ve canlılığı güçlendirdiğine inanılır.",
    en: "Heliodor takes its name from the Greek 'helios' (sun) and 'doron' (gift); this golden-yellow beryl, meaning 'gift of the sun,' was first described in Namibia in 1910. Its warm color evokes sunlight and joy. This fire stone of the solar plexus chakra is believed to strengthen will and vitality.",
    de: "Heliodor leitet seinen Namen vom griechischen 'helios' (Sonne) und 'doron' (Geschenk) ab; dieser goldgelbe Beryll, 'Geschenk der Sonne', wurde erstmals 1910 in Namibia beschrieben. Seine warme Farbe erinnert an Sonnenlicht und Freude. Diesem Feuerstein des Solarplexus-Chakras schreibt man zu, Willen und Lebenskraft zu stärken.",
    es: "El heliodoro toma su nombre del griego 'helios' (sol) y 'doron' (regalo); este berilo amarillo-dorado, 'regalo del sol', se describió por primera vez en Namibia en 1910. Su color cálido evoca la luz del sol y la alegría. Se cree que esta piedra de fuego del chakra del plexo solar fortalece la voluntad y la vitalidad.",
    fr: "L'héliodore tire son nom du grec 'helios' (soleil) et 'doron' (don) ; ce béryl jaune doré, le 'don du soleil', fut décrit pour la première fois en Namibie en 1910. Sa couleur chaude évoque la lumière du soleil et la joie. On croit que cette pierre de feu du chakra du plexus solaire renforce la volonté et la vitalité.",
    ja: "ヘリオドールの名は、ギリシャ語の『helios（太陽）』と『doron（贈り物）』に由来する。『太陽の贈り物』を意味するこの金黄色のベリルは、1910年にナミビアで初めて記載された。その温かな色は、陽光と喜びを呼び起こす。ソーラープレクサスチャクラのこの炎の石は、意志と生命力を強めると信じられている。",
    pt: "O heliodoro recebe o nome do grego 'helios' (sol) e 'doron' (presente); este berilo amarelo-dourado, o 'presente do sol', foi descrito pela primeira vez na Namíbia em 1910. A sua cor quente evoca a luz do sol e a alegria. Acredita-se que esta pedra de fogo do chakra do plexo solar fortalece a vontade e a vitalidade."
  }
};
