export const STONELORE_G3 = {
  "s226": {
    tr: "Goşenit, berilin renksiz ve en saf hâlidir; adını ilk bulunduğu yer olan Massachusetts'teki Goshen kasabasından alır. Camsı berraklığı yüzyıllar boyunca insanı büyülemiş, optik mercek ve gözlük camı yapımında kullanılmıştır. Eski zanaatkârların onu 'içinden geçen ışığı bozmayan taş' olarak gördüğü, taşıyanına dürüstlük ve aklın berraklığını verdiğine inanıldığı söylenir.",
    en: "Goshenite is the colorless and purest form of beryl, named after the town of Goshen in Massachusetts, where it was first found. Its glassy clarity has fascinated people for centuries and was used to make optical lenses and spectacles. It is said that old craftsmen regarded it as 'the stone that does not distort the light passing through it,' and it was believed to grant honesty and clarity of mind to those who carried it.",
    de: "Goshenit ist die farblose und reinste Form des Berylls und wurde nach der Stadt Goshen in Massachusetts benannt, wo er erstmals gefunden wurde. Seine glasklare Reinheit faszinierte die Menschen über Jahrhunderte und wurde zur Herstellung optischer Linsen und Brillengläser verwendet. Man sagt, alte Handwerker betrachteten ihn als 'den Stein, der das hindurchfallende Licht nicht verzerrt', und es wurde geglaubt, er schenke seinem Träger Ehrlichkeit und Klarheit des Geistes.",
    es: "La goshenita es la forma incolora y más pura del berilo, y debe su nombre al pueblo de Goshen, en Massachusetts, donde se halló por primera vez. Su transparencia vítrea ha fascinado a las personas durante siglos y se empleó para fabricar lentes ópticas y cristales de gafas. Se dice que los antiguos artesanos la veían como 'la piedra que no distorsiona la luz que la atraviesa', y se creía que otorgaba honestidad y claridad de mente a quien la portaba.",
    fr: "La goshénite est la forme incolore et la plus pure du béryl ; elle tient son nom de la ville de Goshen, dans le Massachusetts, où elle fut découverte pour la première fois. Sa limpidité vitreuse a fasciné les hommes pendant des siècles et servit à fabriquer des lentilles optiques et des verres de lunettes. On raconte que les anciens artisans la voyaient comme 'la pierre qui ne déforme pas la lumière qui la traverse', et l'on croyait qu'elle offrait à celui qui la portait l'honnêteté et la clarté de l'esprit.",
    ja: "ゴシェナイトはベリルの無色で最も純粋な形であり、初めて発見されたマサチューセッツ州ゴーシェンの町にちなんで名づけられました。そのガラスのような透明さは何世紀にもわたり人々を魅了し、光学レンズや眼鏡のガラスづくりに用いられました。昔の職人たちはこれを「通り抜ける光を歪めない石」とみなし、持つ者に誠実さと心の明晰さを与えると信じられていたと伝えられています。",
    pt: "A goshenita é a forma incolor e mais pura do berilo, e recebe o nome da cidade de Goshen, em Massachusetts, onde foi encontrada pela primeira vez. Sua transparência vítrea fascinou as pessoas durante séculos e foi usada para fabricar lentes ópticas e vidros de óculos. Diz-se que os antigos artesãos a viam como 'a pedra que não distorce a luz que a atravessa', e acreditava-se que concedia honestidade e clareza de mente a quem a carregava."
  },
  "s227": {
    tr: "Diopsit, adını Yunanca 'çift görünüm' anlamına gelen sözcüklerden alır; çünkü kristali döndürüldüğünde içindeki çift kırılma iki ayrı görüntü gibi belirir. 1806'da bir Avusturyalı mineralog tarafından tanımlanmıştır. Yeşil tonları yüzünden eski halk geleneklerinde toprağın ve gökyüzünün buluşmasını simgelediği, kalbi dengeleyip öğrenmeye açtığına inanılırdı.",
    en: "Diopside takes its name from Greek words meaning 'double appearance,' for when the crystal is turned, its double refraction makes two separate images appear within it. It was described by an Austrian mineralogist in 1806. Because of its green tones, in old folk traditions it was believed to symbolize the meeting of earth and sky, and to balance the heart and open it to learning.",
    de: "Diopsid leitet seinen Namen von griechischen Wörtern ab, die 'doppelte Erscheinung' bedeuten, denn dreht man den Kristall, lässt seine Doppelbrechung zwei getrennte Bilder darin erscheinen. Er wurde 1806 von einem österreichischen Mineralogen beschrieben. Wegen seiner grünen Töne glaubte man in alten Volksüberlieferungen, er versinnbildliche die Begegnung von Erde und Himmel und bringe das Herz ins Gleichgewicht und öffne es dem Lernen.",
    es: "El diópsido toma su nombre de palabras griegas que significan 'doble apariencia', pues al girar el cristal su doble refracción hace aparecer dos imágenes separadas en su interior. Fue descrito por un mineralogista austriaco en 1806. Por sus tonos verdes, en las antiguas tradiciones populares se creía que simbolizaba el encuentro de la tierra y el cielo, y que equilibraba el corazón y lo abría al aprendizaje.",
    fr: "Le diopside tire son nom de mots grecs signifiant 'double apparence', car lorsqu'on tourne le cristal, sa double réfraction y fait apparaître deux images distinctes. Il fut décrit par un minéralogiste autrichien en 1806. En raison de ses teintes vertes, les anciennes traditions populaires croyaient qu'il symbolisait la rencontre de la terre et du ciel, et qu'il équilibrait le cœur et l'ouvrait à l'apprentissage.",
    ja: "ディオプサイドは「二重の見え方」を意味するギリシャ語に由来します。結晶を回すと、その複屈折によって内部に二つの別々の像が現れるからです。1806年にオーストリアの鉱物学者によって記載されました。その緑の色合いから、古い民間伝承では大地と空の出会いを象徴し、心を整えて学びへと開くと信じられていました。",
    pt: "O diopsídio tira seu nome de palavras gregas que significam 'aparência dupla', pois, ao girar o cristal, sua dupla refração faz surgir duas imagens separadas em seu interior. Foi descrito por um mineralogista austríaco em 1806. Por seus tons verdes, nas antigas tradições populares acreditava-se que simbolizava o encontro da terra e do céu, e que equilibrava o coração e o abria à aprendizagem."
  },
  "s228": {
    tr: "Hipersten, adını Yunanca 'aşırı güç' anlamına gelen sözcüklerden alır; bu, dış yüzeyindeki olağanüstü sertliğe ve metalik parıltıya gönderme yapar. Koyu, neredeyse siyah rengiyle yüzeyinde bronz bir ışıltı taşır. Eski madenciler bu yer altı taşının ayakları yere bastırdığına, korku karşısında soğukkanlılık verip zihni dağınıklıktan koruduğuna inanırdı.",
    en: "Hypersthene takes its name from Greek words meaning 'over-strength,' a reference to the remarkable hardness of its surface and its metallic sheen. With its dark, almost black color, it carries a bronze shimmer across its surface. Old miners believed this underground stone pressed the feet firmly to the ground, lent composure in the face of fear, and guarded the mind from scattering.",
    de: "Hypersthen leitet seinen Namen von griechischen Wörtern ab, die 'übermäßige Stärke' bedeuten, ein Verweis auf die bemerkenswerte Härte seiner Oberfläche und seinen metallischen Glanz. Mit seiner dunklen, fast schwarzen Farbe trägt er einen bronzenen Schimmer auf seiner Oberfläche. Alte Bergleute glaubten, dieser Stein aus der Tiefe drücke die Füße fest auf den Boden, schenke Gelassenheit angesichts der Furcht und bewahre den Geist vor Zerstreuung.",
    es: "La hiperstena toma su nombre de palabras griegas que significan 'fuerza excesiva', en referencia a la notable dureza de su superficie y su brillo metálico. Con su color oscuro, casi negro, luce un destello broncíneo sobre su superficie. Los antiguos mineros creían que esta piedra subterránea afirmaba los pies sobre la tierra, daba serenidad ante el miedo y resguardaba la mente de la dispersión.",
    fr: "L'hypersthène tire son nom de mots grecs signifiant 'force excessive', une allusion à la dureté remarquable de sa surface et à son éclat métallique. De couleur sombre, presque noire, elle porte un reflet bronze à sa surface. Les anciens mineurs croyaient que cette pierre des profondeurs ancrait fermement les pieds au sol, apportait du sang-froid face à la peur et préservait l'esprit de la dispersion.",
    ja: "ハイパースシーンは「過剰な強さ」を意味するギリシャ語に由来し、その表面の際立った硬さと金属的な輝きを指しています。暗くほとんど黒に近い色をしながら、表面に青銅色の煌めきを宿します。昔の鉱夫たちは、この地中の石が足を大地にしっかりと根づかせ、恐れの前で冷静さを与え、心が散らばるのを守ると信じていました。",
    pt: "A hiperstênio tira seu nome de palavras gregas que significam 'força excessiva', em referência à notável dureza de sua superfície e ao seu brilho metálico. Com sua cor escura, quase preta, traz um reflexo bronzeado sobre a superfície. Os antigos mineiros acreditavam que esta pedra subterrânea firmava os pés ao chão, dava serenidade diante do medo e protegia a mente da dispersão."
  },
  "s229": {
    tr: "Astrofillit, adını Yunanca 'yıldız' ve 'yaprak' sözcüklerinden alır; çünkü bronz-altın kristalleri taşın içinden bir yıldız patlaması gibi ışınsal olarak dağılır. İlk olarak 19. yüzyılda Norveç'in Læven adasında tanımlanmıştır. İçindeki bu yıldız desenleri yüzünden onu görenlerin kişinin gizli potansiyelini ortaya çıkardığına, içsel dönüşüm ve ilham getirdiğine inandığı anlatılır.",
    en: "Astrophyllite takes its name from the Greek words for 'star' and 'leaf,' because its bronze-golden crystals radiate outward through the stone like a starburst. It was first described in the 19th century on the island of Læven in Norway. Because of these star patterns within it, it is said that those who saw it believed it revealed a person's hidden potential and brought inner transformation and inspiration.",
    de: "Astrophyllit leitet seinen Namen von den griechischen Wörtern für 'Stern' und 'Blatt' ab, denn seine bronze-goldenen Kristalle strahlen wie eine Sternenexplosion durch den Stein nach außen. Er wurde erstmals im 19. Jahrhundert auf der Insel Læven in Norwegen beschrieben. Wegen dieser Sternmuster in seinem Inneren erzählt man, dass jene, die ihn sahen, glaubten, er enthülle das verborgene Potenzial eines Menschen und bringe innere Wandlung und Inspiration.",
    es: "La astrofilita toma su nombre de las palabras griegas para 'estrella' y 'hoja', pues sus cristales bronce-dorados se irradian a través de la piedra como un estallido estelar. Fue descrita por primera vez en el siglo XIX en la isla de Læven, en Noruega. Por estos patrones de estrella en su interior, se dice que quienes la veían creían que revelaba el potencial oculto de la persona y traía transformación interior e inspiración.",
    fr: "L'astrophyllite tire son nom des mots grecs signifiant 'étoile' et 'feuille', car ses cristaux bronze doré rayonnent à travers la pierre comme une explosion d'étoile. Elle fut décrite pour la première fois au XIXe siècle sur l'île de Læven, en Norvège. En raison de ces motifs étoilés en son sein, on raconte que ceux qui la voyaient croyaient qu'elle révélait le potentiel caché d'une personne et apportait transformation intérieure et inspiration.",
    ja: "アストロフィライトは「星」と「葉」を意味するギリシャ語に由来します。青銅色から金色の結晶が、星の爆発のように石の内側から放射状に広がるからです。19世紀にノルウェーのレーヴェン島で初めて記載されました。内に宿るこの星の模様ゆえに、それを見た者は、人の隠れた可能性を引き出し、内なる変容とひらめきをもたらすと信じていたと語り継がれています。",
    pt: "A astrofilita tira seu nome das palavras gregas para 'estrela' e 'folha', pois seus cristais bronze-dourados se irradiam pela pedra como uma explosão estelar. Foi descrita pela primeira vez no século XIX na ilha de Læven, na Noruega. Por causa desses padrões estrelados em seu interior, diz-se que aqueles que a viam acreditavam que revelava o potencial oculto da pessoa e trazia transformação interior e inspiração."
  },
  "s230": {
    tr: "Skapolit, adını Yunanca 'sütun' anlamına gelen sözcükten alır; çünkü uzun, prizmatik kristalleri ince sütunlar gibi büyür. Bazı örnekleri ışık altında ipeksi bir kedi gözü etkisi gösterir. Sarımsı ve mor tonlarıyla halk inancında zihni disipline eden, çözülmemiş sorunların önünü açan ve değişime uyum sağlamayı kolaylaştıran bir taş olarak görülürdü.",
    en: "Scapolite takes its name from the Greek word for 'column,' because its long, prismatic crystals grow like slender pillars. Some specimens show a silky cat's-eye effect under light. With its yellowish and violet tones, in folk belief it was seen as a stone that disciplined the mind, opened the way through unresolved problems, and made it easier to adapt to change.",
    de: "Skapolith leitet seinen Namen vom griechischen Wort für 'Säule' ab, denn seine langen, prismatischen Kristalle wachsen wie schlanke Säulen. Manche Exemplare zeigen im Licht einen seidigen Katzenaugen-Effekt. Mit seinen gelblichen und violetten Tönen galt er im Volksglauben als Stein, der den Geist diszipliniert, den Weg durch ungelöste Probleme öffnet und es erleichtert, sich dem Wandel anzupassen.",
    es: "La escapolita toma su nombre de la palabra griega para 'columna', pues sus largos cristales prismáticos crecen como esbeltos pilares. Algunos ejemplares muestran un sedoso efecto de ojo de gato bajo la luz. Con sus tonos amarillentos y violetas, en la creencia popular se la veía como una piedra que disciplinaba la mente, abría el camino a través de los problemas sin resolver y facilitaba adaptarse al cambio.",
    fr: "La scapolite tire son nom du mot grec signifiant 'colonne', car ses longs cristaux prismatiques croissent comme de fines colonnes. Certains spécimens présentent sous la lumière un soyeux effet œil-de-chat. Avec ses teintes jaunâtres et violettes, la croyance populaire la voyait comme une pierre qui disciplinait l'esprit, ouvrait le chemin à travers les problèmes irrésolus et facilitait l'adaptation au changement.",
    ja: "スキャポライトは「柱」を意味するギリシャ語に由来します。長い柱状の結晶が、ほっそりとした円柱のように成長するからです。一部の標本は、光の下で絹のようなキャッツアイ効果を見せます。黄色みや紫の色合いをもつこの石は、民間信仰において心を律し、未解決の問題に道を開き、変化への順応を助ける石とみなされていました。",
    pt: "A escapolita tira seu nome da palavra grega para 'coluna', pois seus longos cristais prismáticos crescem como pilares esguios. Alguns exemplares mostram um sedoso efeito de olho de gato sob a luz. Com seus tons amarelados e violetas, na crença popular era vista como uma pedra que disciplinava a mente, abria caminho através de problemas não resolvidos e facilitava a adaptação à mudança."
  },
  "s231": {
    tr: "Ulexit, adını onu inceleyen Alman kimyager Georg Ludwig Ulex'ten alır. En çarpıcı özelliği, ince lifli yapısı sayesinde altına konan bir yazıyı yüzeyine taşımasıdır; bu yüzden halk arasında 'televizyon taşı' olarak bilinir. Bu doğal optik etki yüzünden ona bakanların görünenin ötesini gösterdiğine, içgörü ve berraklık verdiğine inanılırdı.",
    en: "Ulexite takes its name from the German chemist Georg Ludwig Ulex, who studied it. Its most striking feature is that, thanks to its fine fibrous structure, it carries an image placed beneath it up onto its surface; for this reason it is popularly known as the 'television stone.' Because of this natural optical effect, it was believed that those who gazed at it could see beyond appearances, and that it granted insight and clarity.",
    de: "Ulexit leitet seinen Namen vom deutschen Chemiker Georg Ludwig Ulex ab, der ihn untersuchte. Sein auffälligstes Merkmal ist, dass er dank seiner feinen faserigen Struktur ein darunter gelegtes Bild bis an seine Oberfläche trägt; deshalb ist er im Volksmund als 'Fernsehstein' bekannt. Wegen dieses natürlichen optischen Effekts glaubte man, dass jene, die ihn betrachteten, über den Schein hinausblicken könnten und er Einsicht und Klarheit schenke.",
    es: "La ulexita toma su nombre del químico alemán Georg Ludwig Ulex, que la estudió. Su rasgo más llamativo es que, gracias a su fina estructura fibrosa, lleva hasta su superficie una imagen colocada debajo; por ello se la conoce popularmente como la 'piedra televisión'. Debido a este efecto óptico natural, se creía que quienes la contemplaban podían ver más allá de las apariencias, y que otorgaba visión interior y claridad.",
    fr: "L'ulexite tire son nom du chimiste allemand Georg Ludwig Ulex, qui l'étudia. Son trait le plus frappant est que, grâce à sa fine structure fibreuse, elle remonte à sa surface une image placée en dessous ; on la connaît ainsi populairement sous le nom de 'pierre télévision'. En raison de cet effet optique naturel, on croyait que ceux qui la contemplaient pouvaient voir au-delà des apparences, et qu'elle offrait intuition et clarté.",
    ja: "ユレックス石は、それを研究したドイツの化学者ゲオルク・ルートヴィヒ・ウレックスにちなんで名づけられました。最も際立った特徴は、細い繊維状の構造のおかげで、下に置いた文字や像を表面まで運ぶことです。そのため俗に「テレビ石」と呼ばれます。この自然の光学効果ゆえに、それを見つめる者は見かけの向こうを見通せると信じられ、洞察と明晰さを与えるとされました。",
    pt: "A ulexita tira seu nome do químico alemão Georg Ludwig Ulex, que a estudou. Seu traço mais marcante é que, graças à sua fina estrutura fibrosa, ela traz até a superfície uma imagem colocada por baixo; por isso é popularmente conhecida como a 'pedra televisão'. Por causa desse efeito óptico natural, acreditava-se que quem a contemplava podia ver além das aparências, e que ela concedia perspicácia e clareza."
  },
  "s232": {
    tr: "Krokoit, adını Yunanca 'safran' anlamına gelen sözcükten alır; çünkü ateş kırmızısı, parlak turuncu kristalleri safranın o yoğun rengini andırır. En güzel örnekleri Tasmanya'nın Dundas madenlerinden çıkar ve burada içinde keşfedilen krom elementi, modern kimyaya yepyeni bir renkler dünyası açmıştır. Bu canlı rengi yüzünden ona tutku, cesaret ve yaratıcı kıvılcım bahşettiği söylenir.",
    en: "Crocoite takes its name from the Greek word for 'saffron,' because its fiery red, brilliant orange crystals recall that deep saffron hue. Its finest specimens come from the Dundas mines of Tasmania, and the element chromium discovered within it opened a whole new world of colors to modern chemistry. Because of this vivid color, it is said to grant passion, courage, and the creative spark.",
    de: "Krokoit leitet seinen Namen vom griechischen Wort für 'Safran' ab, denn seine feuerroten, leuchtend orangefarbenen Kristalle erinnern an jenen tiefen Safranton. Seine schönsten Exemplare stammen aus den Dundas-Minen Tasmaniens, und das in ihm entdeckte Element Chrom eröffnete der modernen Chemie eine ganz neue Welt der Farben. Wegen dieser lebhaften Farbe sagt man, er schenke Leidenschaft, Mut und den schöpferischen Funken.",
    es: "La crocoíta toma su nombre de la palabra griega para 'azafrán', pues sus cristales de un rojo ardiente y naranja brillante recuerdan ese intenso tono del azafrán. Sus mejores ejemplares proceden de las minas de Dundas, en Tasmania, y el elemento cromo descubierto en ella abrió a la química moderna todo un nuevo mundo de colores. Por este color vívido, se dice que otorga pasión, valor y la chispa creativa.",
    fr: "La crocoïte tire son nom du mot grec signifiant 'safran', car ses cristaux d'un rouge ardent et d'un orange éclatant rappellent cette teinte intense du safran. Ses plus beaux spécimens proviennent des mines de Dundas, en Tasmanie, et l'élément chrome découvert en elle ouvrit à la chimie moderne tout un nouveau monde de couleurs. En raison de cette couleur vive, on dit qu'elle offre passion, courage et l'étincelle créatrice.",
    ja: "クロコアイトは「サフラン」を意味するギリシャ語に由来します。燃えるような赤や鮮やかな橙の結晶が、あの深いサフランの色合いを思わせるからです。最も美しい標本はタスマニアのダンダス鉱山から産出し、その中から発見された元素クロムは、近代化学に色彩のまったく新しい世界を開きました。この鮮烈な色ゆえに、情熱と勇気、そして創造のひらめきを授けると言われています。",
    pt: "A crocoíta tira seu nome da palavra grega para 'açafrão', pois seus cristais de um vermelho ardente e laranja brilhante lembram aquele intenso tom do açafrão. Seus melhores exemplares vêm das minas de Dundas, na Tasmânia, e o elemento crômio nela descoberto abriu à química moderna todo um novo mundo de cores. Por causa dessa cor viva, diz-se que concede paixão, coragem e a centelha criativa."
  },
  "s114": {
    tr: "Smithsonit, adını İngiliz kimyager ve mineralog James Smithson'dan alır; serveti, ölümünden sonra ünlü Smithsonian Enstitüsü'nün kurulmasını sağlayan adamdır. Çinko cevheri olan bu taş, yumuşak mavi, yeşil ve pembe tonlarıyla üzüm salkımı gibi yuvarlak yığınlar oluşturur. Bu dingin renkler yüzünden ona bakanın kalbini yatıştırdığına, nezaket ve duygusal denge getirdiğine inanılırdı.",
    en: "Smithsonite takes its name from the English chemist and mineralogist James Smithson, the man whose fortune, after his death, founded the famous Smithsonian Institution. An ore of zinc, this stone forms rounded, grape-cluster masses in soft blue, green, and pink tones. Because of these serene colors, it was believed to soothe the heart of the beholder and to bring kindness and emotional balance.",
    de: "Smithsonit leitet seinen Namen vom englischen Chemiker und Mineralogen James Smithson ab, dem Mann, dessen Vermögen nach seinem Tod die berühmte Smithsonian Institution begründete. Als Zinkerz bildet dieser Stein rundliche, traubenförmige Massen in zarten Blau-, Grün- und Rosatönen. Wegen dieser heiteren Farben glaubte man, er beruhige das Herz des Betrachters und bringe Sanftmut und seelisches Gleichgewicht.",
    es: "La smithsonita toma su nombre del químico y mineralogista inglés James Smithson, el hombre cuya fortuna, tras su muerte, fundó la célebre Institución Smithsonian. Mena de cinc, esta piedra forma masas redondeadas en racimo, en suaves tonos azules, verdes y rosados. Por estos colores serenos, se creía que apaciguaba el corazón de quien la contemplaba y que traía amabilidad y equilibrio emocional.",
    fr: "La smithsonite tire son nom du chimiste et minéralogiste anglais James Smithson, l'homme dont la fortune, après sa mort, fonda la célèbre Smithsonian Institution. Minerai de zinc, cette pierre forme des masses arrondies en grappe, dans de doux tons bleus, verts et roses. En raison de ces couleurs sereines, on croyait qu'elle apaisait le cœur de celui qui la contemplait et qu'elle apportait douceur et équilibre émotionnel.",
    ja: "スミソナイトは、イギリスの化学者であり鉱物学者でもあったジェームズ・スミソンにちなんで名づけられました。彼の財産は、その死後、かの有名なスミソニアン協会の設立をもたらした人物です。亜鉛の鉱石であるこの石は、柔らかな青や緑、桃色の色合いで、ぶどうの房のような丸みを帯びた塊をつくります。この穏やかな色ゆえに、見る者の心を和らげ、優しさと感情の均衡をもたらすと信じられていました。",
    pt: "A smithsonita tira seu nome do químico e mineralogista inglês James Smithson, o homem cuja fortuna, após sua morte, fundou a célebre Instituição Smithsonian. Minério de zinco, esta pedra forma massas arredondadas em cacho, em suaves tons de azul, verde e rosa. Por causa dessas cores serenas, acreditava-se que apaziguava o coração de quem a contemplava e que trazia gentileza e equilíbrio emocional."
  },
  "s115": {
    tr: "Adamit, adını 19. yüzyılda ilk örneklerini Şili'den toplayan Fransız mineralog Gilbert-Joseph Adam'dan alır. İçerdiği eser miktarda bakır yüzünden parlak sarı-yeşil rengi ultraviyole ışık altında canlı bir floresan ışıltısıyla parıldar. Bu neşeli, ışık saçan rengi yüzünden ona bakanın içine sevinç ve yaratıcılık aktardığı, karamsarlığı dağıttığı söylenirdi.",
    en: "Adamite takes its name from the French mineralogist Gilbert-Joseph Adam, who collected the first specimens from Chile in the 19th century. Because of the trace copper it contains, its bright yellow-green color glows with a vivid fluorescent shimmer under ultraviolet light. Because of this joyful, light-filled color, it was said to pour joy and creativity into the beholder and to dispel gloom.",
    de: "Adamin leitet seinen Namen vom französischen Mineralogen Gilbert-Joseph Adam ab, der im 19. Jahrhundert die ersten Exemplare aus Chile sammelte. Wegen des Spurenkupfers, das er enthält, leuchtet seine helle gelbgrüne Farbe unter ultraviolettem Licht in einem lebhaften fluoreszierenden Schimmer. Wegen dieser fröhlichen, lichterfüllten Farbe sagte man, er gieße Freude und Schöpferkraft in den Betrachter und vertreibe die Schwermut.",
    es: "La adamita toma su nombre del mineralogista francés Gilbert-Joseph Adam, que recogió los primeros ejemplares en Chile en el siglo XIX. Por el cobre en trazas que contiene, su brillante color amarillo-verdoso resplandece con un vívido destello fluorescente bajo la luz ultravioleta. Por este color alegre y luminoso, se decía que vertía gozo y creatividad en quien la contemplaba y que disipaba el desánimo.",
    fr: "L'adamite tire son nom du minéralogiste français Gilbert-Joseph Adam, qui recueillit les premiers spécimens au Chili au XIXe siècle. En raison du cuivre à l'état de traces qu'elle contient, sa couleur jaune-vert éclatante luit d'un vif éclat fluorescent sous la lumière ultraviolette. À cause de cette couleur joyeuse et lumineuse, on disait qu'elle versait joie et créativité en celui qui la contemplait et qu'elle dissipait la morosité.",
    ja: "アダマイトは、19世紀にチリで最初の標本を採集したフランスの鉱物学者ジルベール＝ジョゼフ・アダムにちなんで名づけられました。含まれるわずかな銅のために、その鮮やかな黄緑色は、紫外線の下で生き生きとした蛍光の煌めきを放ちます。この喜びに満ちた光あふれる色ゆえに、見る者の内に喜びと創造性を注ぎ込み、ふさぎを払うと言われていました。",
    pt: "A adamita tira seu nome do mineralogista francês Gilbert-Joseph Adam, que colheu os primeiros exemplares no Chile no século XIX. Por causa do cobre em traços que contém, sua brilhante cor amarelo-esverdeada resplandece com um vívido reflexo fluorescente sob a luz ultravioleta. Por essa cor alegre e luminosa, dizia-se que derramava alegria e criatividade em quem a contemplava e que dissipava o desânimo."
  },
  "s116": {
    tr: "Limon krizopras, krizoprasın açık, neredeyse limon yeşili bir çeşididir. Krizopras antik çağın en değerli taşlarından biriydi; adını Yunanca 'altın' ve 'pırasa-yeşili' sözcüklerinden alır ve Büyük İskender'in en sevdiği taş olduğu, onu savaşlarda kemerinde taşıdığı anlatılır. Bu yumuşak yeşil tonu yüzünden kalbi yatıştırdığı, bağışlamayı ve içsel yenilenmeyi kolaylaştırdığı söylenir.",
    en: "Lemon chrysoprase is a pale, almost lemon-green variety of chrysoprase. Chrysoprase was one of antiquity's most prized stones; its name comes from the Greek words for 'gold' and 'leek-green,' and it is said to have been Alexander the Great's favorite stone, worn in his belt during his campaigns. Because of this soft green tone, it is said to soothe the heart and to ease forgiveness and inner renewal.",
    de: "Zitronen-Chrysopras ist eine blasse, fast zitronengrüne Varietät des Chrysopras. Chrysopras war einer der geschätztesten Steine der Antike; sein Name stammt von den griechischen Wörtern für 'Gold' und 'lauchgrün', und es heißt, er sei Alexanders des Großen Lieblingsstein gewesen, den er während seiner Feldzüge in seinem Gürtel trug. Wegen dieses sanften Grüntons sagt man, er beruhige das Herz und erleichtere Vergebung und innere Erneuerung.",
    es: "La crisoprasa limón es una variedad pálida, casi verde limón, de la crisoprasa. La crisoprasa fue una de las piedras más preciadas de la Antigüedad; su nombre proviene de las palabras griegas para 'oro' y 'verde puerro', y se dice que fue la piedra favorita de Alejandro Magno, que la llevaba en su cinturón durante sus campañas. Por este suave tono verde, se dice que apacigua el corazón y facilita el perdón y la renovación interior.",
    fr: "La chrysoprase citron est une variété pâle, presque vert citron, de la chrysoprase. La chrysoprase fut l'une des pierres les plus prisées de l'Antiquité ; son nom vient des mots grecs signifiant 'or' et 'vert poireau', et l'on raconte qu'elle fut la pierre favorite d'Alexandre le Grand, qui la portait à sa ceinture durant ses campagnes. En raison de cette douce teinte verte, on dit qu'elle apaise le cœur et facilite le pardon et le renouveau intérieur.",
    ja: "レモンクリソプレーズは、クリソプレーズの淡い、ほとんどレモン色がかった緑の変種です。クリソプレーズは古代で最も珍重された石のひとつでした。その名は「金」と「ニラのような緑」を意味するギリシャ語に由来し、アレクサンドロス大王の愛石で、遠征の折にはベルトに身につけていたと伝えられています。この柔らかな緑の色合いゆえに、心を和らげ、許しと内なる再生を促すと言われています。",
    pt: "A crisoprásio limão é uma variedade pálida, quase verde-limão, do crisoprásio. O crisoprásio foi uma das pedras mais valorizadas da Antiguidade; seu nome vem das palavras gregas para 'ouro' e 'verde-alho-poró', e diz-se que foi a pedra favorita de Alexandre, o Grande, que a usava em seu cinto durante as campanhas. Por causa desse suave tom verde, diz-se que apazigua o coração e facilita o perdão e a renovação interior."
  },
  "s117": {
    tr: "Lazulit, adını Arapça/Farsça kökenli 'gök mavisi' anlamına gelen sözcükten alır; aynı kök lapis lazuli ve azurit gibi mavi taşların adında da geçer. Derin gök mavisi rengiyle, eski madenciler bu nadir taşı bir parça dökülmüş gökyüzü gibi görürdü. Bu sakin mavisi yüzünden onu taşıyanın zihnini odakladığına, sezgiyi keskinleştirip iç berraklık verdiğine inanılırdı.",
    en: "Lazulite takes its name from a word of Arabic/Persian origin meaning 'sky-blue'; the same root appears in the names of blue stones like lapis lazuli and azurite. With its deep azure color, old miners saw this rare stone as a fragment of fallen sky. Because of this calm blue, it was believed to focus the mind of the one who carried it, to sharpen intuition, and to grant inner clarity.",
    de: "Lazulith leitet seinen Namen von einem Wort arabisch/persischen Ursprungs ab, das 'himmelblau' bedeutet; dieselbe Wurzel findet sich in den Namen blauer Steine wie Lapislazuli und Azurit. Mit seiner tiefen azurblauen Farbe sahen alte Bergleute diesen seltenen Stein als ein Stück herabgefallenen Himmels. Wegen dieses ruhigen Blaus glaubte man, er bündele den Geist seines Trägers, schärfe die Intuition und schenke innere Klarheit.",
    es: "La lazulita toma su nombre de una palabra de origen árabe/persa que significa 'azul cielo'; la misma raíz aparece en los nombres de piedras azules como el lapislázuli y la azurita. Con su profundo color azur, los antiguos mineros veían esta rara piedra como un fragmento de cielo caído. Por este azul sereno, se creía que enfocaba la mente de quien la portaba, agudizaba la intuición y otorgaba claridad interior.",
    fr: "La lazulite tire son nom d'un mot d'origine arabe/persane signifiant 'bleu ciel' ; la même racine se retrouve dans les noms de pierres bleues comme le lapis-lazuli et l'azurite. Avec sa profonde couleur azur, les anciens mineurs voyaient cette pierre rare comme un fragment de ciel tombé. En raison de ce bleu paisible, on croyait qu'elle concentrait l'esprit de celui qui la portait, aiguisait l'intuition et offrait une clarté intérieure.",
    ja: "ラズライトは「空色」を意味するアラビア語・ペルシア語起源の語に由来し、同じ語根はラピスラズリやアズライトといった青い石の名にも見られます。深い空色をもつこの稀少な石を、昔の鉱夫たちは落ちてきた空のかけらのように見ていました。この静かな青ゆえに、持つ者の心を集中させ、直感を研ぎ澄まし、内なる明晰さを与えると信じられていました。",
    pt: "A lazulita tira seu nome de uma palavra de origem árabe/persa que significa 'azul-celeste'; a mesma raiz aparece nos nomes de pedras azuis como o lápis-lazúli e a azurita. Com sua profunda cor de azul, os antigos mineiros viam esta pedra rara como um fragmento de céu caído. Por causa desse azul sereno, acreditava-se que concentrava a mente de quem a portava, aguçava a intuição e concedia clareza interior."
  },
  "s118": {
    tr: "Kavansit, adını içeriğindeki elementlerden alır: kalsiyum, vanadyum ve silikat. 1960'larda tanımlanan bu genç ve nadir taş, en güzel örneklerini Hindistan'ın Pune yakınlarındaki volkanik kayalardan verir; orada tortu boşluklarında parlak gök-mavisi rozetler hâlinde büyür. Bu canlı mavisi yüzünden modern toplayıcılar ona açık iletişim, neşe ve içsel ifade taşıdığını söyler.",
    en: "Cavansite takes its name from the elements it contains: calcium, vanadium, and silicate. Described in the 1960s, this young and rare stone yields its finest specimens from the volcanic rocks near Pune in India, where it grows as bright sky-blue rosettes in cavities of the rock. Because of this vivid blue, modern collectors say it carries open communication, joy, and inner expression.",
    de: "Cavansit leitet seinen Namen von den Elementen ab, die er enthält: Calcium, Vanadium und Silikat. Dieser in den 1960er Jahren beschriebene junge und seltene Stein liefert seine schönsten Exemplare aus den vulkanischen Gesteinen bei Pune in Indien, wo er als leuchtend himmelblaue Rosetten in Hohlräumen des Gesteins wächst. Wegen dieses lebhaften Blaus sagen moderne Sammler, er trage offene Kommunikation, Freude und innere Ausdruckskraft in sich.",
    es: "La cavansita toma su nombre de los elementos que contiene: calcio, vanadio y silicato. Descrita en la década de 1960, esta piedra joven y rara da sus mejores ejemplares en las rocas volcánicas cercanas a Pune, en la India, donde crece como brillantes rosetas azul cielo en las cavidades de la roca. Por este azul vívido, los coleccionistas modernos dicen que porta comunicación abierta, alegría y expresión interior.",
    fr: "La cavansite tire son nom des éléments qu'elle contient : calcium, vanadium et silicate. Décrite dans les années 1960, cette pierre jeune et rare livre ses plus beaux spécimens dans les roches volcaniques près de Pune, en Inde, où elle croît en rosettes d'un bleu ciel éclatant dans les cavités de la roche. En raison de ce bleu vif, les collectionneurs modernes disent qu'elle porte communication ouverte, joie et expression intérieure.",
    ja: "カバンシ石は、含まれる元素であるカルシウム（calcium）、バナジウム（vanadium）、ケイ酸塩（silicate）にちなんで名づけられました。1960年代に記載されたこの若く稀少な石は、インドのプネー近郊の火山岩から最も美しい標本を産し、岩の空隙の中に鮮やかな空色のロゼットとして育ちます。この鮮烈な青ゆえに、現代の収集家は、開かれた対話と喜び、内なる表現を宿す石だと語ります。",
    pt: "A cavansita tira seu nome dos elementos que contém: cálcio, vanádio e silicato. Descrita na década de 1960, esta pedra jovem e rara dá seus melhores exemplares nas rochas vulcânicas perto de Pune, na Índia, onde cresce como brilhantes rosetas azul-celeste nas cavidades da rocha. Por causa desse azul vívido, os colecionadores modernos dizem que ela carrega comunicação aberta, alegria e expressão interior."
  },
  "s119": {
    tr: "Eudialit, adını Yunanca 'kolayca çözünen' anlamına gelen sözcükten alır; çünkü asitte diğer minerallerden daha kolay çözünür ve mineraloglar onu böyle tanır. Grönland ve Rusya'nın Kola Yarımadası'ndaki nadir kayalarda bulunan ahududu kırmızısı bir taştır; halk arasında 'ejderha kanı' olarak da anılır. Bu sıcak kırmızısı yüzünden öz-sevgiyi beslediği, kalp ile zihni uyumlulaştırıp amaç duygusu verdiği söylenir.",
    en: "Eudialyte takes its name from the Greek word meaning 'easily dissolved,' because it dissolves in acid more readily than other minerals, and mineralogists recognize it that way. It is a raspberry-red stone found in the rare rocks of Greenland and Russia's Kola Peninsula; it is also popularly called 'dragon's blood.' Because of this warm red, it is said to nourish self-love, to harmonize heart and mind, and to give a sense of purpose.",
    de: "Eudialyt leitet seinen Namen vom griechischen Wort für 'leicht löslich' ab, denn er löst sich in Säure leichter als andere Minerale, und Mineralogen erkennen ihn daran. Es ist ein himbeerroter Stein, der in den seltenen Gesteinen Grönlands und der russischen Halbinsel Kola vorkommt; volkstümlich wird er auch 'Drachenblut' genannt. Wegen dieses warmen Rots sagt man, er nähre die Selbstliebe, bringe Herz und Geist in Einklang und schenke ein Gefühl von Sinn.",
    es: "La eudialita toma su nombre de la palabra griega que significa 'fácilmente disuelto', pues se disuelve en ácido con más facilidad que otros minerales, y los mineralogistas la reconocen así. Es una piedra de color rojo frambuesa hallada en las raras rocas de Groenlandia y de la península de Kola, en Rusia; también se la llama popularmente 'sangre de dragón'. Por este rojo cálido, se dice que nutre el amor propio, armoniza el corazón y la mente y otorga un sentido de propósito.",
    fr: "L'eudialyte tire son nom du mot grec signifiant 'facilement dissous', car elle se dissout dans l'acide plus aisément que d'autres minéraux, et les minéralogistes la reconnaissent ainsi. C'est une pierre rouge framboise que l'on trouve dans les roches rares du Groenland et de la péninsule de Kola, en Russie ; on l'appelle aussi populairement 'sang de dragon'. En raison de ce rouge chaleureux, on dit qu'elle nourrit l'amour de soi, harmonise le cœur et l'esprit et offre un sentiment de dessein.",
    ja: "ユーディアライトは「容易に溶ける」を意味するギリシャ語に由来します。他の鉱物よりも酸に溶けやすく、鉱物学者はそれによって見分けるからです。グリーンランドやロシアのコラ半島の稀少な岩石に見られる、ラズベリー色の赤い石で、俗に「竜の血」とも呼ばれます。この温かな赤ゆえに、自己愛を育み、心と頭を調和させ、目的の感覚を与えると言われています。",
    pt: "A eudialita tira seu nome da palavra grega que significa 'facilmente dissolvido', pois se dissolve em ácido com mais facilidade do que outros minerais, e os mineralogistas a reconhecem assim. É uma pedra de cor vermelho-framboesa encontrada nas raras rochas da Groenlândia e da península de Kola, na Rússia; também é popularmente chamada de 'sangue de dragão'. Por causa desse vermelho caloroso, diz-se que nutre o amor-próprio, harmoniza coração e mente e concede um sentido de propósito."
  }
};
