export const STONELORE_G1 = {
  "s200": {
    tr: "Adını Yunanca 'gül' (rhodon) ve 'renk' (khros) sözcüklerinden alan rodokrozit, ilk kez 1813'te bilime tanımlanmış; en güzel damarları ise Arjantin'in Inca Huasi madeninde bulunmuştur. Bu yüzden 'İnka gülü' diye anılır ve yöre halkı arasında taşın, eski hükümdarların kanının zamanla taşa dönüştüğüne inanılırdı. Kalp çakrasıyla bağdaştırılan pembe katmanları, öz-sevgi ve şefkatin sabırla biriken halkaları gibi düşünülür.",
    en: "Named from the Greek words rhodon ('rose') and khros ('color'), rhodochrosite was first described to science in 1813, and its finest banded veins come from the Inca Huasi mine in Argentina. For this reason it is called the 'Inca rose,' and local lore held that the stone was the blood of ancient rulers slowly turned to crystal. Tied to the heart chakra, its rings of pink are imagined as the patient layers in which self-love and compassion gather over time.",
    de: "Benannt nach den griechischen Wörtern rhodon ('Rose') und khros ('Farbe'), wurde der Rhodochrosit 1813 erstmals wissenschaftlich beschrieben; seine schönsten gebänderten Adern stammen aus der Inca-Huasi-Mine in Argentinien. Daher nennt man ihn 'Inkarose,' und im Volksglauben galt der Stein als das Blut alter Herrscher, das mit der Zeit zu Kristall wurde. Mit dem Herzchakra verbunden, gelten seine rosa Ringe als die geduldigen Schichten, in denen sich Selbstliebe und Mitgefühl ansammeln.",
    es: "Su nombre proviene de las palabras griegas rhodon ('rosa') y khros ('color'); la rodocrosita fue descrita por la ciencia en 1813 y sus vetas más bellas proceden de la mina Inca Huasi, en Argentina. Por eso se la llama la 'rosa de los incas,' y la tradición local decía que la piedra era la sangre de antiguos gobernantes, vuelta cristal con el tiempo. Vinculada al chakra del corazón, sus anillos rosados evocan las capas pacientes donde se acumulan el amor propio y la compasión.",
    fr: "Tirant son nom des mots grecs rhodon ('rose') et khros ('couleur'), la rhodochrosite fut décrite par la science en 1813, et ses plus belles veines rubanées proviennent de la mine d'Inca Huasi, en Argentine. On l'appelle ainsi la 'rose des Incas,' et la tradition locale voulait que la pierre fût le sang d'anciens souverains, peu à peu changé en cristal. Liée au chakra du cœur, ses anneaux roses évoquent les couches patientes où s'accumulent l'amour de soi et la compassion.",
    ja: "ギリシャ語の rhodon（薔薇）と khros（色）に由来するロードクロサイトは、1813年に学術的に記載され、その最も美しい縞模様の鉱脈はアルゼンチンのインカ・ワシ鉱山から産する。そのため『インカの薔薇』と呼ばれ、土地の言い伝えでは、古代の王たちの血が長い時を経て結晶になったものとされた。ハートチャクラと結びつくその桃色の層は、自己愛と慈しみが時とともに静かに積み重なる輪のように考えられている。",
    pt: "Com nome derivado das palavras gregas rhodon ('rosa') e khros ('cor'), a rodocrosita foi descrita pela ciência em 1813, e suas veias listradas mais belas vêm da mina de Inca Huasi, na Argentina. Por isso é chamada de 'rosa dos incas,' e a tradição local dizia que a pedra era o sangue de antigos governantes, transformado em cristal com o tempo. Ligada ao chacra do coração, seus anéis rosados evocam as camadas pacientes onde o amor-próprio e a compaixão se acumulam."
  },
  "s201": {
    tr: "Adını Yunanca 'içinden görmek' (dia-optomai) anlamına gelen sözcükten alan dioptaz, taşı kesenin içindeki ayrılma çizgilerini görebilmesinden ötürü böyle anılır. 1785'te Kazakistan'daki bir bakır yatağında bulunan bu zümrüt-yeşili kristal, ilk başta zümrütle karıştırıldı; sonradan bakırdan gelen rengiyle ayrı bir mineral olduğu anlaşıldı. Kalp çakrasıyla bağdaştırılan canlı yeşili, affetme ve yenilenmenin tazeliğini hatırlatır sayılır.",
    en: "Dioptase takes its name from the Greek dia-optomai, 'to see through,' because a cutter can glimpse the cleavage planes inside the stone. Found in 1785 in a copper deposit in Kazakhstan, this emerald-green crystal was at first mistaken for emerald; only later was it recognized as a distinct mineral colored by copper. Linked to the heart chakra, its vivid green is felt to recall the freshness of forgiveness and renewal.",
    de: "Der Dioptas trägt seinen Namen vom griechischen dia-optomai, 'hindurchsehen,' weil ein Schleifer die Spaltflächen im Inneren des Steins erkennen kann. 1785 in einer Kupferlagerstätte in Kasachstan entdeckt, wurde dieser smaragdgrüne Kristall zunächst für Smaragd gehalten; erst später erkannte man ihn als eigenes, von Kupfer gefärbtes Mineral. Mit dem Herzchakra verbunden, soll sein lebhaftes Grün an die Frische von Vergebung und Erneuerung erinnern.",
    es: "La dioptasa debe su nombre al griego dia-optomai, 'ver a través,' porque el tallista alcanza a vislumbrar los planos de exfoliación dentro de la piedra. Hallada en 1785 en un yacimiento de cobre de Kazajistán, este cristal verde esmeralda fue confundido al principio con la esmeralda; solo después se reconoció como mineral propio, coloreado por el cobre. Vinculada al chakra del corazón, su verde vivo evoca la frescura del perdón y la renovación.",
    fr: "La dioptase tire son nom du grec dia-optomai, 'voir à travers,' car le tailleur peut entrevoir les plans de clivage à l'intérieur de la pierre. Découverte en 1785 dans un gisement de cuivre du Kazakhstan, ce cristal vert émeraude fut d'abord confondu avec l'émeraude ; on le reconnut seulement plus tard comme un minéral distinct, coloré par le cuivre. Liée au chakra du cœur, son vert éclatant évoque la fraîcheur du pardon et du renouveau.",
    ja: "ディオプテーズの名は、職人が石の内部の劈開面を見透かせることから、ギリシャ語の dia-optomai（透かして見る）に由来する。1785年にカザフスタンの銅鉱床で発見されたこのエメラルド色の結晶は、当初エメラルドと取り違えられ、のちに銅によって色づく独立した鉱物だと認められた。ハートチャクラと結びつくその鮮やかな緑は、許しと再生のみずみずしさを思い起こさせるとされる。",
    pt: "A dioptásio recebe seu nome do grego dia-optomai, 'ver através,' pois o lapidário consegue vislumbrar os planos de clivagem dentro da pedra. Encontrado em 1785 em um depósito de cobre no Cazaquistão, esse cristal verde-esmeralda foi a princípio confundido com a esmeralda; só depois foi reconhecido como mineral distinto, colorido pelo cobre. Ligado ao chacra do coração, seu verde vivo evoca o frescor do perdão e da renovação."
  },
  "s202": {
    tr: "Danburit, 1839'da Amerika'nın Connecticut eyaletindeki Danbury kasabası yakınlarında ilk kez bulunduğu için bu adı taşır; kasaba sonradan büyüyüp mineralin tip-yatağının üzerine yayılmıştır. Çoğu zaman su gibi berrak ya da soluk pembe olan bu kristalin, ışığı kırarken neredeyse görünmez kalan saflığı, ona melekvari bir sükûnet atfedilmesine yol açtı. Taç çakrasıyla bağdaştırılan bu duruluk, huzur ve ferahlığın sessiz bir simgesi sayılır.",
    en: "Danburite is named for Danbury, Connecticut, in the United States, where it was first found in 1839; the town later grew until it spread over the mineral's type locality. Often water-clear or pale pink, this crystal's purity—nearly invisible as it bends the light—led people to ascribe to it an angelic calm. Associated with the crown chakra, that clarity is taken as a quiet emblem of peace and lightness.",
    de: "Der Danburit ist nach Danbury in Connecticut, USA, benannt, wo er 1839 erstmals gefunden wurde; die Stadt wuchs später über die Typlokalität des Minerals hinweg. Oft wasserklar oder blassrosa, führte die Reinheit dieses Kristalls—der das Licht beinahe unsichtbar bricht—dazu, ihm eine engelhafte Ruhe zuzuschreiben. Mit dem Kronenchakra verbunden, gilt diese Klarheit als stilles Sinnbild von Frieden und Leichtigkeit.",
    es: "La danburita debe su nombre a Danbury, en Connecticut, Estados Unidos, donde se halló por primera vez en 1839; el pueblo creció después hasta cubrir la localidad tipo del mineral. A menudo transparente como el agua o de un rosa pálido, la pureza de este cristal—casi invisible al desviar la luz—llevó a atribuirle una calma angélica. Asociada al chakra de la corona, esa nitidez se considera un emblema sereno de paz y ligereza.",
    fr: "La danburite tire son nom de Danbury, dans le Connecticut, aux États-Unis, où elle fut découverte pour la première fois en 1839 ; la ville s'étendit ensuite jusqu'à recouvrir le gisement type du minéral. Souvent limpide comme l'eau ou rose pâle, la pureté de ce cristal—presque invisible quand il dévie la lumière—lui valut d'être associée à un calme angélique. Liée au chakra couronne, cette clarté passe pour un emblème paisible de paix et de légèreté.",
    ja: "ダンブライトは、1839年にアメリカ・コネチカット州のダンベリーで初めて発見されたことからその名を持つ。町はのちに広がり、この鉱物の原産地の上に重なっていった。水のように澄んだ、あるいは淡い桃色のこの結晶は、光を屈折させてもほとんど見えないほどの透明さから、天使のような静けさを宿すとされてきた。クラウンチャクラと結びつくその澄明さは、平安と軽やかさの静かな象徴とされる。",
    pt: "A danburita recebe o nome de Danbury, em Connecticut, nos Estados Unidos, onde foi encontrada pela primeira vez em 1839; a cidade depois cresceu até se estender sobre a localidade-tipo do mineral. Muitas vezes transparente como água ou rosa-pálido, a pureza desse cristal—quase invisível ao desviar a luz—levou as pessoas a lhe atribuir uma calma angelical. Associada ao chacra da coroa, essa clareza é vista como um emblema sereno de paz e leveza."
  },
  "s203": {
    tr: "Aleksandrit, 1830'larda Rusya'nın Ural Dağları'ndaki zümrüt madenlerinde bulundu ve geleceğin çarı II. Aleksandr'ın adıyla anıldı. Gündüz ışığında yeşil, mum ışığında kırmızı görünen bu olağanüstü renk değişimi, Çarlık Rusya'sının yeşil ve kırmızı askeri renklerini hatırlattığı için ulusal bir taş sayıldı. Kalp çakrasıyla bağdaştırılan bu ikili doğası, dönüşümün ve karşıtlıklar arasında denge kurmanın sembolü olarak yorumlanır.",
    en: "Alexandrite was found in the 1830s in the emerald mines of Russia's Ural Mountains and named for the future tsar Alexander II. Its remarkable color change—green in daylight, red by candlelight—recalled the green and red military colors of imperial Russia, and so it was honored as a national stone. Tied to the heart chakra, this dual nature is read as a symbol of transformation and of holding balance between opposites.",
    de: "Der Alexandrit wurde in den 1830er Jahren in den Smaragdminen des russischen Urals gefunden und nach dem künftigen Zaren Alexander II. benannt. Sein bemerkenswerter Farbwechsel—grün im Tageslicht, rot im Kerzenschein—erinnerte an die grün-roten Militärfarben des kaiserlichen Russlands und machte ihn so zum Nationalstein. Mit dem Herzchakra verbunden, deutet man dieses doppelte Wesen als Sinnbild der Wandlung und des Gleichgewichts zwischen Gegensätzen.",
    es: "La alejandrita se halló en la década de 1830 en las minas de esmeralda de los montes Urales, en Rusia, y se llamó así por el futuro zar Alejandro II. Su notable cambio de color—verde a la luz del día, rojo a la luz de las velas—evocaba los colores militares verde y rojo de la Rusia imperial, por lo que se la veneró como piedra nacional. Vinculada al chakra del corazón, esa doble naturaleza se interpreta como símbolo de transformación y de equilibrio entre opuestos.",
    fr: "L'alexandrite fut découverte dans les années 1830 dans les mines d'émeraude de l'Oural, en Russie, et nommée d'après le futur tsar Alexandre II. Son changement de couleur remarquable—verte au jour, rouge à la lueur des bougies—rappelait les couleurs militaires vertes et rouges de la Russie impériale, ce qui en fit une pierre nationale. Liée au chakra du cœur, cette double nature se lit comme un symbole de transformation et d'équilibre entre les contraires.",
    ja: "アレキサンドライトは1830年代、ロシア・ウラル山脈のエメラルド鉱山で発見され、のちの皇帝アレクサンドル2世にちなんで名づけられた。昼光では緑、ろうそくの灯では赤に見えるその驚くべき変色は、帝政ロシアの緑と赤の軍色を思わせたため、国の石として尊ばれた。ハートチャクラと結びつくこの二面性は、変容と、相反するものの間に均衡を保つことの象徴とされている。",
    pt: "A alexandrita foi encontrada na década de 1830 nas minas de esmeralda dos montes Urais, na Rússia, e recebeu o nome do futuro czar Alexandre II. Sua notável mudança de cor—verde à luz do dia, vermelha à luz de velas—lembrava as cores militares verde e vermelho da Rússia imperial, e por isso foi honrada como pedra nacional. Ligada ao chacra do coração, essa natureza dupla é lida como símbolo de transformação e de equilíbrio entre opostos."
  },
  "s204": {
    tr: "Herkimer elması aslında elmas değil, ABD'nin New York eyaletindeki Herkimer County'de bulunan, kendiliğinden çift uçlu ve cam berraklığında bir kuvars türüdür. Yüzeyi öyle parlak ve kusursuz biçimlidir ki, on sekizinci yüzyılda yöredeki işçiler bu taşları gerçek elmas sanmıştır. Taç çakrasıyla bağdaştırılan bu kristalin iki ucu, yukarı ve içe doğru aynı anda açılan bir netliğin, berraklığın ve uyanışın simgesi olarak görülür.",
    en: "The Herkimer diamond is not truly a diamond but a kind of quartz from Herkimer County in New York State, naturally double-terminated and glass-clear. Its faces are so bright and so perfectly shaped that in the eighteenth century local laborers mistook the stones for real diamonds. Associated with the crown chakra, the crystal's two points are seen as an emblem of a clarity that opens upward and inward at once—of lucidity and awakening.",
    de: "Der Herkimer-Diamant ist kein echter Diamant, sondern eine Quarzart aus Herkimer County im US-Bundesstaat New York, von Natur aus doppelt endend und glasklar. Seine Flächen sind so hell und so vollkommen geformt, dass Arbeiter der Gegend die Steine im achtzehnten Jahrhundert für echte Diamanten hielten. Mit dem Kronenchakra verbunden, gelten die zwei Spitzen des Kristalls als Sinnbild einer Klarheit, die sich zugleich nach oben und nach innen öffnet—für Luzidität und Erwachen.",
    es: "El diamante Herkimer no es en verdad un diamante, sino una variedad de cuarzo del condado de Herkimer, en el estado de Nueva York, biterminado por naturaleza y transparente como el vidrio. Sus caras son tan brillantes y de forma tan perfecta que en el siglo XVIII los obreros del lugar confundieron las piedras con diamantes reales. Asociado al chakra de la corona, las dos puntas del cristal se ven como emblema de una claridad que se abre a la vez hacia arriba y hacia dentro—de lucidez y despertar.",
    fr: "Le diamant Herkimer n'est pas vraiment un diamant, mais une variété de quartz du comté de Herkimer, dans l'État de New York, naturellement biterminée et limpide comme le verre. Ses faces sont si brillantes et si parfaitement formées qu'au dix-huitième siècle les ouvriers de la région prirent ces pierres pour de vrais diamants. Lié au chakra couronne, les deux pointes du cristal passent pour l'emblème d'une clarté qui s'ouvre à la fois vers le haut et vers l'intérieur—de lucidité et d'éveil.",
    ja: "ハーキマー・ダイヤモンドは実際にはダイヤモンドではなく、アメリカ・ニューヨーク州ハーキマー郡で産する、生まれつき両端が尖りガラスのように澄んだ水晶の一種である。その面はあまりに明るく完璧な形をしているため、十八世紀には土地の労働者がこれを本物のダイヤと取り違えたという。クラウンチャクラと結びつくこの結晶の二つの先端は、上方と内側へ同時に開く明晰さ、すなわち澄明と目覚めの象徴とされている。",
    pt: "O diamante Herkimer não é de fato um diamante, mas uma variedade de quartzo do condado de Herkimer, no estado de Nova York, naturalmente biterminada e transparente como vidro. Suas faces são tão brilhantes e de forma tão perfeita que, no século XVIII, os trabalhadores da região confundiram as pedras com diamantes verdadeiros. Associado ao chacra da coroa, as duas pontas do cristal são vistas como emblema de uma clareza que se abre ao mesmo tempo para cima e para dentro—de lucidez e despertar."
  },
  "s205": {
    tr: "Rutilli kuvars, berrak kuvarsın içinde altın, bakır ya da kızıl renkli ince rutil iğnelerinin doğal olarak büyümesiyle oluşur; bu iplik gibi kristaller halk arasında 'Venüs'ün saçı' ya da 'aşk okları' diye anılmıştır. Rutil adı, kızıl rengi nedeniyle Latince 'kızıllık' (rutilus) sözcüğünden gelir. Solar pleksus çakrasıyla bağdaştırılan bu altın iplikler, içsel gücün ve ilhamın taşın derinliğinde donmuş ışınları gibi düşünülür.",
    en: "Rutilated quartz forms when fine golden, coppery or reddish needles of rutile grow naturally inside clear quartz; these thread-like crystals were popularly called 'Venus hair' or 'love's arrows.' The name rutile comes from the Latin rutilus, 'reddish,' for its ruddy color. Associated with the solar plexus chakra, these golden threads are imagined as rays of inner strength and inspiration, frozen in the depth of the stone.",
    de: "Rutilquarz entsteht, wenn feine goldene, kupferne oder rötliche Rutilnadeln auf natürliche Weise im klaren Quarz wachsen; diese fadenartigen Kristalle nannte man im Volksmund 'Venushaar' oder 'Liebespfeile.' Der Name Rutil stammt vom lateinischen rutilus, 'rötlich,' nach seiner rötlichen Farbe. Mit dem Solarplexuschakra verbunden, denkt man sich diese goldenen Fäden als Strahlen innerer Stärke und Inspiration, eingefroren in der Tiefe des Steins.",
    es: "El cuarzo rutilado se forma cuando finas agujas de rutilo doradas, cobrizas o rojizas crecen de modo natural dentro del cuarzo transparente; estos cristales filiformes se llamaron popularmente 'cabello de Venus' o 'flechas del amor.' El nombre rutilo viene del latín rutilus, 'rojizo,' por su color encendido. Asociado al chakra del plexo solar, esos hilos dorados se imaginan como rayos de fuerza interior e inspiración, congelados en la hondura de la piedra.",
    fr: "Le quartz rutile se forme lorsque de fines aiguilles dorées, cuivrées ou rougeâtres de rutile croissent naturellement à l'intérieur du quartz limpide ; ces cristaux filiformes furent populairement appelés 'cheveux de Vénus' ou 'flèches de l'amour.' Le nom rutile vient du latin rutilus, 'rougeâtre,' à cause de sa couleur ardente. Lié au chakra du plexus solaire, ces fils dorés sont imaginés comme des rayons de force intérieure et d'inspiration, figés dans la profondeur de la pierre.",
    ja: "ルチルクォーツは、透明な水晶の内部に金色・銅色・赤みを帯びたルチルの細い針が自然に成長して生まれる。この糸のような結晶は、俗に『ヴィーナスの髪』や『愛の矢』と呼ばれた。ルチルの名は、その赤みを帯びた色からラテン語の rutilus（赤らんだ）に由来する。ソーラープレクサスチャクラと結びつくこの金の糸は、内なる力とひらめきの光線が石の深みに凍りついたものと想像される。",
    pt: "O quartzo rutilado se forma quando finas agulhas douradas, acobreadas ou avermelhadas de rutilo crescem naturalmente dentro do quartzo transparente; esses cristais filiformes foram popularmente chamados de 'cabelo de Vênus' ou 'flechas do amor.' O nome rutilo vem do latim rutilus, 'avermelhado,' por sua cor ardente. Associado ao chacra do plexo solar, esses fios dourados são imaginados como raios de força interior e inspiração, congelados na profundeza da pedra."
  },
  "s206": {
    tr: "Pembe turmalin, turmalin ailesinin gül renkli üyesidir; adı Seylan'da (Sri Lanka) konuşulan Sinhalaca 'turamali' sözcüğünden gelir ve 'karışık renkli taş' anlamına geldiği söylenir. Hollandalı tüccarlar bu taşları on yedinci yüzyılda Avrupa'ya getirdiğinde, ısıtıldığında küçük partikülleri çekip ittiği fark edildiği için 'kül çeken' anlamına gelen 'aschentrekker' adıyla anıldı. Kalp çakrasıyla bağdaştırılan yumuşak pembesi, sevginin ve duygusal güvenliğin nazik bir hatırlatıcısı sayılır.",
    en: "Pink tourmaline is the rose-colored member of the tourmaline family; its name comes from the Sinhala word 'turamali' of Ceylon (Sri Lanka), said to mean 'stone of mixed colors.' When Dutch traders brought these stones to Europe in the seventeenth century, they noticed that, once warmed, the crystal attracted and repelled small particles, and so called it 'aschentrekker,' the 'ash-drawer.' Tied to the heart chakra, its soft pink is taken as a gentle reminder of love and emotional safety.",
    de: "Der rosa Turmalin ist das rosenfarbene Mitglied der Turmalinfamilie; sein Name stammt vom singhalesischen Wort 'turamali' aus Ceylon (Sri Lanka), das 'Stein gemischter Farben' bedeuten soll. Als niederländische Händler diese Steine im siebzehnten Jahrhundert nach Europa brachten, bemerkten sie, dass der Kristall erwärmt kleine Teilchen anzog und abstieß, und nannten ihn daher 'aschentrekker,' den 'Aschenzieher.' Mit dem Herzchakra verbunden, gilt sein sanftes Rosa als zarte Erinnerung an Liebe und emotionale Geborgenheit.",
    es: "La turmalina rosa es el miembro rosado de la familia de las turmalinas; su nombre proviene de la palabra cingalesa 'turamali' de Ceilán (Sri Lanka), que se dice significa 'piedra de colores mezclados.' Cuando los comerciantes neerlandeses trajeron estas piedras a Europa en el siglo XVII, notaron que, al calentarse, el cristal atraía y repelía pequeñas partículas, y la llamaron 'aschentrekker,' la 'atrae-cenizas.' Vinculada al chakra del corazón, su rosa suave se considera un recordatorio gentil del amor y de la seguridad emocional.",
    fr: "La tourmaline rose est le membre rosé de la famille des tourmalines ; son nom vient du mot cingalais 'turamali' de Ceylan (Sri Lanka), que l'on dit signifier 'pierre aux couleurs mêlées.' Quand les marchands néerlandais apportèrent ces pierres en Europe au dix-septième siècle, ils remarquèrent que, une fois chauffé, le cristal attirait et repoussait de petites particules, et l'appelèrent 'aschentrekker,' la 'tireuse de cendres.' Liée au chakra du cœur, son rose tendre passe pour un doux rappel de l'amour et de la sécurité affective.",
    ja: "ピンクトルマリンはトルマリン一族の薔薇色の一員で、その名はセイロン（スリランカ）のシンハラ語『turamali』に由来し、『色の混じった石』を意味するといわれる。十七世紀にオランダ商人がこれをヨーロッパへ持ち込んだ際、温めると結晶が小さな粒を引き寄せたり退けたりすることに気づき、『灰を引く者』を意味する『アスヘントレッケル』と呼んだ。ハートチャクラと結びつくその柔らかな桃色は、愛と心の安らぎをそっと思い出させるものとされる。",
    pt: "A turmalina rosa é o membro de cor rósea da família das turmalinas; seu nome vem da palavra cingalesa 'turamali' do Ceilão (Sri Lanka), que se diz significar 'pedra de cores misturadas.' Quando os comerciantes holandeses trouxeram essas pedras à Europa no século XVII, notaram que, ao ser aquecido, o cristal atraía e repelia pequenas partículas, e o chamaram de 'aschentrekker,' o 'puxa-cinzas.' Ligada ao chacra do coração, seu rosa suave é visto como um lembrete gentil do amor e da segurança emocional."
  },
  "s207": {
    tr: "Apofillit, adını Yunanca 'soyulmak, pul pul ayrılmak' anlamına gelen sözcükten alır; çünkü ısıtıldığında yüzeyi ince katmanlar hâlinde soyulur. En berrak ve parlak kristalleri Hindistan'ın Deccan yaylasındaki eski lav boşluklarında, zeolitlerle birlikte oluşur ve cam gibi içe işleyen bir ışıltıyla parlar. Taç çakrasıyla bağdaştırılan bu duru piramitler, ışığın ve ferahlığın yukarıya doğru açılan saydam birer penceresi gibi düşünülür.",
    en: "Apophyllite takes its name from a Greek word meaning 'to flake off,' for its surface peels away in thin layers when heated. Its clearest, brightest crystals form alongside zeolites in the old lava cavities of India's Deccan plateau, glowing with a glassy, inward light. Associated with the crown chakra, these clear little pyramids are imagined as translucent windows of light and lightness, opening upward.",
    de: "Der Apophyllit trägt seinen Namen von einem griechischen Wort für 'abblättern,' denn seine Oberfläche löst sich beim Erhitzen in dünnen Schichten. Seine klarsten, hellsten Kristalle bilden sich gemeinsam mit Zeolithen in den alten Lavahohlräumen des indischen Dekkan-Plateaus und leuchten mit einem glasigen, nach innen gerichteten Licht. Mit dem Kronenchakra verbunden, denkt man sich diese klaren kleinen Pyramiden als durchscheinende Fenster aus Licht und Leichtigkeit, die sich nach oben öffnen.",
    es: "La apofilita debe su nombre a una palabra griega que significa 'desprenderse en láminas,' pues su superficie se exfolia en capas finas al calentarse. Sus cristales más claros y brillantes se forman junto a las zeolitas en las antiguas cavidades de lava de la meseta del Decán, en la India, y brillan con una luz vítrea que parece interior. Asociada al chakra de la corona, esas pequeñas pirámides límpidas se imaginan como ventanas translúcidas de luz y ligereza, abiertas hacia arriba.",
    fr: "L'apophyllite tire son nom d'un mot grec signifiant 's'exfolier,' car sa surface se détache en couches minces lorsqu'on la chauffe. Ses cristaux les plus clairs et les plus brillants se forment auprès des zéolites dans les anciennes cavités de lave du plateau du Deccan, en Inde, et brillent d'une lumière vitreuse, comme intérieure. Liée au chakra couronne, ces petites pyramides limpides sont imaginées comme des fenêtres translucides de lumière et de légèreté, ouvertes vers le haut.",
    ja: "アポフィライトの名は、加熱すると表面が薄い層となって剥がれることから、『剥がれ落ちる』を意味するギリシャ語に由来する。最も澄んで輝く結晶は、インド・デカン高原の古い溶岩の空洞の中で沸石とともに生まれ、ガラスのように内へ差し込む光を放つ。クラウンチャクラと結びつくこの澄んだ小さな錐は、上方へ開く光と軽やかさの半透明の窓のように想像される。",
    pt: "A apofilita recebe o nome de uma palavra grega que significa 'descamar,' pois sua superfície se desprende em camadas finas quando aquecida. Seus cristais mais claros e brilhantes se formam junto às zeólitas nas antigas cavidades de lava do planalto do Decão, na Índia, e brilham com uma luz vítrea que parece interior. Associada ao chacra da coroa, essas pequenas pirâmides límpidas são imaginadas como janelas translúcidas de luz e leveza, abertas para cima."
  },
  "s208": {
    tr: "Hemimorfit, adını Yunanca 'yarım' (hemi) ve 'biçim' (morphe) sözcüklerinden alır; çünkü kristalin iki ucu birbirinden farklı biçimdedir; bu asimetri taşı tanımlayan ender özelliklerden biridir. Eskiden çinko cevheriyle karıştırılan bu taş, en güzel mavi-yeşil üzüm salkımı kümeleriyle çinko yataklarında bulunur. Boğaz çakrasıyla bağdaştırılan deniz mavisi tonları, açık ve şefkatli iletişimin, duyguların dengeli ifadesinin sakin bir simgesi sayılır.",
    en: "Hemimorphite takes its name from the Greek hemi ('half') and morphe ('form'), because the two ends of its crystals differ in shape—an asymmetry that is one of the rare features defining the stone. Once confused with zinc ore, it is found in zinc deposits as its loveliest blue-green, grape-like clusters. Associated with the throat chakra, its sea-blue tones are taken as a calm emblem of open, compassionate communication and the balanced expression of feeling.",
    de: "Der Hemimorphit trägt seinen Namen vom griechischen hemi ('halb') und morphe ('Form'), denn die beiden Enden seiner Kristalle sind verschieden geformt—eine Asymmetrie, die zu den seltenen Merkmalen dieses Steins gehört. Einst mit Zinkerz verwechselt, findet er sich in Zinklagerstätten als seine schönsten blaugrünen, traubenartigen Aggregate. Mit dem Halschakra verbunden, gelten seine meerblauen Töne als ruhiges Sinnbild offener, mitfühlender Kommunikation und des ausgewogenen Ausdrucks von Gefühlen.",
    es: "La hemimorfita debe su nombre al griego hemi ('mitad') y morphe ('forma'), porque los dos extremos de sus cristales difieren en forma—una asimetría que es uno de los rasgos poco comunes que la definen. Confundida antaño con el mineral de cinc, se encuentra en yacimientos de cinc en sus más bellos racimos azul verdosos, parecidos a uvas. Asociada al chakra de la garganta, sus tonos azul mar se toman como emblema sereno de la comunicación abierta y compasiva y de la expresión equilibrada de los sentimientos.",
    fr: "L'hémimorphite tire son nom du grec hemi ('moitié') et morphe ('forme'), car les deux extrémités de ses cristaux diffèrent par leur forme—une asymétrie qui compte parmi les traits rares définissant cette pierre. Jadis confondue avec le minerai de zinc, on la trouve dans les gisements de zinc sous ses plus beaux amas bleu-vert, semblables à des grappes. Liée au chakra de la gorge, ses tons bleu mer passent pour un emblème paisible de communication ouverte et compatissante et de l'expression équilibrée des sentiments.",
    ja: "ヘミモルファイトの名は、結晶の両端の形が異なることから、ギリシャ語の hemi（半分）と morphe（形）に由来する。この非対称さは、この石を特徴づける数少ない性質の一つである。かつて亜鉛鉱と取り違えられたこの石は、亜鉛の鉱床の中で、ぶどうの房のような最も美しい青緑色の塊として見つかる。スロートチャクラと結びつくその海の青の色合いは、開かれた思いやりのある対話と、感情の均衡のとれた表現の静かな象徴とされる。",
    pt: "A hemimorfita recebe seu nome do grego hemi ('metade') e morphe ('forma'), porque as duas extremidades de seus cristais diferem na forma—uma assimetria que é um dos traços raros que a definem. Outrora confundida com o minério de zinco, é encontrada em depósitos de zinco em seus mais belos aglomerados azul-esverdeados, semelhantes a cachos de uva. Associada ao chacra da garganta, seus tons de azul-marinho são vistos como emblema sereno da comunicação aberta e compassiva e da expressão equilibrada dos sentimentos."
  },
  "s209": {
    tr: "Variskit, 1837'de ilk tanımlandığı Almanya'daki tarihî Voigtland (Latince adıyla Variscia) bölgesinden adını alır. Soluk yeşilden deniz köpüğü tonlarına uzanan bu taş, görünüşüyle sık sık turkuvazla karıştırılır; ABD'nin Utah eyaletindeki yataklarda yerli halklar tarafından süs ve takı olarak işlenmiştir. Toprak elementiyle ve kalp çakrasıyla bağdaştırılan dingin yeşili, umudun ve duygusal şifanın sakin, yere basan bir hatırlatıcısı sayılır.",
    en: "Variscite is named for the historic region of Voigtland in Germany—Variscia in Latin—where it was first described in 1837. Ranging from pale green to sea-foam tones, the stone is often mistaken for turquoise by its look; in deposits in Utah, in the United States, it was worked by Native peoples for ornament and jewelry. Associated with the earth element and the heart chakra, its quiet green is taken as a calm, grounding reminder of hope and emotional healing.",
    de: "Der Variscit ist nach der historischen Region Voigtland in Deutschland benannt—lateinisch Variscia—, wo er 1837 erstmals beschrieben wurde. Von blassgrünen bis zu meerschaumfarbenen Tönen reichend, wird der Stein dem Aussehen nach oft mit Türkis verwechselt; in Lagerstätten in Utah, USA, wurde er von indigenen Völkern zu Schmuck verarbeitet. Mit dem Erdelement und dem Herzchakra verbunden, gilt sein stilles Grün als ruhige, erdende Erinnerung an Hoffnung und seelische Heilung.",
    es: "La variscita debe su nombre a la histórica región de Voigtland, en Alemania—Variscia en latín—, donde se describió por primera vez en 1837. Con tonos que van del verde pálido al espuma de mar, la piedra suele confundirse con la turquesa por su aspecto; en yacimientos de Utah, en Estados Unidos, fue labrada por los pueblos nativos como ornamento y joya. Asociada al elemento tierra y al chakra del corazón, su verde sereno se toma como recordatorio calmo y enraizado de la esperanza y la sanación emocional.",
    fr: "La variscite tire son nom de la région historique du Voigtland, en Allemagne—Variscia en latin—, où elle fut décrite pour la première fois en 1837. Allant du vert pâle aux teintes d'écume de mer, la pierre est souvent confondue avec la turquoise par son aspect ; dans des gisements de l'Utah, aux États-Unis, elle fut travaillée par les peuples autochtones comme ornement et bijou. Liée à l'élément terre et au chakra du cœur, son vert paisible passe pour un rappel calme et enraciné de l'espoir et de la guérison émotionnelle.",
    ja: "バリサイトの名は、1837年に初めて記載されたドイツの歴史的地域フォークトラント（ラテン語でヴァリスキア）に由来する。淡い緑から海の泡のような色合いまで幅があるこの石は、その見た目からしばしばターコイズと取り違えられる。アメリカ・ユタ州の鉱床では、先住民によって装飾や宝飾として加工された。地の元素とハートチャクラに結びつくその静かな緑は、希望と心の癒やしを穏やかに、地に足のついた形で思い出させるものとされる。",
    pt: "A variscita recebe o nome da histórica região de Voigtland, na Alemanha—Variscia em latim—, onde foi descrita pela primeira vez em 1837. Variando do verde-pálido a tons de espuma do mar, a pedra costuma ser confundida com a turquesa pela aparência; em depósitos de Utah, nos Estados Unidos, foi trabalhada por povos nativos como ornamento e joia. Associada ao elemento terra e ao chacra do coração, seu verde sereno é visto como um lembrete calmo e enraizado de esperança e cura emocional."
  },
  "s210": {
    tr: "Petalit, adını Yunanca 'yaprak' (petalon) sözcüğünden alır; çünkü kristali kâğıt inceliğinde yapraklar hâlinde ayrılabilir. 1817'de İsveç'te incelenen bu mineral, bilim tarihinde ayrı bir yere sahiptir; lityum elementi ilk kez petalitin içinde keşfedilmiş ve adı 'taş' anlamına gelen Yunanca 'lithos'tan verilmiştir. Taç çakrasıyla bağdaştırılan berrak, soluk renkli kristali, zihnin gürültüden ayrışıp dinginliğe kavuştuğu sessiz bir alanın simgesi sayılır.",
    en: "Petalite takes its name from the Greek petalon, 'leaf,' because its crystal can split into paper-thin sheets. Studied in Sweden in 1817, this mineral holds a special place in the history of science: the element lithium was first discovered within petalite, and named from the Greek lithos, 'stone.' Associated with the crown chakra, its clear, pale crystal is taken as an emblem of a quiet space where the mind separates from noise and settles into stillness.",
    de: "Der Petalit trägt seinen Namen vom griechischen petalon, 'Blatt,' weil sein Kristall sich in papierdünne Blättchen spalten lässt. 1817 in Schweden untersucht, hat dieses Mineral einen besonderen Platz in der Wissenschaftsgeschichte: Das Element Lithium wurde erstmals im Petalit entdeckt und nach dem griechischen lithos, 'Stein,' benannt. Mit dem Kronenchakra verbunden, gilt sein klarer, blasser Kristall als Sinnbild eines stillen Raums, in dem sich der Geist vom Lärm löst und zur Ruhe findet.",
    es: "La petalita debe su nombre al griego petalon, 'hoja,' porque su cristal puede separarse en láminas finas como el papel. Estudiada en Suecia en 1817, este mineral ocupa un lugar especial en la historia de la ciencia: el elemento litio se descubrió por primera vez dentro de la petalita y se nombró a partir del griego lithos, 'piedra.' Asociada al chakra de la corona, su cristal claro y pálido se toma como emblema de un espacio sereno donde la mente se separa del ruido y se asienta en la quietud.",
    fr: "La pétalite tire son nom du grec petalon, 'feuille,' car son cristal peut se cliver en feuillets minces comme du papier. Étudié en Suède en 1817, ce minéral occupe une place particulière dans l'histoire des sciences : l'élément lithium fut d'abord découvert dans la pétalite et nommé d'après le grec lithos, 'pierre.' Liée au chakra couronne, son cristal clair et pâle passe pour l'emblème d'un espace paisible où l'esprit se détache du bruit et se pose dans le calme.",
    ja: "ペタライトの名は、結晶が紙のように薄い葉状に割れることから、ギリシャ語の petalon（葉）に由来する。1817年にスウェーデンで研究されたこの鉱物は、科学史において特別な位置を占める。元素リチウムは初めてペタライトの中から発見され、ギリシャ語の lithos（石）にちなんで名づけられた。クラウンチャクラと結びつくその澄んだ淡い色の結晶は、心が騒がしさから離れ、静けさに落ち着く静かな空間の象徴とされる。",
    pt: "A petalita recebe seu nome do grego petalon, 'folha,' porque seu cristal pode se dividir em lâminas finas como papel. Estudado na Suécia em 1817, esse mineral ocupa um lugar especial na história da ciência: o elemento lítio foi descoberto pela primeira vez dentro da petalita e nomeado a partir do grego lithos, 'pedra.' Associada ao chacra da coroa, seu cristal claro e pálido é visto como emblema de um espaço sereno onde a mente se separa do ruído e se assenta na quietude."
  },
  "s211": {
    tr: "Fenakit, adını Yunanca 'aldatıcı' anlamına gelen 'phenakos' sözcüğünden alır; çünkü berrak kristalleri sıkça kuvarsla karıştırılır, sanki kendini başka bir taş gibi gösterir. 1833'te Rusya'nın Ural Dağları'nda tanımlanan bu nadir berilyum minerali, gerçekte kuvarstan çok daha sert ve parlaktır. Taç çakrasıyla bağdaştırılan saydam, ışık geçiren kristali, görünenin ardındaki inceliği aramanın, yüksek bilince ve berraklığa yönelmenin sembolü olarak yorumlanır.",
    en: "Phenakite takes its name from the Greek phenakos, 'deceiver,' because its clear crystals are often mistaken for quartz, as if disguising themselves as another stone. Described in 1833 in Russia's Ural Mountains, this rare beryllium mineral is in fact far harder and brighter than quartz. Associated with the crown chakra, its transparent, light-bearing crystal is read as a symbol of seeking the subtle behind the obvious—of turning toward higher awareness and clarity.",
    de: "Der Phenakit trägt seinen Namen vom griechischen phenakos, 'Betrüger,' weil seine klaren Kristalle oft mit Quarz verwechselt werden, als verkleideten sie sich als ein anderer Stein. 1833 im russischen Ural beschrieben, ist dieses seltene Berylliummineral in Wahrheit weit härter und glänzender als Quarz. Mit dem Kronenchakra verbunden, deutet man seinen durchsichtigen, lichttragenden Kristall als Sinnbild der Suche nach dem Feinen hinter dem Offensichtlichen—der Hinwendung zu höherem Bewusstsein und Klarheit.",
    es: "La fenaquita debe su nombre al griego phenakos, 'engañador,' porque sus cristales transparentes suelen confundirse con el cuarzo, como si se disfrazaran de otra piedra. Descrita en 1833 en los montes Urales de Rusia, este raro mineral de berilio es en realidad mucho más duro y brillante que el cuarzo. Asociada al chakra de la corona, su cristal transparente y portador de luz se interpreta como símbolo de buscar lo sutil tras lo evidente—de volverse hacia una conciencia más elevada y la claridad.",
    fr: "La phénacite tire son nom du grec phenakos, 'trompeur,' car ses cristaux limpides sont souvent confondus avec le quartz, comme s'ils se déguisaient en une autre pierre. Décrit en 1833 dans l'Oural russe, ce rare minéral de béryllium est en réalité bien plus dur et brillant que le quartz. Lié au chakra couronne, son cristal transparent et porteur de lumière se lit comme un symbole de la quête du subtil derrière l'évident—du tournant vers une conscience plus haute et la clarté.",
    ja: "フェナカイトの名は、その透明な結晶がしばしば水晶と取り違えられ、まるで別の石に化けるかのようであることから、ギリシャ語の phenakos（欺く者）に由来する。1833年にロシアのウラル山脈で記載されたこの稀少なベリリウム鉱物は、実際には水晶よりはるかに硬く輝く。クラウンチャクラと結びつくその透明で光を宿す結晶は、明白なものの奥にある繊細さを求めること、すなわち高い意識と明晰さへ向かうことの象徴とされる。",
    pt: "A fenacita recebe seu nome do grego phenakos, 'enganador,' porque seus cristais transparentes são muitas vezes confundidos com o quartzo, como se se disfarçassem de outra pedra. Descrito em 1833 nos montes Urais, na Rússia, esse raro mineral de berílio é na verdade bem mais duro e brilhante que o quartzo. Associada ao chacra da coroa, seu cristal transparente e portador de luz é lido como símbolo de buscar o sutil por trás do evidente—de voltar-se para uma consciência mais elevada e a clareza."
  },
  "s212": {
    tr: "Dumortierit, adını ilk örneklerini bilime sunan Fransız paleontolog Eugène Dumortier'in anısına alır ve 1881'de Fransa'da tanımlanmıştır. Derin lacivertten mor mavisine uzanan bu taş, kuvarsın içinde ince lifler hâlinde de bulunur ve sabırlı bir el işçiliğiyle boncuk hâline getirilir. Üçüncü göz çakrasıyla bağdaştırılan dingin mavisi, dağılmış bir zihnin yavaşça toplanıp odaklanmasının, sabır ve disiplinin sessiz bir simgesi sayılır.",
    en: "Dumortierite is named in memory of the French paleontologist Eugène Dumortier, who presented its first specimens to science, and was described in France in 1881. Ranging from deep navy to violet-blue, the stone is also found as fine fibers within quartz and shaped into beads by patient handwork. Associated with the third-eye chakra, its tranquil blue is taken as a quiet emblem of a scattered mind slowly gathering into focus—of patience and discipline.",
    de: "Der Dumortierit ist zum Andenken an den französischen Paläontologen Eugène Dumortier benannt, der seine ersten Stücke der Wissenschaft vorlegte, und wurde 1881 in Frankreich beschrieben. Von tiefem Marineblau bis zu Violettblau reichend, findet sich der Stein auch als feine Fasern im Quarz und wird in geduldiger Handarbeit zu Perlen geformt. Mit dem Stirnchakra verbunden, gilt sein ruhiges Blau als stilles Sinnbild eines zerstreuten Geistes, der sich langsam zur Konzentration sammelt—für Geduld und Disziplin.",
    es: "La dumortierita lleva su nombre en memoria del paleontólogo francés Eugène Dumortier, que presentó sus primeros ejemplares a la ciencia, y fue descrita en Francia en 1881. Con tonos que van del azul marino profundo al azul violáceo, la piedra también se encuentra como finas fibras dentro del cuarzo y se trabaja en cuentas con paciente labor manual. Asociada al chakra del tercer ojo, su azul tranquilo se toma como emblema sereno de una mente dispersa que poco a poco se recoge en el enfoque—de paciencia y disciplina.",
    fr: "La dumortiérite porte son nom en mémoire du paléontologue français Eugène Dumortier, qui présenta ses premiers spécimens à la science, et fut décrite en France en 1881. Allant du bleu marine profond au bleu violacé, la pierre se trouve aussi sous forme de fines fibres dans le quartz et se façonne en perles par un travail patient. Liée au chakra du troisième œil, son bleu tranquille passe pour un emblème paisible d'un esprit dispersé qui peu à peu se rassemble dans la concentration—de patience et de discipline.",
    ja: "デュモルチェライトの名は、最初の標本を学界に提示したフランスの古生物学者ウジェーヌ・デュモルティエを記念したもので、1881年にフランスで記載された。深い紺色から菫色を帯びた青まで幅のあるこの石は、水晶の中に細い繊維としても見られ、根気のいる手仕事でビーズに整えられる。サードアイチャクラと結びつくその穏やかな青は、散り散りになった心が少しずつ集まって焦点を結ぶさま、すなわち忍耐と規律の静かな象徴とされる。",
    pt: "A dumortierita leva esse nome em memória do paleontólogo francês Eugène Dumortier, que apresentou seus primeiros exemplares à ciência, e foi descrita na França em 1881. Variando do azul-marinho profundo ao azul-violáceo, a pedra também é encontrada como finas fibras dentro do quartzo e moldada em contas por um trabalho manual paciente. Associada ao chacra do terceiro olho, seu azul tranquilo é visto como emblema sereno de uma mente dispersa que aos poucos se recolhe no foco—de paciência e disciplina."
  }
};
