// Sakin / Niyet: Yardım kılavuzu (glossary) sözlüğü: 7 dil
// Yapı: kategori → öğeler → { term, desc, examples? }
// Kategori başlıkları t("guide_cat_*") ile alınır (i18n.js / i18n-extras.js içinde).
// Sakin'in sesi: sade, sıcak, küçük harf tercihli. Şiirsel ama bilimsel ton.

// Tek bir öğeyi yerleştirme: { term, desc, examples? }
// 7 dilin hepsi için aynı yapı korunur. Eksik dilde fallback EN → TR.

import { STARSEED_BY_LANG } from "./glossary-starseed";

const TR = [
  { cat: "guide_cat_numerology", items: [
    { term: "Yaşam Yolu Sayısı (Life Path Number)", desc: "Doğum tarihindeki tüm rakamların tek haneli bir sayıya (veya 11, 22, 33 usta sayılarına) indirgenmesiyle bulunan kişisel sayıdır. Hayat amacını, doğal yeteneklerini ve yaşam yolculuğunun temel enerjisini temsil eder.", examples: [
      { num: "1", meaning: "Lider, bağımsız, öncü. Kendi yolunu çizen, cesur ve kararlı bir enerji. Yenilik ve başlangıçların sayısı." },
      { num: "2", meaning: "Diplomat, uyumlu, hassas. İşbirliği ve denge arayan, sezgisel ve nazik bir enerji. Ortaklık ve ilişki sayısı." },
      { num: "3", meaning: "Yaratıcı, ifadeci, neşeli. Sanat, iletişim ve sosyal bağlantı enerjisi. Kendini ifade etme ve ilham sayısı." },
      { num: "4", meaning: "İnşa edici, disiplinli, güvenilir. Düzen, istikrar ve sağlam temeller enerjisi. Çalışkanlık ve dayanıklılık sayısı." },
      { num: "5", meaning: "Özgür ruh, maceracı, değişken. Özgürlük, seyahat ve deneyim enerjisi. Değişim ve esneklik sayısı." },
      { num: "6", meaning: "Bakıcı, sorumlu, uyumlu. Aile, ev ve toplum enerjisi. Sevgi, şifa ve sorumluluk sayısı." },
      { num: "7", meaning: "Araştırmacı, mistik, içe dönük. Maneviyat, analiz ve derin düşünce enerjisi. Bilgelik ve keşif sayısı." },
      { num: "8", meaning: "Güç sahibi, hırslı, başarılı. Maddi bolluk, otorite ve başarı enerjisi. Denge ve karma sayısı." },
      { num: "9", meaning: "İnsancıl, bilge, tamamlayıcı. Evrensel sevgi, şefkat ve bırakma enerjisi. Hizmet ve dönüşüm sayısı." },
      { num: "11", meaning: "Usta Sayı: Sezgisel aydınlatıcı. Yüksek farkındalık, ilham ve spiritüel öğretmenlik enerjisi." },
      { num: "22", meaning: "Usta Sayı: Usta inşacı. Büyük vizyonları gerçeğe dönüştürme gücü. Pratik idealizm enerjisi." },
      { num: "33", meaning: "Usta Sayı: Usta öğretmen. Koşulsuz sevgi, şifa ve evrensel hizmet enerjisi." },
    ]},
    { term: "Kişisel Yıl Sayısı", desc: "Doğum gününüz ve ayınız ile içinde bulunduğunuz yılın rakamlarının toplanmasıyla hesaplanır. 1-9 arasında döngüsel bir enerji haritası sunar. Her yıl farklı bir tema ve enerji getirir.", examples: [
      { num: "1. Yıl", meaning: "Yeni başlangıçlar, tohum ekme zamanı." },
      { num: "2. Yıl", meaning: "Sabır, işbirliği ve bekleme zamanı." },
      { num: "3. Yıl", meaning: "Yaratıcılık, ifade ve sosyallik zamanı." },
      { num: "4. Yıl", meaning: "Temel atma, düzen kurma zamanı." },
      { num: "5. Yıl", meaning: "Değişim, özgürlük ve macera zamanı." },
      { num: "6. Yıl", meaning: "Sorumluluk, aile ve şifa zamanı." },
      { num: "7. Yıl", meaning: "İçe dönüş, araştırma ve maneviyat zamanı." },
      { num: "8. Yıl", meaning: "Güç, başarı ve maddi bolluk zamanı." },
      { num: "9. Yıl", meaning: "Tamamlama, bırakma ve dönüşüm zamanı." },
    ]},
    { term: "İndirgeme (Reduce)", desc: "Numerolojide çok haneli sayıları tek haneye düşürme işlemidir. Tüm rakamlar toplanır, sonuç 9'dan büyükse tekrar toplanır. 11, 22 ve 33 \"Usta Sayılar\" olarak indirgenmez, özel anlamları korunur." },
  ]},
  { cat: "guide_cat_astrology", items: [
    { term: "Burç (Güneş Burcu)", desc: "Doğduğunuz tarihte Güneş'in bulunduğu burçtur. Temel kişiliğinizi, egonuzu ve yaşam enerjinizi temsil eder. 12 burç vardır: Koç, Boğa, İkizler, Yengeç, Aslan, Başak, Terazi, Akrep, Yay, Oğlak, Kova, Balık." },
    { term: "Yükselen Burç (Ascendant)", desc: "Doğum anında ufuk çizgisinde yükselen burçtur. Dış dünyanın sizi nasıl gördüğünü, fiziksel görünümünüzü ve ilk izleniminizi belirler. Hesaplamak için doğum saati gereklidir. Yaklaşık olarak her 2 saatte bir burç değişir." },
    { term: "12. Ev & Yönetici Gezegen", desc: "Astrolojide 12. ev bilinçaltını, gizli güçleri, spiritüel potansiyeli ve içsel dünyayı temsil eder. Her evin bir yönetici gezegeni vardır ve bu gezegen o evin temalarını nasıl deneyimlediğinizi belirler." },
    { term: "Draconik Harita", desc: "Natal harita kim olduğunu söyler, Draconik harita ruhunun bu bedene girmeden önce ne olduğunu söyler. Kuzey Ay Düğümü 0° Koç'a sabitlenerek hesaplanır ve tüm gezegenlerin ruhsal eksen sıfırlandığında nerede durduğunu gösterir. Pamela Crane ve Ronald Davison tarafından 1970'lerde sistemleştirilmiştir. Draconik Güneş ruhun gerçek kimliği, natal Güneş bu hayatta giydiği maskedir; ikisi farklı burçtaysa kişi sürekli rol yapıyor gibi hissedebilir." },
    { term: "Gezegen Güçleri", desc: "Her gezegen farklı bir yaşam alanını ve enerjiyi yönetir: Güneş (benlik), Ay (duygular), Merkür (iletişim), Venüs (sevgi), Mars (aksiyon), Jüpiter (genişleme), Satürn (disiplin), Uranüs (özgünlük), Neptün (hayal gücü), Pluto (dönüşüm)." },
    { term: "Kuzey Düğüm & Güney Düğüm", desc: "Ay'ın yörüngesinin ekliptiği kestiği iki noktadır; gökte fiziksel bir cisim değil, matematiksel bir kesişimdir. Güney Düğüm geçmişten getirdiğin, rahat ama seni büyütmeyen kalıpları; Kuzey Düğüm ise bu yaşamda yönelmen gereken, başta zorlayıcı gelen yönü temsil eder." },
    { term: "Retro (Retrograde)", desc: "Bir gezegenin Dünya'dan bakıldığında geriye gidiyormuş gibi görünmesidir. Gerçekte geri gitmez; iki gezegenin hız farkından doğan görsel bir yanılsamadır. Astrolojide bu dönemler yeniden gözden geçirme, tamamlama ve içe dönme zamanı olarak okunur." },
    { term: "Geçiş (Transit)", desc: "Gökyüzündeki gezegenlerin o anki konumlarının, doğum haritandaki noktalarla kurduğu açısal ilişkidir. Sakin'in gökyüzü raporundaki geçiş notu KİŞİSEL değil KOLEKTİFTİR: o gün herkes için aynı gökyüzünü anlatır." },
    { term: "Ay Evresi", desc: "Ay'ın Güneş'e göre konumundan doğan aydınlanma döngüsüdür; yaklaşık 29,5 günde tamamlanır. Yeni Ay niyet tohumlamaya, Dolunay ise görünür kılmaya ve bırakmaya bağlanır." },
  ]},
  { cat: "guide_cat_chakra", items: [
    { term: "Çakra Nedir?", desc: "Sanskrit dilinde \"tekerlek\" anlamına gelir. Vücuttaki enerji merkezleridir. 7 ana çakra omurga boyunca sıralanır. Her biri farklı fiziksel, duygusal ve spiritüel alanları yönetir." },
    { term: "1. Kök Çakra (Muladhara)", desc: "Konum: Omurga tabanı. Renk: Kırmızı. Element: Toprak. Temsil: Güvenlik, hayatta kalma, temel ihtiyaçlar, topraklanma. Dengede: Güvende hissedersin. Dengesiz: Korku, kaygı, maddi endişeler." },
    { term: "2. Sakral Çakra (Svadhisthana)", desc: "Konum: Göbek altı. Renk: Turuncu. Element: Su. Temsil: Yaratıcılık, duygular, cinsellik, zevk alma. Dengede: Akışta hissedersin. Dengesiz: Duygusal istikrarsızlık, yaratıcılık tıkanması." },
    { term: "3. Güneş Pleksusu Çakra (Manipura)", desc: "Konum: Mide bölgesi. Renk: Sarı. Element: Ateş. Temsil: Özgüven, irade gücü, kişisel güç. Dengede: Güçlü ve kararlı hissedersin. Dengesiz: Güçsüzlük, kontrol sorunları." },
    { term: "4. Kalp Çakra (Anahata)", desc: "Konum: Göğüs merkezi. Renk: Yeşil. Element: Hava. Temsil: Sevgi, şefkat, bağışlama, ilişkiler. Dengede: Sevgiyle açık hissedersin. Dengesiz: Kıskançlık, yalnızlık, bağlanma korkusu." },
    { term: "5. Boğaz Çakra (Vishuddha)", desc: "Konum: Boğaz. Renk: Mavi. Element: Ses. Temsil: İletişim, kendini ifade, hakikat. Dengede: Rahatça konuşursun. Dengesiz: İfade zorluğu, yalan söyleme eğilimi." },
    { term: "6. Üçüncü Göz Çakra (Ajna)", desc: "Konum: İki kaş arası. Renk: Mor/İndigo. Element: Işık. Temsil: Sezgi, içgörü, hayal gücü, bilgelik. Dengede: Sezgilerin güçlüdür. Dengesiz: Karar verememe, sezgisel tıkanıklık." },
    { term: "7. Taç Çakra (Sahasrara)", desc: "Konum: Başın tepesi. Renk: Mor/Beyaz. Element: Evren. Temsil: Evrensel bağlantı, aydınlanma, spiritüel farkındalık. Dengede: Bütünle bağlı hissedersin. Dengesiz: Kopukluk, anlamsızlık hissi." },
    { term: "22 Çakra Sistemi", desc: "7 ana çakranın ötesinde 15 ek enerji merkezi daha bulunur. Bunlar arasında Yeryüzü Yıldızı, Ruh, Thymus, Orion, Soul Star gibi daha ileri düzey enerji merkezleri yer alır. Reiki terapisinde bu genişletilmiş sistem kullanılır." },
  ]},
  { cat: "guide_cat_biorhythm", items: [
    { term: "Biyoritim Nedir?", desc: "Doğum tarihinden itibaren başlayan üç döngüsel biyolojik ritimdir. Her döngü sinüs dalgası şeklinde pozitif ve negatif arasında salınır. Değerler -100 ile +100 arasında değişir." },
    { term: "Fiziksel Biyoritim (23 gün)", desc: "Fiziksel enerji, güç, dayanıklılık ve koordinasyonu yansıtır. Pozitif dönemde enerjin yüksek, negatif dönemde dinlenme ihtiyacın artar. Kritik günlerde (0 geçişi) dikkatli ol." },
    { term: "Duygusal Biyoritim (28 gün)", desc: "Duygusal denge, ruh hali, yaratıcılık ve sezgiyi yansıtır. Pozitif dönemde iyimser ve empatiksin, negatif dönemde hassas ve içe dönüksün." },
    { term: "Zihinsel Biyoritim (33 gün)", desc: "Zihinsel keskinlik, konsantrasyon, hafıza ve analitik düşünme kapasitesini yansıtır. Pozitif dönemde zihnen aktif ve öğrenmeye açıksın, negatif dönemde odaklanma zorlaşır." },
  ]},
  { cat: "guide_cat_reiki", items: [
    { term: "Reiki Nedir?", desc: "Japonca \"evrensel yaşam enerjisi\" anlamına gelen bir farkındalık pratiğidir. Ellerin enerji merkezlerine (çakralara) yerleştirilmesiyle kişisel farkındalık ve rahatlama deneyimi sunar. Tıbbi bir tedavi veya teşhis yöntemi değildir; profesyonel sağlık hizmetinin yerine geçmez." },
    { term: "Çakra Terapisi", desc: "Sakin'deki 60 saniyelik seanslar, seçtiğiniz çakraya odaklanmanızı sağlar. Elinizi ilgili bölgeye koyarak, gözlerinizi kapatarak ve nefes alarak o enerji merkeziyle bağ kurarsınız." },
    { term: "Şifa Arayışı", desc: "Yapay zeka destekli bir analiz aracıdır. Fiziksel veya duygusal bir durumu girdiğinizde, Reiki bilgeliği, Louise Hay'in zihinsel-duygusal neden haritası ve çakra teorisini birleştirerek kişiselleştirilmiş bir yorum sunar." },
    { term: "Louise Hay Yöntemi", desc: "Fiziksel rahatsızlıkların altında yatan zihinsel ve duygusal nedenleri inceleyen bir yaklaşımdır. Örneğin baş ağrısı \"kendini geçersiz sayma\", sırt ağrısı \"duygusal destek eksikliği\" ile ilişkilendirilir." },
    { term: "İçsel Ayna", desc: "Bedensel şikayetlerinizi veya duygusal durumunuzu yazarak içsel nedenlerini keşfetmenizi sağlayan yapay zeka analiz aracıdır." },
  ]},
  { cat: "guide_cat_app", items: [
    { term: "Sabah Niyeti", desc: "Her güne bilinçli bir niyetle başlama pratiğidir. Kısa bir cümle veya kelime ile o günün odak noktasını belirlersiniz. Niyet, bilinçaltına yön verir ve günün akışını şekillendirir." },
    { term: "3 Kelime Seçimi", desc: "Sabah rutininde sunulan 12 güç kelimesinden (huzur, akış, cesaret, sabır, berraklık, sevgi, güç, denge, özgürlük, neşe, şükür, güven) 3 tanesini seçersiniz. Bu kelimeler günün enerji yönelimini belirler." },
    { term: "Nefes Egzersizi (4-1.5-3.5)", desc: "Al (4 sn) → Tut (1.5 sn) → Ver (3.5 sn) → Dinlen ritmiyle yapılan nefes pratiğidir. Parasempatik sinir sistemini aktive ederek stresi azaltır ve odaklanmayı artırır." },
    { term: "Gün İçi Hatırlatıcılar", desc: "Gün boyunca farkındalığınızı korumanız için tasarlanmış 10 mikro pratiktir: aynaya bakmak, su içmek, nefes farkındalığı, beden egzersizi, güneşi hissetmek, ağaca sarılmak, toprağa dokunmak, gökyüzüne bakmak, çakra anı ve sosyal medya molası." },
    { term: "Akşam Kapanışı", desc: "Günü bilinçli bir şekilde kapatma ritüelidir. \"Bugün ne öğrendin?\" ve \"Şükür?\" sorularıyla günün farkındalık özetini çıkarırsınız." },
    { term: "Haftalık İç Harita", desc: "Haftanın istatistiklerini gösteren özet ekrandır: en aktif çakra, toplam nefes sayısı, niyet kelimeleri ve bilinçli an sayısı. Yapay zeka raporu bu verilerden haftalık bir içgörü sentezi oluşturur." },
    { term: "Doğum Profili", desc: "Doğum tarihiniz ve saatinizden hesaplanan kişisel enerji haritanızdır: burç, yaşam yolu sayısı, kişisel yıl sayısı, yükselen burç, 12. ev analizi ve haftalık biyoritim grafiği." },
    { term: "Solfeggio Frekansları", desc: "Sakin'de kullanılan altı temel ton (396, 417, 528, 639, 741, 852 Hz) ve taç çakra için 963 Hz. Her frekans bir çakraya eşlenir. Bunlar bir tedavi yöntemi değil, dikkati bedene toplamaya yardımcı olan işitsel bir demirdir." },
    { term: "Bağlantı & Gün Serisi", desc: "Günün 7 adımını (sabah, gün görevleri, nefes, ses, çakra, akşam, ayna) tamamladığında bağlantı aktifleşir ve çakra sütunu ışık tüneline dönüşür. Art arda tamamlanan günler seriyi büyütür: 7 günde 2. seviye (x2), 21 günde 3. seviye (x4)." },
    { term: "Gökyüzü Raporu", desc: "Ay evresi, güneş patlamaları, jeomanyetik hareketlilik (Kp indeksi), güneş rüzgârı ve göktaşı yağmurlarını birleştiren günlük kolektif özet. Veriler NOAA'nın açık uzay hava durumu servisinden gelir; yorum herkes için aynıdır." },
    { term: "Galaktik Kimlik", desc: "Doğum bilgilerinden üretilen, paylaşılabilir kişisel kart. Burç, yükselen, yaşam yolu sayısı ve element dağılımını tek görselde toplar." },
    { term: "Element Dağılımı", desc: "Doğum haritandaki gezegenlerin ateş, toprak, hava ve su elementlerine dağılımıdır. Güneş ve Ay daha ağır tartılır. Baskın element doğal eğilimini, en zayıf element ise bilinçle beslemen gereken alanı gösterir." },
    { term: "Zihni Boşalt (Kaleidoskop)", desc: "Dört mod (sükûnet, berraklık, teslimiyet, genişlik) sunan tam ekran görsel-işitsel bir dinlenme alanı. Desenler ve tonlar o anda üretilir; kayıt değildir, her seferinde farklı akar." },
    { term: "Panik Butonu", desc: "Ani kaygı anlarında hızlı erişim için tasarlanmıştır. Doğrudan 4-7-8 nefes moduna götürür. Bu ritim nefes vermeyi uzatarak parasempatik sinir sistemini destekler. Tıbbi bir müdahale değildir; acil durumda 112'yi arayın." },
  ]},
];

const EN = [
  { cat: "guide_cat_numerology", items: [
    { term: "Life Path Number", desc: "Calculated by reducing all digits of your birth date to a single digit (or master numbers 11, 22, 33). It represents your life purpose, natural talents, and the core energy of your journey.", examples: [
      { num: "1", meaning: "Leader, independent, pioneer. Courageous and determined energy that charts its own course." },
      { num: "2", meaning: "Diplomat, harmonious, sensitive. Cooperative and intuitive energy seeking balance." },
      { num: "3", meaning: "Creative, expressive, joyful. Art, communication and social connection energy." },
      { num: "4", meaning: "Builder, disciplined, reliable. Order, stability and solid foundations energy." },
      { num: "5", meaning: "Free spirit, adventurous, changeable. Freedom, travel and experience energy." },
      { num: "6", meaning: "Caretaker, responsible, harmonious. Family, home and community energy." },
      { num: "7", meaning: "Researcher, mystic, introspective. Spirituality, analysis and deep thought energy." },
      { num: "8", meaning: "Powerful, ambitious, successful. Material abundance, authority and achievement energy." },
      { num: "9", meaning: "Humanitarian, wise, completing. Universal love, compassion and release energy." },
      { num: "11", meaning: "Master Number: Intuitive illuminator. High awareness and spiritual teaching energy." },
      { num: "22", meaning: "Master Number: Master builder. Power to turn grand visions into reality." },
      { num: "33", meaning: "Master Number: Master teacher. Unconditional love, healing and universal service." },
    ]},
    { term: "Personal Year Number", desc: "Calculated by adding your birth day and month with the current year's digits. Provides a cyclical energy map from 1-9. Each year brings a different theme and energy." },
    { term: "Reduction", desc: "The process of reducing multi-digit numbers to a single digit in numerology. All digits are added; if the result is greater than 9, they are added again. 11, 22, and 33 are \"Master Numbers\" and are not reduced." },
  ]},
  { cat: "guide_cat_astrology", items: [
    { term: "Zodiac Sign (Sun Sign)", desc: "The sign the Sun was in at your birth. Represents your core personality, ego, and life energy. There are 12 signs: Aries, Taurus, Gemini, Cancer, Leo, Virgo, Libra, Scorpio, Sagittarius, Capricorn, Aquarius, Pisces." },
    { term: "Ascendant (Rising Sign)", desc: "The sign rising on the horizon at your birth moment. Determines how the world sees you, your physical appearance and first impression. Birth time is required for calculation." },
    { term: "12th House & Ruling Planet", desc: "In astrology, the 12th house represents the subconscious, hidden powers, spiritual potential and inner world. Each house has a ruling planet that determines how you experience its themes." },
    { term: "Draconic Chart", desc: "Your natal chart tells you who you are; the Draconic chart tells you what your soul was before entering this body. Calculated by fixing the North Node at 0° Aries. Systematized by Pamela Crane and Ronald Davison in the 1970s. The Draconic Sun is the soul's true identity; the natal Sun is the mask worn in this life." },
    { term: "Planetary Powers", desc: "Each planet governs different life areas: Sun (self), Moon (emotions), Mercury (communication), Venus (love), Mars (action), Jupiter (expansion), Saturn (discipline), Uranus (originality), Neptune (imagination), Pluto (transformation)." },
    { term: "North Node & South Node", desc: "The two points where the Moon's orbit crosses the ecliptic: not physical bodies, but mathematical intersections. The South Node represents patterns you carry from the past: comfortable, but no longer growing you. The North Node points to the direction you are meant to grow toward in this life, which often feels unfamiliar at first." },
    { term: "Retrograde", desc: "When a planet appears to move backwards as seen from Earth. It never truly reverses; it is an optical effect created by the difference in orbital speeds. In astrology these periods are read as time to revisit, finish and turn inward." },
    { term: "Transit", desc: "The angular relationship between planets' current positions and the points in your birth chart. The transit note in Sakin's sky report is COLLECTIVE, not personal: it describes the same sky for everyone that day." },
    { term: "Moon Phase", desc: "The illumination cycle created by the Moon's position relative to the Sun, completing in about 29.5 days. The New Moon is associated with seeding intentions, the Full Moon with making things visible and letting go." },
  ]},
  { cat: "guide_cat_chakra", items: [
    { term: "What is a Chakra?", desc: "Means \"wheel\" in Sanskrit. Energy centers in the body. 7 main chakras align along the spine, each governing different physical, emotional and spiritual areas." },
    { term: "1. Root Chakra (Muladhara)", desc: "Location: Base of spine. Color: Red. Element: Earth. Represents: Safety, survival, basic needs, grounding." },
    { term: "2. Sacral Chakra (Svadhisthana)", desc: "Location: Below navel. Color: Orange. Element: Water. Represents: Creativity, emotions, sexuality, pleasure." },
    { term: "3. Solar Plexus Chakra (Manipura)", desc: "Location: Stomach area. Color: Yellow. Element: Fire. Represents: Confidence, willpower, personal power." },
    { term: "4. Heart Chakra (Anahata)", desc: "Location: Center of chest. Color: Green. Element: Air. Represents: Love, compassion, forgiveness, relationships." },
    { term: "5. Throat Chakra (Vishuddha)", desc: "Location: Throat. Color: Blue. Element: Sound. Represents: Communication, self-expression, truth." },
    { term: "6. Third Eye Chakra (Ajna)", desc: "Location: Between eyebrows. Color: Indigo. Element: Light. Represents: Intuition, insight, imagination, wisdom." },
    { term: "7. Crown Chakra (Sahasrara)", desc: "Location: Top of head. Color: Violet/White. Element: Universe. Represents: Universal connection, enlightenment." },
    { term: "22 Chakra System", desc: "Beyond the 7 main chakras, there are 15 additional energy centers including Earth Star, Soul, Thymus, Orion, Soul Star and more, used in extended Reiki therapy." },
  ]},
  { cat: "guide_cat_biorhythm", items: [
    { term: "What is Biorhythm?", desc: "Three cyclical biological rhythms starting from your birth date. Each oscillates between positive and negative as sine waves, with values ranging from -100 to +100." },
    { term: "Physical Biorhythm (23 days)", desc: "Reflects physical energy, strength, endurance and coordination. Positive periods = high energy, negative = rest needed." },
    { term: "Emotional Biorhythm (28 days)", desc: "Reflects emotional balance, mood, creativity and intuition. Positive = optimistic, negative = sensitive and introverted." },
    { term: "Mental Biorhythm (33 days)", desc: "Reflects mental sharpness, concentration, memory and analytical thinking. Positive = mentally active, negative = harder to focus." },
  ]},
  { cat: "guide_cat_reiki", items: [
    { term: "What is Reiki?", desc: "A Japanese energy healing method meaning \"universal life energy\". Activates the body's natural healing mechanism by placing hands on energy centers (chakras). Not medical treatment; a complementary wellness practice." },
    { term: "Chakra Therapy", desc: "60-second sessions in Sakin that help you focus on your chosen chakra by placing your hand on the area, closing your eyes and breathing." },
    { term: "Healing Search", desc: "An AI-powered analysis tool that combines Reiki wisdom, Louise Hay's mental-emotional cause mapping and chakra theory to provide personalized insights." },
    { term: "Louise Hay Method", desc: "An approach examining mental and emotional causes underlying physical ailments. For example, headaches linked to \"self-invalidation\", back pain to \"lack of emotional support\"." },
    { term: "Inner Mirror", desc: "AI analysis tool that lets you discover inner causes by writing about your physical complaints or emotional states." },
  ]},
  { cat: "guide_cat_app", items: [
    { term: "Morning Intention", desc: "The practice of starting each day with a conscious intention. You set the day's focus point with a short sentence or word." },
    { term: "3 Word Selection", desc: "Choose 3 power words from 12 options (peace, flow, courage, patience, clarity, love, strength, balance, freedom, joy, gratitude, trust) to set the day's energy direction." },
    { term: "Breath Exercise (4-1.5-3.5)", desc: "Inhale (4s) → Hold (1.5s) → Exhale (3.5s) → Rest rhythm. Activates the parasympathetic nervous system to reduce stress and improve focus." },
    { term: "Daily Reminders", desc: "10 micro practices throughout the day: mirror gazing, drinking water, breath awareness, body exercise, feeling the sun, hugging a tree, touching earth, looking at sky, chakra moment, social media break." },
    { term: "Evening Close", desc: "A ritual to consciously close the day. Extract your awareness summary with \"What did you learn today?\" and \"Gratitude?\" questions." },
    { term: "Weekly Inner Map", desc: "Summary screen showing the week's stats: most active chakra, total breaths, intention words and mindful moments. AI report creates a weekly insight synthesis." },
    { term: "Birth Profile", desc: "Your personal energy map calculated from your birth date and time: zodiac sign, life path number, personal year, ascendant, 12th house analysis and weekly biorhythm graph." },
    { term: "Solfeggio Frequencies", desc: "The six core tones used in Sakin (396, 417, 528, 639, 741, 852 Hz) plus 963 Hz for the crown chakra. Each frequency maps to a chakra. These are not a treatment. They are an auditory anchor that helps gather attention into the body." },
    { term: "Connection & Day Streak", desc: "When you complete the seven steps of the day (morning, day tasks, breath, sound, chakra, evening, mirror), the connection activates and the chakra column becomes a tunnel of light. Consecutive completed days grow your streak: level 2 at 7 days (x2), level 3 at 21 days (x4)." },
    { term: "Sky Report", desc: "A daily collective summary combining the moon phase, solar flares, geomagnetic activity (Kp index), solar wind and meteor showers. Data comes from NOAA's open space-weather service; the reading is the same for everyone." },
    { term: "Galactic Identity", desc: "A shareable personal card generated from your birth details. It gathers your sun sign, ascendant, life path number and element balance into a single image." },
    { term: "Element Balance", desc: "How the planets in your birth chart distribute across fire, earth, air and water. The Sun and Moon carry more weight. Your dominant element shows your natural leaning; the weakest one shows what you may need to nourish consciously." },
    { term: "Clear the Mind (Kaleidoscope)", desc: "A full-screen visual and sonic resting space with four modes (stillness, clarity, surrender, spaciousness). The patterns and tones are generated live rather than played back, so each session flows differently." },
    { term: "Panic Button", desc: "Designed for quick access in moments of sudden anxiety. It takes you straight to the 4-7-8 breath mode: a rhythm that lengthens the exhale and supports the parasympathetic nervous system. It is not a medical intervention; in an emergency call your local emergency number." },
  ]},
];

const DE = [
  { cat: "guide_cat_numerology", items: [
    { term: "Lebenszahl (Life Path Number)", desc: "Berechnet durch Reduktion aller Ziffern deines Geburtsdatums auf eine einzelne Zahl (oder Meisterzahlen 11, 22, 33). Sie repräsentiert deinen Lebenssinn, deine natürlichen Talente und die Kernenergie deiner Reise.", examples: [
      { num: "1", meaning: "Anführer, unabhängig, Pionier. Mutige und entschlossene Energie, die ihren eigenen Weg geht." },
      { num: "2", meaning: "Diplomat, harmonisch, sensibel. Kooperative und intuitive Energie, die Ausgleich sucht." },
      { num: "3", meaning: "Kreativ, ausdrucksstark, freudvoll. Energie für Kunst, Kommunikation und soziale Verbindung." },
      { num: "4", meaning: "Erbauer, diszipliniert, verlässlich. Energie für Ordnung, Stabilität und feste Fundamente." },
      { num: "5", meaning: "Freigeist, abenteuerlustig, wandelbar. Energie für Freiheit, Reisen und Erfahrung." },
      { num: "6", meaning: "Fürsorger, verantwortungsvoll, harmonisch. Energie für Familie, Heim und Gemeinschaft." },
      { num: "7", meaning: "Forscher, mystisch, introspektiv. Energie für Spiritualität, Analyse und tiefes Denken." },
      { num: "8", meaning: "Machtvoll, ehrgeizig, erfolgreich. Energie für materiellen Reichtum, Autorität und Erfolg." },
      { num: "9", meaning: "Humanitär, weise, vollendend. Energie der universellen Liebe, des Mitgefühls und des Loslassens." },
      { num: "11", meaning: "Meisterzahl: Intuitiver Erleuchter. Hohes Bewusstsein und spirituelle Lehrerenergie." },
      { num: "22", meaning: "Meisterzahl: Meisterbaumeister. Die Kraft, große Visionen in Realität zu verwandeln." },
      { num: "33", meaning: "Meisterzahl: Meisterlehrer. Bedingungslose Liebe, Heilung und universeller Dienst." },
    ]},
    { term: "Persönliche Jahreszahl", desc: "Berechnet durch Addition deines Geburtstags und -monats mit den Ziffern des aktuellen Jahres. Sie bietet eine zyklische Energiekarte von 1 bis 9. Jedes Jahr bringt ein anderes Thema und eine andere Energie." },
    { term: "Reduktion", desc: "Der Prozess, mehrstellige Zahlen in der Numerologie auf eine einzelne Ziffer zu reduzieren. Alle Ziffern werden addiert; ist das Ergebnis größer als 9, werden sie erneut addiert. 11, 22 und 33 sind „Meisterzahlen“ und werden nicht reduziert." },
  ]},
  { cat: "guide_cat_astrology", items: [
    { term: "Sternzeichen (Sonnenzeichen)", desc: "Das Zeichen, in dem die Sonne bei deiner Geburt stand. Repräsentiert deine Kernpersönlichkeit, dein Ego und deine Lebensenergie. Es gibt 12 Zeichen: Widder, Stier, Zwillinge, Krebs, Löwe, Jungfrau, Waage, Skorpion, Schütze, Steinbock, Wassermann, Fische." },
    { term: "Aszendent (Aufsteigendes Zeichen)", desc: "Das Zeichen, das im Moment deiner Geburt am Horizont aufstieg. Bestimmt, wie die Welt dich sieht, dein körperliches Erscheinungsbild und deinen ersten Eindruck. Für die Berechnung ist die Geburtszeit nötig." },
    { term: "12. Haus & Herrscherplanet", desc: "In der Astrologie repräsentiert das 12. Haus das Unterbewusste, verborgene Kräfte, spirituelles Potenzial und die innere Welt. Jedes Haus hat einen Herrscherplaneten, der bestimmt, wie du seine Themen erlebst." },
    { term: "Draconische Karte", desc: "Die Geburtskarte sagt dir, wer du bist; die draconische Karte sagt dir, was deine Seele vor der Inkarnation war. Berechnet mit dem Nordknoten auf 0° Widder fixiert. Von Pamela Crane und Ronald Davison in den 1970ern systematisiert. Die draconische Sonne ist die wahre Identität der Seele; die natale Sonne ist die Maske, die du in diesem Leben trägst." },
    { term: "Planetenkräfte", desc: "Jeder Planet regiert verschiedene Lebensbereiche: Sonne (Selbst), Mond (Emotionen), Merkur (Kommunikation), Venus (Liebe), Mars (Handlung), Jupiter (Expansion), Saturn (Disziplin), Uranus (Originalität), Neptun (Vorstellungskraft), Pluto (Transformation)." },
    { term: "Nordknoten & Südknoten", desc: "Die beiden Punkte, an denen die Mondbahn die Ekliptik schneidet; kein physischer Himmelskörper, sondern ein mathematischer Schnittpunkt. Der Südknoten steht für Muster, die du aus der Vergangenheit mitbringst und die bequem sind, dich aber nicht wachsen lassen; der Nordknoten für die Richtung, der du dich in diesem Leben zuwenden darfst und die sich anfangs herausfordernd anfühlt." },
    { term: "Rückläufigkeit (Retrograde)", desc: "Ein Planet scheint von der Erde aus betrachtet rückwärts zu laufen. In Wirklichkeit tut er das nicht; es ist eine optische Täuschung, die aus dem Geschwindigkeitsunterschied zweier Planeten entsteht. In der Astrologie gelten solche Phasen als Zeit des Überarbeitens, Abschließens und Nachinnenschauens." },
    { term: "Transit", desc: "Die Winkelbeziehung zwischen den aktuellen Positionen der Planeten am Himmel und den Punkten deines Geburtshoroskops. Der Transit-Hinweis im Himmelsbericht von Sakin ist NICHT persönlich, sondern KOLLEKTIV: er beschreibt denselben Himmel für alle an diesem Tag." },
    { term: "Mondphase", desc: "Der Beleuchtungszyklus, der aus der Stellung des Mondes zur Sonne entsteht; er dauert etwa 29,5 Tage. Der Neumond wird mit dem Säen von Absichten verbunden, der Vollmond mit dem Sichtbarmachen und dem Loslassen." },
  ]},
  { cat: "guide_cat_chakra", items: [
    { term: "Was ist ein Chakra?", desc: "Bedeutet „Rad“ im Sanskrit. Energiezentren im Körper. 7 Hauptchakren reihen sich entlang der Wirbelsäule, jedes regiert verschiedene körperliche, emotionale und spirituelle Bereiche." },
    { term: "1. Wurzelchakra (Muladhara)", desc: "Ort: Basis der Wirbelsäule. Farbe: Rot. Element: Erde. Steht für: Sicherheit, Überleben, Grundbedürfnisse, Erdung." },
    { term: "2. Sakralchakra (Svadhisthana)", desc: "Ort: Unterhalb des Nabels. Farbe: Orange. Element: Wasser. Steht für: Kreativität, Emotionen, Sexualität, Genuss." },
    { term: "3. Solarplexus-Chakra (Manipura)", desc: "Ort: Magengegend. Farbe: Gelb. Element: Feuer. Steht für: Selbstvertrauen, Willenskraft, persönliche Macht." },
    { term: "4. Herzchakra (Anahata)", desc: "Ort: Brustmitte. Farbe: Grün. Element: Luft. Steht für: Liebe, Mitgefühl, Vergebung, Beziehungen." },
    { term: "5. Halschakra (Vishuddha)", desc: "Ort: Hals. Farbe: Blau. Element: Klang. Steht für: Kommunikation, Selbstausdruck, Wahrheit." },
    { term: "6. Drittes-Auge-Chakra (Ajna)", desc: "Ort: Zwischen den Augenbrauen. Farbe: Indigo. Element: Licht. Steht für: Intuition, Einsicht, Vorstellungskraft, Weisheit." },
    { term: "7. Kronenchakra (Sahasrara)", desc: "Ort: Scheitel des Kopfes. Farbe: Violett/Weiß. Element: Universum. Steht für: universelle Verbindung, Erleuchtung." },
    { term: "22-Chakra-System", desc: "Über die 7 Hauptchakren hinaus gibt es 15 zusätzliche Energiezentren (darunter Erdstern, Seele, Thymus, Orion, Seelenstern), die in der erweiterten Reiki-Therapie verwendet werden." },
  ]},
  { cat: "guide_cat_biorhythm", items: [
    { term: "Was ist Biorhythmus?", desc: "Drei zyklische biologische Rhythmen, die mit deinem Geburtsdatum beginnen. Jeder schwingt in Sinuswellen zwischen positiv und negativ, mit Werten von -100 bis +100." },
    { term: "Körperlicher Biorhythmus (23 Tage)", desc: "Spiegelt körperliche Energie, Kraft, Ausdauer und Koordination wider. Positive Phasen = hohe Energie, negative = Ruhe nötig." },
    { term: "Emotionaler Biorhythmus (28 Tage)", desc: "Spiegelt emotionale Balance, Stimmung, Kreativität und Intuition wider. Positiv = optimistisch, negativ = empfindsam und nach innen gekehrt." },
    { term: "Mentaler Biorhythmus (33 Tage)", desc: "Spiegelt geistige Schärfe, Konzentration, Gedächtnis und analytisches Denken wider. Positiv = geistig aktiv, negativ = Fokus fällt schwerer." },
  ]},
  { cat: "guide_cat_reiki", items: [
    { term: "Was ist Reiki?", desc: "Eine japanische Energieheilmethode, die „universelle Lebensenergie“ bedeutet. Aktiviert die natürlichen Heilungsmechanismen des Körpers durch das Auflegen der Hände auf Energiezentren (Chakren). Keine medizinische Behandlung; eine ergänzende Wellness-Praxis." },
    { term: "Chakra-Therapie", desc: "60-Sekunden-Sitzungen in Sakin, die dir helfen, dich auf dein gewähltes Chakra zu konzentrieren: die Hand auf den Bereich legen, die Augen schließen und atmen." },
    { term: "Heilungssuche", desc: "Ein KI-gestütztes Analyse-Tool, das Reiki-Weisheit, Louise Hays mental-emotionale Ursachenkarte und Chakra-Theorie verbindet, um personalisierte Einsichten zu liefern." },
    { term: "Louise-Hay-Methode", desc: "Ein Ansatz, der mentale und emotionale Ursachen hinter körperlichen Beschwerden untersucht. Zum Beispiel werden Kopfschmerzen mit „Selbstabwertung“ und Rückenschmerzen mit „Mangel an emotionaler Unterstützung“ verknüpft." },
    { term: "Innerer Spiegel", desc: "KI-Analyse-Tool, mit dem du innere Ursachen entdeckst, indem du über deine körperlichen Beschwerden oder emotionalen Zustände schreibst." },
  ]},
  { cat: "guide_cat_app", items: [
    { term: "Morgenabsicht", desc: "Die Praxis, jeden Tag mit einer bewussten Absicht zu beginnen. Du setzt den Fokus des Tages mit einem kurzen Satz oder Wort." },
    { term: "3 Worte wählen", desc: "Wähle 3 Kraftworte aus 12 Optionen (Frieden, Fluss, Mut, Geduld, Klarheit, Liebe, Stärke, Balance, Freiheit, Freude, Dankbarkeit, Vertrauen), um die Energierichtung des Tages zu setzen." },
    { term: "Atemübung (4-1,5-3,5)", desc: "Einatmen (4s) → Halten (1,5s) → Ausatmen (3,5s) → Ruhe-Rhythmus. Aktiviert das parasympathische Nervensystem, reduziert Stress und verbessert den Fokus." },
    { term: "Tägliche Erinnerungen", desc: "10 Mikro-Praktiken über den Tag verteilt: in den Spiegel schauen, Wasser trinken, Atembewusstheit, Körperübung, die Sonne spüren, einen Baum umarmen, die Erde berühren, in den Himmel schauen, Chakra-Moment und Social-Media-Pause." },
    { term: "Abendlicher Abschluss", desc: "Ein Ritual, um den Tag bewusst zu beenden. Extrahiere deine Bewusstheits-Zusammenfassung mit den Fragen „Was hast du heute gelernt?“ und „Dankbarkeit?“." },
    { term: "Wöchentliche Innenkarte", desc: "Übersichtsbildschirm mit Wochenstatistiken: aktivstes Chakra, Atemzüge insgesamt, Absichtsworte und bewusste Momente. Der KI-Bericht erstellt aus diesen Daten eine wöchentliche Synthese." },
    { term: "Geburtsprofil", desc: "Deine persönliche Energiekarte, berechnet aus Geburtsdatum und -zeit: Sternzeichen, Lebenszahl, persönliches Jahr, Aszendent, 12.-Haus-Analyse und wöchentliches Biorhythmus-Diagramm." },
    { term: "Solfeggio-Frequenzen", desc: "Die sechs Grundtöne in Sakin (396, 417, 528, 639, 741, 852 Hz) sowie 963 Hz für das Kronenchakra. Jede Frequenz ist einem Chakra zugeordnet. Sie sind keine Behandlungsmethode, sondern ein akustischer Anker, der hilft, die Aufmerksamkeit im Körper zu sammeln." },
    { term: "Verbindung & Tagesserie", desc: "Wenn du die 7 Schritte des Tages abschließt (Morgen, Tagesaufgaben, Atem, Klang, Chakra, Abend, Spiegel), wird die Verbindung aktiv und die Chakra-Säule verwandelt sich in einen Lichttunnel. Aufeinanderfolgende Tage lassen die Serie wachsen: nach 7 Tagen Stufe 2 (x2), nach 21 Tagen Stufe 3 (x4)." },
    { term: "Himmelsbericht", desc: "Eine tägliche kollektive Zusammenfassung, die Mondphase, Sonneneruptionen, geomagnetische Aktivität (Kp-Index), Sonnenwind und Meteorschauer verbindet. Die Daten stammen aus dem offenen Weltraumwetterdienst der NOAA; die Deutung ist für alle dieselbe." },
    { term: "Galaktische Identität", desc: "Eine teilbare persönliche Karte, die aus deinen Geburtsdaten erzeugt wird. Sie fasst Sternzeichen, Aszendent, Lebenszahl und Elementverteilung in einem Bild zusammen." },
    { term: "Elementverteilung", desc: "Die Verteilung der Planeten deines Geburtshoroskops auf Feuer, Erde, Luft und Wasser. Sonne und Mond wiegen dabei schwerer. Das dominante Element zeigt deine natürliche Neigung, das schwächste den Bereich, den du bewusst nähren darfst." },
    { term: "Kopf leeren (Kaleidoskop)", desc: "Ein bildschirmfüllender visuell-akustischer Ruheraum mit vier Modi (Stille, Klarheit, Hingabe, Weite). Muster und Töne entstehen im Moment; es sind keine Aufnahmen, jedes Mal fließt es anders." },
    { term: "Panikknopf", desc: "Für plötzliche Angstmomente gedacht, mit schnellem Zugriff. Er führt dich direkt in den 4-7-8-Atemmodus. Dieser Rhythmus verlängert die Ausatmung und unterstützt das parasympathische Nervensystem. Das ist keine medizinische Maßnahme; wähle im Notfall die Notrufnummer deines Landes." },
  ]},
];

const ES = [
  { cat: "guide_cat_numerology", items: [
    { term: "Número de Camino de Vida", desc: "Calculado al reducir todos los dígitos de tu fecha de nacimiento a un solo dígito (o números maestros 11, 22, 33). Representa tu propósito de vida, talentos naturales y la energía esencial de tu viaje.", examples: [
      { num: "1", meaning: "Líder, independiente, pionero. Energía valiente y decidida que traza su propio camino." },
      { num: "2", meaning: "Diplomático, armonioso, sensible. Energía cooperativa e intuitiva que busca equilibrio." },
      { num: "3", meaning: "Creativo, expresivo, alegre. Energía de arte, comunicación y conexión social." },
      { num: "4", meaning: "Constructor, disciplinado, confiable. Energía de orden, estabilidad y cimientos sólidos." },
      { num: "5", meaning: "Espíritu libre, aventurero, cambiante. Energía de libertad, viaje y experiencia." },
      { num: "6", meaning: "Cuidador, responsable, armonioso. Energía de familia, hogar y comunidad." },
      { num: "7", meaning: "Investigador, místico, introspectivo. Energía de espiritualidad, análisis y pensamiento profundo." },
      { num: "8", meaning: "Poderoso, ambicioso, exitoso. Energía de abundancia material, autoridad y logro." },
      { num: "9", meaning: "Humanitario, sabio, que completa. Energía de amor universal, compasión y soltar." },
      { num: "11", meaning: "Número Maestro: Iluminador intuitivo. Energía de alta conciencia y enseñanza espiritual." },
      { num: "22", meaning: "Número Maestro: Maestro constructor. Poder para convertir grandes visiones en realidad." },
      { num: "33", meaning: "Número Maestro: Maestro educador. Amor incondicional, sanación y servicio universal." },
    ]},
    { term: "Número del Año Personal", desc: "Calculado sumando tu día y mes de nacimiento con los dígitos del año actual. Ofrece un mapa cíclico de energía del 1 al 9. Cada año trae un tema y energía diferente." },
    { term: "Reducción", desc: "El proceso de reducir números de varias cifras a un solo dígito en numerología. Se suman todos los dígitos; si el resultado es mayor que 9, se suman de nuevo. 11, 22 y 33 son \"Números Maestros\" y no se reducen." },
  ]},
  { cat: "guide_cat_astrology", items: [
    { term: "Signo Zodiacal (Signo Solar)", desc: "El signo donde estaba el Sol al nacer. Representa tu personalidad central, ego y energía vital. Hay 12 signos: Aries, Tauro, Géminis, Cáncer, Leo, Virgo, Libra, Escorpio, Sagitario, Capricornio, Acuario, Piscis." },
    { term: "Ascendente (Signo en Ascenso)", desc: "El signo que se eleva en el horizonte en el momento de tu nacimiento. Determina cómo te ve el mundo, tu apariencia física y primera impresión. Se necesita la hora de nacimiento para calcularlo." },
    { term: "Casa 12 y Planeta Regente", desc: "En astrología, la Casa 12 representa el subconsciente, los poderes ocultos, el potencial espiritual y el mundo interior. Cada casa tiene un planeta regente que determina cómo experimentas sus temas." },
    { term: "Carta Dracónica", desc: "La carta natal te dice quién eres; la carta dracónica te dice qué era tu alma antes de entrar en este cuerpo. Se calcula fijando el Nodo Norte a 0° Aries. Sistematizada por Pamela Crane y Ronald Davison en los 70. El Sol dracónico es la verdadera identidad del alma; el Sol natal es la máscara en esta vida." },
    { term: "Fuerzas Planetarias", desc: "Cada planeta rige un área de vida diferente: Sol (yo), Luna (emociones), Mercurio (comunicación), Venus (amor), Marte (acción), Júpiter (expansión), Saturno (disciplina), Urano (originalidad), Neptuno (imaginación), Plutón (transformación)." },
    { term: "Nodo Norte y Nodo Sur", desc: "Los dos puntos donde la órbita de la Luna corta la eclíptica; no son un cuerpo físico, sino una intersección matemática. El Nodo Sur representa los patrones que traes del pasado, cómodos pero que no te hacen crecer; el Nodo Norte, la dirección hacia la que conviene moverte en esta vida, que al principio resulta exigente." },
    { term: "Retrógrado", desc: "Un planeta parece moverse hacia atrás visto desde la Tierra. En realidad no retrocede; es una ilusión óptica que surge de la diferencia de velocidad entre dos planetas. En astrología, estos periodos se leen como tiempo de revisar, completar y mirar hacia dentro." },
    { term: "Tránsito", desc: "La relación angular entre las posiciones actuales de los planetas y los puntos de tu carta natal. La nota de tránsito del informe del cielo de Sakin NO es personal sino COLECTIVA: describe el mismo cielo para todos ese día." },
    { term: "Fase lunar", desc: "El ciclo de iluminación que surge de la posición de la Luna respecto al Sol; se completa en unos 29,5 días. La Luna nueva se asocia con sembrar intenciones y la Luna llena con hacer visible y soltar." },
  ]},
  { cat: "guide_cat_chakra", items: [
    { term: "¿Qué es un Chakra?", desc: "Significa \"rueda\" en sánscrito. Son centros de energía en el cuerpo. 7 chakras principales se alinean a lo largo de la columna, cada uno rige áreas físicas, emocionales y espirituales diferentes." },
    { term: "1. Chakra Raíz (Muladhara)", desc: "Ubicación: Base de la columna. Color: Rojo. Elemento: Tierra. Representa: Seguridad, supervivencia, necesidades básicas, enraizamiento." },
    { term: "2. Chakra Sacro (Svadhisthana)", desc: "Ubicación: Debajo del ombligo. Color: Naranja. Elemento: Agua. Representa: Creatividad, emociones, sexualidad, placer." },
    { term: "3. Chakra del Plexo Solar (Manipura)", desc: "Ubicación: Área del estómago. Color: Amarillo. Elemento: Fuego. Representa: Confianza, voluntad, poder personal." },
    { term: "4. Chakra del Corazón (Anahata)", desc: "Ubicación: Centro del pecho. Color: Verde. Elemento: Aire. Representa: Amor, compasión, perdón, relaciones." },
    { term: "5. Chakra de la Garganta (Vishuddha)", desc: "Ubicación: Garganta. Color: Azul. Elemento: Sonido. Representa: Comunicación, autoexpresión, verdad." },
    { term: "6. Chakra del Tercer Ojo (Ajna)", desc: "Ubicación: Entre las cejas. Color: Índigo. Elemento: Luz. Representa: Intuición, perspicacia, imaginación, sabiduría." },
    { term: "7. Chakra Corona (Sahasrara)", desc: "Ubicación: Coronilla. Color: Violeta/Blanco. Elemento: Universo. Representa: Conexión universal, iluminación." },
    { term: "Sistema de 22 Chakras", desc: "Más allá de los 7 chakras principales, existen 15 centros de energía adicionales (incluyendo Estrella Terrestre, Alma, Timo, Orión, Estrella del Alma) usados en la terapia Reiki ampliada." },
  ]},
  { cat: "guide_cat_biorhythm", items: [
    { term: "¿Qué es el Biorritmo?", desc: "Tres ritmos biológicos cíclicos que comienzan desde tu fecha de nacimiento. Cada uno oscila entre positivo y negativo en ondas sinusoidales, con valores de -100 a +100." },
    { term: "Biorritmo Físico (23 días)", desc: "Refleja energía física, fuerza, resistencia y coordinación. Períodos positivos = alta energía, negativos = se necesita descanso." },
    { term: "Biorritmo Emocional (28 días)", desc: "Refleja equilibrio emocional, estado de ánimo, creatividad e intuición. Positivo = optimista, negativo = sensible e introvertido." },
    { term: "Biorritmo Mental (33 días)", desc: "Refleja agudeza mental, concentración, memoria y pensamiento analítico. Positivo = mentalmente activo, negativo = más difícil enfocarse." },
  ]},
  { cat: "guide_cat_reiki", items: [
    { term: "¿Qué es el Reiki?", desc: "Un método japonés de sanación energética que significa \"energía vital universal\". Activa el mecanismo natural de sanación del cuerpo colocando las manos sobre los centros de energía (chakras). No es tratamiento médico; es una práctica de bienestar complementaria." },
    { term: "Terapia de Chakras", desc: "Sesiones de 60 segundos en Sakin que te ayudan a enfocarte en el chakra elegido colocando la mano sobre el área, cerrando los ojos y respirando." },
    { term: "Búsqueda de Sanación", desc: "Una herramienta de análisis con IA que combina la sabiduría Reiki, el mapa mental-emocional de Louise Hay y la teoría de chakras para ofrecer percepciones personalizadas." },
    { term: "Método de Louise Hay", desc: "Un enfoque que examina las causas mentales y emocionales detrás de las dolencias físicas. Por ejemplo, los dolores de cabeza se relacionan con \"autoinvalidación\" y los dolores de espalda con \"falta de apoyo emocional\"." },
    { term: "Espejo Interior", desc: "Herramienta de análisis con IA que te permite descubrir las causas internas escribiendo sobre tus quejas físicas o estados emocionales." },
  ]},
  { cat: "guide_cat_app", items: [
    { term: "Intención Matinal", desc: "La práctica de comenzar cada día con una intención consciente. Estableces el punto focal del día con una frase corta o una palabra." },
    { term: "Selección de 3 Palabras", desc: "Elige 3 palabras de poder de 12 opciones (paz, fluir, valor, paciencia, claridad, amor, fuerza, equilibrio, libertad, alegría, gratitud, confianza) para establecer la dirección energética del día." },
    { term: "Ejercicio de Respiración (4-1,5-3,5)", desc: "Inhalar (4s) → Sostener (1,5s) → Exhalar (3,5s) → Ritmo de descanso. Activa el sistema nervioso parasimpático, reduce el estrés y mejora la concentración." },
    { term: "Recordatorios Diarios", desc: "10 micro-prácticas a lo largo del día: mirarse al espejo, beber agua, conciencia de la respiración, ejercicio corporal, sentir el sol, abrazar un árbol, tocar la tierra, mirar al cielo, momento de chakra y pausa de redes sociales." },
    { term: "Cierre Vespertino", desc: "Un ritual para cerrar el día conscientemente. Extrae tu resumen de conciencia con las preguntas \"¿Qué aprendiste hoy?\" y \"¿Gratitud?\"." },
    { term: "Mapa Interior Semanal", desc: "Pantalla resumen que muestra las estadísticas de la semana: chakra más activo, total de respiraciones, palabras de intención y momentos conscientes. El informe IA crea una síntesis semanal a partir de estos datos." },
    { term: "Perfil de Nacimiento", desc: "Tu mapa energético personal calculado desde tu fecha y hora de nacimiento: signo zodiacal, número de camino de vida, año personal, ascendente, análisis de la Casa 12 y gráfico semanal de biorritmo." },
    { term: "Frecuencias Solfeggio", desc: "Los seis tonos base que usa Sakin (396, 417, 528, 639, 741 y 852 Hz) y 963 Hz para el chakra corona. Cada frecuencia se asocia a un chakra. No son un tratamiento, sino un ancla sonora que ayuda a reunir la atención en el cuerpo." },
    { term: "Conexión y racha diaria", desc: "Cuando completas los 7 pasos del día (mañana, tareas del día, respiración, sonido, chakra, noche y espejo), la conexión se activa y la columna de chakras se convierte en un túnel de luz. Los días consecutivos hacen crecer la racha: a los 7 días, nivel 2 (x2); a los 21 días, nivel 3 (x4)." },
    { term: "Informe del cielo", desc: "Un resumen colectivo diario que combina la fase lunar, las erupciones solares, la actividad geomagnética (índice Kp), el viento solar y las lluvias de meteoros. Los datos provienen del servicio abierto de meteorología espacial de la NOAA; la interpretación es la misma para todos." },
    { term: "Identidad galáctica", desc: "Una tarjeta personal que se puede compartir, generada a partir de tus datos de nacimiento. Reúne en una sola imagen tu signo, tu ascendente, tu número de camino de vida y tu distribución de elementos." },
    { term: "Distribución de elementos", desc: "El reparto de los planetas de tu carta natal entre fuego, tierra, aire y agua. El Sol y la Luna pesan más. El elemento dominante muestra tu inclinación natural y el más débil, el área que conviene nutrir con conciencia." },
    { term: "Vaciar la mente (caleidoscopio)", desc: "Un espacio de descanso visual y sonoro a pantalla completa con cuatro modos (calma, claridad, entrega, amplitud). Los patrones y los tonos se generan en el momento; no son grabaciones y cada vez fluyen distinto." },
    { term: "Botón de pánico", desc: "Pensado para momentos de ansiedad repentina, con acceso rápido. Te lleva directamente al modo de respiración 4-7-8. Ese ritmo alarga la exhalación y apoya al sistema nervioso parasimpático. No es una intervención médica; en caso de emergencia llama al número de emergencias de tu país." },
  ]},
];

const PT = [
  { cat: "guide_cat_numerology", items: [
    { term: "Número do Caminho de Vida", desc: "Calculado reduzindo todos os dígitos da sua data de nascimento a um único dígito (ou números mestres 11, 22, 33). Representa seu propósito de vida, talentos naturais e a energia central da sua jornada.", examples: [
      { num: "1", meaning: "Líder, independente, pioneiro. Energia corajosa e determinada que traça seu próprio caminho." },
      { num: "2", meaning: "Diplomata, harmonioso, sensível. Energia cooperativa e intuitiva que busca equilíbrio." },
      { num: "3", meaning: "Criativo, expressivo, alegre. Energia de arte, comunicação e conexão social." },
      { num: "4", meaning: "Construtor, disciplinado, confiável. Energia de ordem, estabilidade e fundações sólidas." },
      { num: "5", meaning: "Espírito livre, aventureiro, mutável. Energia de liberdade, viagem e experiência." },
      { num: "6", meaning: "Cuidador, responsável, harmonioso. Energia de família, lar e comunidade." },
      { num: "7", meaning: "Pesquisador, místico, introspectivo. Energia de espiritualidade, análise e pensamento profundo." },
      { num: "8", meaning: "Poderoso, ambicioso, bem-sucedido. Energia de abundância material, autoridade e realização." },
      { num: "9", meaning: "Humanitário, sábio, que completa. Energia de amor universal, compaixão e soltar." },
      { num: "11", meaning: "Número Mestre: Iluminador intuitivo. Energia de alta consciência e ensino espiritual." },
      { num: "22", meaning: "Número Mestre: Mestre construtor. Poder de transformar grandes visões em realidade." },
      { num: "33", meaning: "Número Mestre: Mestre educador. Amor incondicional, cura e serviço universal." },
    ]},
    { term: "Número do Ano Pessoal", desc: "Calculado somando seu dia e mês de nascimento com os dígitos do ano atual. Fornece um mapa cíclico de energia de 1 a 9. Cada ano traz um tema e energia diferentes." },
    { term: "Redução", desc: "O processo de reduzir números de vários dígitos a um único dígito em numerologia. Todos os dígitos são somados; se o resultado for maior que 9, são somados novamente. 11, 22 e 33 são \"Números Mestres\" e não são reduzidos." },
  ]},
  { cat: "guide_cat_astrology", items: [
    { term: "Signo Solar", desc: "O signo em que o Sol estava ao nascer. Representa sua personalidade central, ego e energia vital. Há 12 signos: Áries, Touro, Gêmeos, Câncer, Leão, Virgem, Libra, Escorpião, Sagitário, Capricórnio, Aquário, Peixes." },
    { term: "Ascendente", desc: "O signo que sobe no horizonte no momento do seu nascimento. Determina como o mundo te vê, sua aparência física e primeira impressão. O horário de nascimento é necessário para o cálculo." },
    { term: "Casa 12 e Planeta Regente", desc: "Na astrologia, a Casa 12 representa o subconsciente, poderes ocultos, potencial espiritual e mundo interior. Cada casa tem um planeta regente que determina como você vivencia seus temas." },
    { term: "Mapa Dracônico", desc: "O mapa natal diz quem você é; o mapa dracônico diz o que sua alma era antes desta encarnação. Calculado fixando o Nodo Norte a 0° de Áries. Sistematizado por Pamela Crane e Ronald Davison nos anos 70. O Sol dracônico é a verdadeira identidade da alma; o Sol natal é a máscara desta vida." },
    { term: "Forças Planetárias", desc: "Cada planeta rege uma área diferente da vida: Sol (eu), Lua (emoções), Mercúrio (comunicação), Vênus (amor), Marte (ação), Júpiter (expansão), Saturno (disciplina), Urano (originalidade), Netuno (imaginação), Plutão (transformação)." },
    { term: "Nodo Norte e Nodo Sul", desc: "Os dois pontos onde a órbita da Lua cruza a eclíptica; não são um corpo físico, mas uma interseção matemática. O Nodo Sul representa os padrões que trazes do passado, confortáveis mas que não te fazem crescer; o Nodo Norte, a direção para a qual convém voltares-te nesta vida, que no início parece exigente." },
    { term: "Retrógrado", desc: "Um planeta parece andar para trás quando visto da Terra. Na realidade não recua; é uma ilusão ótica que nasce da diferença de velocidade entre dois planetas. Na astrologia, estes períodos são lidos como tempo de rever, completar e olhar para dentro." },
    { term: "Trânsito", desc: "A relação angular entre as posições atuais dos planetas e os pontos do teu mapa natal. A nota de trânsito no relatório do céu do Sakin NÃO é pessoal, é COLETIVA: descreve o mesmo céu para toda a gente nesse dia." },
    { term: "Fase da Lua", desc: "O ciclo de iluminação que nasce da posição da Lua em relação ao Sol; completa-se em cerca de 29,5 dias. A Lua nova associa-se a semear intenções e a Lua cheia a tornar visível e a soltar." },
  ]},
  { cat: "guide_cat_chakra", items: [
    { term: "O que é um Chakra?", desc: "Significa \"roda\" em sânscrito. São centros de energia no corpo. 7 chakras principais se alinham ao longo da coluna, cada um rege áreas físicas, emocionais e espirituais diferentes." },
    { term: "1. Chakra Raiz (Muladhara)", desc: "Localização: Base da coluna. Cor: Vermelho. Elemento: Terra. Representa: Segurança, sobrevivência, necessidades básicas, enraizamento." },
    { term: "2. Chakra Sacral (Svadhisthana)", desc: "Localização: Abaixo do umbigo. Cor: Laranja. Elemento: Água. Representa: Criatividade, emoções, sexualidade, prazer." },
    { term: "3. Chakra do Plexo Solar (Manipura)", desc: "Localização: Região do estômago. Cor: Amarelo. Elemento: Fogo. Representa: Confiança, força de vontade, poder pessoal." },
    { term: "4. Chakra Cardíaco (Anahata)", desc: "Localização: Centro do peito. Cor: Verde. Elemento: Ar. Representa: Amor, compaixão, perdão, relacionamentos." },
    { term: "5. Chakra Laríngeo (Vishuddha)", desc: "Localização: Garganta. Cor: Azul. Elemento: Som. Representa: Comunicação, autoexpressão, verdade." },
    { term: "6. Chakra do Terceiro Olho (Ajna)", desc: "Localização: Entre as sobrancelhas. Cor: Índigo. Elemento: Luz. Representa: Intuição, percepção, imaginação, sabedoria." },
    { term: "7. Chakra Coronário (Sahasrara)", desc: "Localização: Topo da cabeça. Cor: Violeta/Branco. Elemento: Universo. Representa: Conexão universal, iluminação." },
    { term: "Sistema de 22 Chakras", desc: "Além dos 7 chakras principais, há 15 centros de energia adicionais (incluindo Estrela Terrestre, Alma, Timo, Órion, Estrela da Alma) usados na terapia Reiki estendida." },
  ]},
  { cat: "guide_cat_biorhythm", items: [
    { term: "O que é Biorritmo?", desc: "Três ritmos biológicos cíclicos que começam na sua data de nascimento. Cada um oscila entre positivo e negativo em ondas senoidais, com valores de -100 a +100." },
    { term: "Biorritmo Físico (23 dias)", desc: "Reflete energia física, força, resistência e coordenação. Períodos positivos = alta energia, negativos = necessidade de descanso." },
    { term: "Biorritmo Emocional (28 dias)", desc: "Reflete equilíbrio emocional, humor, criatividade e intuição. Positivo = otimista, negativo = sensível e introvertido." },
    { term: "Biorritmo Mental (33 dias)", desc: "Reflete agudeza mental, concentração, memória e pensamento analítico. Positivo = mentalmente ativo, negativo = mais difícil focar." },
  ]},
  { cat: "guide_cat_reiki", items: [
    { term: "O que é Reiki?", desc: "Um método japonês de cura energética que significa \"energia vital universal\". Ativa o mecanismo natural de cura do corpo colocando as mãos sobre os centros de energia (chakras). Não é tratamento médico; é uma prática de bem-estar complementar." },
    { term: "Terapia de Chakras", desc: "Sessões de 60 segundos no Sakin que te ajudam a focar no chakra escolhido colocando a mão sobre a região, fechando os olhos e respirando." },
    { term: "Busca de Cura", desc: "Uma ferramenta de análise com IA que combina sabedoria Reiki, o mapa mental-emocional de Louise Hay e a teoria dos chakras para oferecer insights personalizados." },
    { term: "Método de Louise Hay", desc: "Uma abordagem que examina causas mentais e emocionais por trás de doenças físicas. Por exemplo, dores de cabeça são associadas a \"autoinvalidação\" e dores nas costas a \"falta de apoio emocional\"." },
    { term: "Espelho Interior", desc: "Ferramenta de análise com IA que te permite descobrir causas internas escrevendo sobre suas queixas físicas ou estados emocionais." },
  ]},
  { cat: "guide_cat_app", items: [
    { term: "Intenção Matinal", desc: "A prática de começar cada dia com uma intenção consciente. Você define o ponto focal do dia com uma frase curta ou palavra." },
    { term: "Seleção de 3 Palavras", desc: "Escolha 3 palavras de poder dentre 12 opções (paz, fluxo, coragem, paciência, clareza, amor, força, equilíbrio, liberdade, alegria, gratidão, confiança) para definir a direção energética do dia." },
    { term: "Exercício Respiratório (4-1,5-3,5)", desc: "Inspirar (4s) → Segurar (1,5s) → Expirar (3,5s) → Ritmo de descanso. Ativa o sistema nervoso parassimpático, reduz o estresse e melhora o foco." },
    { term: "Lembretes Diários", desc: "10 micropráticas ao longo do dia: olhar-se no espelho, beber água, consciência da respiração, exercício corporal, sentir o sol, abraçar uma árvore, tocar a terra, olhar o céu, momento de chakra e pausa das redes sociais." },
    { term: "Fechamento Noturno", desc: "Um ritual para fechar o dia conscientemente. Extraia seu resumo de consciência com as perguntas \"O que você aprendeu hoje?\" e \"Gratidão?\"." },
    { term: "Mapa Interior Semanal", desc: "Tela resumo que mostra as estatísticas da semana: chakra mais ativo, total de respirações, palavras de intenção e momentos conscientes. O relatório IA cria uma síntese semanal a partir desses dados." },
    { term: "Perfil de Nascimento", desc: "Seu mapa energético pessoal calculado a partir da data e hora de nascimento: signo, número do caminho de vida, ano pessoal, ascendente, análise da Casa 12 e gráfico semanal de biorritmo." },
    { term: "Frequências Solfeggio", desc: "Os seis tons base usados no Sakin (396, 417, 528, 639, 741 e 852 Hz) e 963 Hz para o chakra da coroa. Cada frequência corresponde a um chakra. Não são um tratamento, mas uma âncora sonora que ajuda a reunir a atenção no corpo." },
    { term: "Conexão e sequência diária", desc: "Quando completas os 7 passos do dia (manhã, tarefas do dia, respiração, som, chakra, noite e espelho), a conexão ativa-se e a coluna de chakras transforma-se num túnel de luz. Os dias seguidos fazem crescer a sequência: aos 7 dias, nível 2 (x2); aos 21 dias, nível 3 (x4)." },
    { term: "Relatório do céu", desc: "Um resumo coletivo diário que junta a fase da Lua, as erupções solares, a atividade geomagnética (índice Kp), o vento solar e as chuvas de meteoros. Os dados vêm do serviço aberto de meteorologia espacial da NOAA; a interpretação é a mesma para toda a gente." },
    { term: "Identidade galáctica", desc: "Um cartão pessoal partilhável, gerado a partir dos teus dados de nascimento. Reúne numa só imagem o teu signo, o ascendente, o número do caminho de vida e a distribuição de elementos." },
    { term: "Distribuição dos elementos", desc: "A repartição dos planetas do teu mapa natal por fogo, terra, ar e água. O Sol e a Lua pesam mais. O elemento dominante mostra a tua inclinação natural e o mais fraco, a área que convém nutrir com consciência." },
    { term: "Esvaziar a mente (caleidoscópio)", desc: "Um espaço de descanso visual e sonoro em ecrã inteiro, com quatro modos (calma, clareza, entrega, amplitude). Os padrões e os tons são gerados no momento; não são gravações e fluem de forma diferente de cada vez." },
    { term: "Botão de pânico", desc: "Pensado para momentos de ansiedade repentina, com acesso rápido. Leva-te diretamente ao modo de respiração 4-7-8. Esse ritmo prolonga a expiração e apoia o sistema nervoso parassimpático. Não é uma intervenção médica; em emergência liga para o número de emergência do teu país." },
  ]},
];

const FR = [
  { cat: "guide_cat_numerology", items: [
    { term: "Chemin de Vie (Life Path Number)", desc: "Calculé en réduisant tous les chiffres de ta date de naissance à un seul chiffre (ou nombres maîtres 11, 22, 33). Il représente ton sens de la vie, tes talents naturels et l'énergie centrale de ton voyage.", examples: [
      { num: "1", meaning: "Leader, indépendant, pionnier. Énergie courageuse et déterminée qui trace son propre chemin." },
      { num: "2", meaning: "Diplomate, harmonieux, sensible. Énergie coopérative et intuitive qui cherche l'équilibre." },
      { num: "3", meaning: "Créatif, expressif, joyeux. Énergie d'art, de communication et de lien social." },
      { num: "4", meaning: "Bâtisseur, discipliné, fiable. Énergie d'ordre, de stabilité et de fondations solides." },
      { num: "5", meaning: "Esprit libre, aventureux, changeant. Énergie de liberté, de voyage et d'expérience." },
      { num: "6", meaning: "Soignant, responsable, harmonieux. Énergie de famille, de foyer et de communauté." },
      { num: "7", meaning: "Chercheur, mystique, introspectif. Énergie de spiritualité, d'analyse et de pensée profonde." },
      { num: "8", meaning: "Puissant, ambitieux, accompli. Énergie d'abondance matérielle, d'autorité et de réussite." },
      { num: "9", meaning: "Humanitaire, sage, qui complète. Énergie d'amour universel, de compassion et de lâcher-prise." },
      { num: "11", meaning: "Nombre Maître : Illuminateur intuitif. Énergie de haute conscience et d'enseignement spirituel." },
      { num: "22", meaning: "Nombre Maître : Maître bâtisseur. Pouvoir de transformer de grandes visions en réalité." },
      { num: "33", meaning: "Nombre Maître : Maître enseignant. Amour inconditionnel, guérison et service universel." },
    ]},
    { term: "Année Personnelle", desc: "Calculée en additionnant ton jour et mois de naissance avec les chiffres de l'année en cours. Offre une carte cyclique d'énergie de 1 à 9. Chaque année apporte un thème et une énergie différents." },
    { term: "Réduction", desc: "Le processus de réduction de nombres à plusieurs chiffres en un seul chiffre en numérologie. Tous les chiffres sont additionnés ; si le résultat est supérieur à 9, ils sont à nouveau additionnés. 11, 22 et 33 sont des « Nombres Maîtres » et ne sont pas réduits." },
  ]},
  { cat: "guide_cat_astrology", items: [
    { term: "Signe Solaire", desc: "Le signe dans lequel se trouvait le Soleil à ta naissance. Représente ta personnalité essentielle, ton ego et ton énergie vitale. Il y a 12 signes : Bélier, Taureau, Gémeaux, Cancer, Lion, Vierge, Balance, Scorpion, Sagittaire, Capricorne, Verseau, Poissons." },
    { term: "Ascendant", desc: "Le signe qui se lève à l'horizon au moment de ta naissance. Détermine la façon dont le monde te voit, ton apparence physique et ta première impression. L'heure de naissance est requise pour le calcul." },
    { term: "Maison 12 & Planète Maîtresse", desc: "En astrologie, la 12e maison représente l'inconscient, les pouvoirs cachés, le potentiel spirituel et le monde intérieur. Chaque maison a une planète maîtresse qui détermine comment tu vis ses thèmes." },
    { term: "Carte Draconique", desc: "La carte natale dit qui tu es ; la carte draconique dit ce que ton âme était avant cette incarnation. Calculée en fixant le Nœud Nord à 0° du Bélier. Systématisée par Pamela Crane et Ronald Davison dans les années 70. Le Soleil draconique est la vraie identité de l'âme ; le Soleil natal est le masque porté dans cette vie." },
    { term: "Forces Planétaires", desc: "Chaque planète régit un domaine de vie différent : Soleil (soi), Lune (émotions), Mercure (communication), Vénus (amour), Mars (action), Jupiter (expansion), Saturne (discipline), Uranus (originalité), Neptune (imagination), Pluton (transformation)." },
    { term: "Nœud Nord et Nœud Sud", desc: "Les deux points où l'orbite de la Lune croise l'écliptique ; ce ne sont pas des corps physiques mais une intersection mathématique. Le Nœud Sud représente les schémas que tu apportes du passé, confortables mais qui ne te font pas grandir ; le Nœud Nord, la direction vers laquelle te tourner dans cette vie, exigeante au début." },
    { term: "Rétrograde", desc: "Une planète semble reculer lorsqu'on l'observe depuis la Terre. En réalité elle ne recule pas ; c'est une illusion d'optique née de la différence de vitesse entre deux planètes. En astrologie, ces périodes se lisent comme un temps de révision, d'achèvement et de retour vers soi." },
    { term: "Transit", desc: "La relation angulaire entre la position actuelle des planètes et les points de ton thème natal. La note de transit du rapport du ciel de Sakin n'est PAS personnelle mais COLLECTIVE : elle décrit le même ciel pour tout le monde ce jour-là." },
    { term: "Phase de la Lune", desc: "Le cycle d'illumination né de la position de la Lune par rapport au Soleil ; il se boucle en environ 29,5 jours. La nouvelle Lune est associée aux intentions que l'on sème, la pleine Lune au fait de rendre visible et de lâcher." },
  ]},
  { cat: "guide_cat_chakra", items: [
    { term: "Qu'est-ce qu'un Chakra ?", desc: "Signifie « roue » en sanskrit. Centres d'énergie du corps. 7 chakras principaux s'alignent le long de la colonne vertébrale, chacun régissant différents domaines physiques, émotionnels et spirituels." },
    { term: "1. Chakra Racine (Muladhara)", desc: "Emplacement : Base de la colonne. Couleur : Rouge. Élément : Terre. Représente : Sécurité, survie, besoins fondamentaux, ancrage." },
    { term: "2. Chakra Sacré (Svadhisthana)", desc: "Emplacement : Sous le nombril. Couleur : Orange. Élément : Eau. Représente : Créativité, émotions, sexualité, plaisir." },
    { term: "3. Chakra du Plexus Solaire (Manipura)", desc: "Emplacement : Zone de l'estomac. Couleur : Jaune. Élément : Feu. Représente : Confiance, volonté, pouvoir personnel." },
    { term: "4. Chakra du Cœur (Anahata)", desc: "Emplacement : Centre de la poitrine. Couleur : Vert. Élément : Air. Représente : Amour, compassion, pardon, relations." },
    { term: "5. Chakra de la Gorge (Vishuddha)", desc: "Emplacement : Gorge. Couleur : Bleu. Élément : Son. Représente : Communication, expression de soi, vérité." },
    { term: "6. Chakra du Troisième Œil (Ajna)", desc: "Emplacement : Entre les sourcils. Couleur : Indigo. Élément : Lumière. Représente : Intuition, perspicacité, imagination, sagesse." },
    { term: "7. Chakra Couronne (Sahasrara)", desc: "Emplacement : Sommet de la tête. Couleur : Violet/Blanc. Élément : Univers. Représente : Connexion universelle, illumination." },
    { term: "Système des 22 Chakras", desc: "Au-delà des 7 chakras principaux, il existe 15 centres d'énergie supplémentaires (dont Étoile de la Terre, Âme, Thymus, Orion, Étoile de l'Âme) utilisés dans la thérapie Reiki étendue." },
  ]},
  { cat: "guide_cat_biorhythm", items: [
    { term: "Qu'est-ce que le Biorythme ?", desc: "Trois rythmes biologiques cycliques qui commencent à ta date de naissance. Chacun oscille entre positif et négatif en ondes sinusoïdales, avec des valeurs de -100 à +100." },
    { term: "Biorythme Physique (23 jours)", desc: "Reflète l'énergie physique, la force, l'endurance et la coordination. Périodes positives = haute énergie, négatives = besoin de repos." },
    { term: "Biorythme Émotionnel (28 jours)", desc: "Reflète l'équilibre émotionnel, l'humeur, la créativité et l'intuition. Positif = optimiste, négatif = sensible et introverti." },
    { term: "Biorythme Mental (33 jours)", desc: "Reflète l'acuité mentale, la concentration, la mémoire et la pensée analytique. Positif = mentalement actif, négatif = focalisation plus difficile." },
  ]},
  { cat: "guide_cat_reiki", items: [
    { term: "Qu'est-ce que le Reiki ?", desc: "Une méthode japonaise de guérison énergétique signifiant « énergie vitale universelle ». Active le mécanisme naturel de guérison du corps en plaçant les mains sur les centres d'énergie (chakras). Ce n'est pas un traitement médical ; c'est une pratique de bien-être complémentaire." },
    { term: "Thérapie des Chakras", desc: "Séances de 60 secondes dans Sakin qui t'aident à te concentrer sur le chakra choisi en plaçant la main sur la zone, en fermant les yeux et en respirant." },
    { term: "Recherche de Guérison", desc: "Un outil d'analyse alimenté par l'IA qui combine la sagesse Reiki, la carte mentale-émotionnelle de Louise Hay et la théorie des chakras pour offrir des insights personnalisés." },
    { term: "Méthode Louise Hay", desc: "Une approche qui examine les causes mentales et émotionnelles derrière les maux physiques. Par exemple, les maux de tête sont liés à « l'auto-invalidation » et les maux de dos à « un manque de soutien émotionnel »." },
    { term: "Miroir Intérieur", desc: "Outil d'analyse IA qui te permet de découvrir les causes intérieures en écrivant sur tes plaintes physiques ou états émotionnels." },
  ]},
  { cat: "guide_cat_app", items: [
    { term: "Intention Matinale", desc: "La pratique de commencer chaque jour avec une intention consciente. Tu fixes le point focal de la journée par une courte phrase ou un mot." },
    { term: "Sélection de 3 mots", desc: "Choisis 3 mots de pouvoir parmi 12 options (paix, flux, courage, patience, clarté, amour, force, équilibre, liberté, joie, gratitude, confiance) pour orienter l'énergie du jour." },
    { term: "Exercice respiratoire (4-1,5-3,5)", desc: "Inspirer (4s) → Retenir (1,5s) → Expirer (3,5s) → Rythme de repos. Active le système nerveux parasympathique, réduit le stress et améliore la concentration." },
    { term: "Rappels quotidiens", desc: "10 micro-pratiques tout au long de la journée : se regarder dans le miroir, boire de l'eau, conscience de la respiration, exercice corporel, sentir le soleil, embrasser un arbre, toucher la terre, regarder le ciel, moment de chakra et pause des réseaux sociaux." },
    { term: "Clôture du Soir", desc: "Un rituel pour clore consciemment la journée. Tire ton résumé de conscience avec les questions « Qu'as-tu appris aujourd'hui ? » et « Gratitude ? »." },
    { term: "Carte Intérieure Hebdomadaire", desc: "Écran récapitulatif qui montre les statistiques de la semaine : chakra le plus actif, total des respirations, mots d'intention et moments conscients. Le rapport IA en crée une synthèse hebdomadaire." },
    { term: "Profil de Naissance", desc: "Ta carte énergétique personnelle calculée à partir de ta date et heure de naissance : signe solaire, chemin de vie, année personnelle, ascendant, analyse de la 12e maison et graphique hebdomadaire du biorythme." },
    { term: "Fréquences Solfeggio", desc: "Les six tons de base utilisés dans Sakin (396, 417, 528, 639, 741 et 852 Hz) ainsi que 963 Hz pour le chakra couronne. Chaque fréquence correspond à un chakra. Ce n'est pas un traitement, mais un ancrage sonore qui aide à rassembler l'attention dans le corps." },
    { term: "Connexion et série de jours", desc: "Lorsque tu termines les 7 étapes de la journée (matin, tâches du jour, souffle, son, chakra, soir et miroir), la connexion s'active et la colonne des chakras devient un tunnel de lumière. Les jours consécutifs font grandir la série : au bout de 7 jours, niveau 2 (x2) ; au bout de 21 jours, niveau 3 (x4)." },
    { term: "Rapport du ciel", desc: "Un résumé collectif quotidien qui réunit la phase de la Lune, les éruptions solaires, l'activité géomagnétique (indice Kp), le vent solaire et les pluies de météores. Les données proviennent du service ouvert de météorologie de l'espace de la NOAA ; l'interprétation est la même pour tout le monde." },
    { term: "Identité galactique", desc: "Une carte personnelle partageable, générée à partir de tes données de naissance. Elle réunit en une seule image ton signe, ton ascendant, ton nombre de chemin de vie et ta répartition des éléments." },
    { term: "Répartition des éléments", desc: "La répartition des planètes de ton thème natal entre le feu, la terre, l'air et l'eau. Le Soleil et la Lune pèsent davantage. L'élément dominant montre ton penchant naturel, le plus faible le domaine à nourrir consciemment." },
    { term: "Vider l'esprit (kaléidoscope)", desc: "Un espace de repos visuel et sonore en plein écran, avec quatre modes (calme, clarté, abandon, ampleur). Les motifs et les sons sont générés sur le moment ; ce ne sont pas des enregistrements et cela coule différemment à chaque fois." },
    { term: "Bouton panique", desc: "Conçu pour les moments d'angoisse soudaine, avec un accès rapide. Il te conduit directement au mode de respiration 4-7-8. Ce rythme allonge l'expiration et soutient le système nerveux parasympathique. Ce n'est pas une intervention médicale ; en cas d'urgence, appelle le numéro d'urgence de ton pays." },
  ]},
];

const JA = [
  { cat: "guide_cat_numerology", items: [
    { term: "ライフパスナンバー", desc: "生年月日のすべての数字を一桁に還元して求める個人の数字（または11, 22, 33のマスターナンバー）。人生の目的、生まれ持った才能、そして人生の旅の中核となるエネルギーを表します。", examples: [
      { num: "1", meaning: "リーダー、独立、開拓者。自分の道を切り開く勇敢で決断力のあるエネルギー。" },
      { num: "2", meaning: "外交官、調和的、繊細。協力的で直感的、調和を求めるエネルギー。" },
      { num: "3", meaning: "創造的、表現豊か、喜びにあふれる。芸術、コミュニケーション、社会的つながりのエネルギー。" },
      { num: "4", meaning: "建設者、規律正しい、信頼できる。秩序、安定、堅固な土台のエネルギー。" },
      { num: "5", meaning: "自由な魂、冒険好き、変化を好む。自由、旅、経験のエネルギー。" },
      { num: "6", meaning: "世話人、責任感、調和的。家族、家庭、共同体のエネルギー。" },
      { num: "7", meaning: "探求者、神秘的、内省的。霊性、分析、深い思考のエネルギー。" },
      { num: "8", meaning: "力強い、野心的、成功者。物質的豊かさ、権威、達成のエネルギー。" },
      { num: "9", meaning: "人道的、賢い、完了させる存在。普遍的な愛、慈悲、手放しのエネルギー。" },
      { num: "11", meaning: "マスターナンバー：直感的な啓発者。高い気づきと霊的な教えのエネルギー。" },
      { num: "22", meaning: "マスターナンバー：偉大な建設者。壮大なビジョンを現実に変える力。" },
      { num: "33", meaning: "マスターナンバー：偉大な教師。無条件の愛、癒し、普遍的な奉仕。" },
    ]},
    { term: "パーソナルイヤーナンバー", desc: "生まれた日と月、そして現在の年の数字を足し合わせて計算します。1〜9の循環するエネルギーマップを示し、毎年異なるテーマとエネルギーをもたらします。" },
    { term: "還元", desc: "数秘術で複数桁の数字を一桁に減らす作業。すべての桁を足し、結果が9より大きければ再び足します。11, 22, 33は「マスターナンバー」として還元されず、特別な意味を保ちます。" },
  ]},
  { cat: "guide_cat_astrology", items: [
    { term: "太陽星座", desc: "誕生時に太陽がいた星座。中核の人格、自我、生命エネルギーを表します。12の星座があります：牡羊座、牡牛座、双子座、蟹座、獅子座、乙女座、天秤座、蠍座、射手座、山羊座、水瓶座、魚座。" },
    { term: "アセンダント（上昇星座）", desc: "生まれた瞬間に地平線から昇っていた星座。世界からどう見られるか、外見、第一印象を決定します。計算には出生時刻が必要です。" },
    { term: "第12ハウスと支配星", desc: "占星術で第12ハウスは無意識、隠れた力、霊的な可能性、内なる世界を表します。各ハウスには支配星があり、そのテーマをどう体験するかを決めます。" },
    { term: "ドラコニックチャート", desc: "ネイタルチャートは「あなたが誰か」を語り、ドラコニックチャートはこの身体に入る前の魂の姿を語ります。北のノードを牡羊座0°に固定して計算します。1970年代にパメラ・クレインとロナルド・デイヴィソンによって体系化されました。ドラコニックの太陽は魂の真の正体、ネイタルの太陽はこの人生でまとっている仮面です。" },
    { term: "惑星の力", desc: "各惑星は人生の異なる領域を司ります：太陽（自己）、月（感情）、水星（コミュニケーション）、金星（愛）、火星（行動）、木星（拡大）、土星（規律）、天王星（独自性）、海王星（想像力）、冥王星（変容）。" },
    { term: "ノースノードとサウスノード", desc: "月の軌道が黄道と交わる二つの点で、天体そのものではなく数学的な交点です。サウスノードは過去から持ち越した、居心地はよいけれど成長をもたらさないパターンを、ノースノードはこの人生で向かうべき、はじめは負荷に感じられる方向を表します。" },
    { term: "逆行（レトログラード）", desc: "地球から見ると惑星が後戻りしているように見える現象です。実際に戻っているわけではなく、二つの惑星の速度差から生まれる見かけ上の錯覚です。占星術では、見直し・完了・内省の時期として読まれます。" },
    { term: "トランジット（経過）", desc: "現在の惑星の位置と、あなたの出生図の各点とが結ぶ角度の関係です。Sakin の空のレポートにあるトランジットの記述は個人的なものではなく集合的なもので、その日の同じ空をすべての人に向けて語ります。" },
    { term: "月の満ち欠け", desc: "太陽に対する月の位置から生まれる明るさの周期で、およそ29.5日で一巡します。新月は意図の種まきに、満月は見えるようにすることと手放すことに結びつけられます。" },
  ]},
  { cat: "guide_cat_chakra", items: [
    { term: "チャクラとは？", desc: "サンスクリット語で「車輪」を意味します。身体のエネルギーセンター。7つの主要チャクラが背骨に沿って並び、それぞれ異なる身体的、感情的、霊的な領域を司ります。" },
    { term: "1. ルートチャクラ（ムーラダーラ）", desc: "位置：背骨の根元。色：赤。元素：地。意味：安全、生存、基本的欲求、グラウンディング。" },
    { term: "2. サクラルチャクラ（スワディスターナ）", desc: "位置：へその下。色：橙。元素：水。意味：創造性、感情、性、喜び。" },
    { term: "3. ソーラープレクサスチャクラ（マニプーラ）", desc: "位置：胃のあたり。色：黄。元素：火。意味：自信、意志の力、個人の力。" },
    { term: "4. ハートチャクラ（アナーハタ）", desc: "位置：胸の中心。色：緑。元素：風。意味：愛、慈悲、許し、関係性。" },
    { term: "5. スロートチャクラ（ヴィシュッダ）", desc: "位置：喉。色：青。元素：音。意味：コミュニケーション、自己表現、真実。" },
    { term: "6. サードアイチャクラ（アジナ）", desc: "位置：眉間。色：藍。元素：光。意味：直感、洞察、想像力、知恵。" },
    { term: "7. クラウンチャクラ（サハスラーラ）", desc: "位置：頭頂。色：紫／白。元素：宇宙。意味：宇宙とのつながり、悟り。" },
    { term: "22チャクラシステム", desc: "7つの主要チャクラを超え、アーススター、ソウル、胸腺、オリオン、ソウルスターなど15のエネルギーセンターがあり、拡張レイキ療法で用いられます。" },
  ]},
  { cat: "guide_cat_biorhythm", items: [
    { term: "バイオリズムとは？", desc: "生年月日から始まる3つの周期的な生物学的リズム。それぞれが正弦波として正負の間を揺れ、値は-100から+100の範囲を取ります。" },
    { term: "身体バイオリズム（23日）", desc: "身体のエネルギー、力、持久力、協調性を反映します。正のとき＝高エネルギー、負のとき＝休息が必要。" },
    { term: "感情バイオリズム（28日）", desc: "感情の安定、気分、創造性、直感を反映します。正＝楽観的、負＝繊細で内向的。" },
    { term: "知性バイオリズム（33日）", desc: "知的鋭敏さ、集中、記憶、分析的思考を反映します。正＝活発、負＝集中しづらい。" },
  ]},
  { cat: "guide_cat_reiki", items: [
    { term: "レイキとは？", desc: "「宇宙の生命エネルギー」を意味する日本発祥のエネルギーヒーリング法。エネルギーセンター（チャクラ）に手を当て、身体本来の癒しを促します。医療行為ではなく、補完的なウェルネスの実践です。" },
    { term: "チャクラ療法", desc: "Sakinの60秒セッションでは、選んだチャクラに手を当て、目を閉じ、呼吸することで、そのエネルギーセンターと結びつきます。" },
    { term: "癒しの探求", desc: "レイキの智慧、ルイーズ・ヘイの心と感情の原因マップ、チャクラ理論を組み合わせた、AIによるパーソナライズされた洞察ツール。" },
    { term: "ルイーズ・ヘイの方法", desc: "身体の不調の背後にある心と感情の原因を探るアプローチ。例：頭痛は「自己否定」、腰痛は「感情的サポートの欠如」と関連づけられます。" },
    { term: "内なる鏡", desc: "身体の不調や感情の状態を書き出すことで、内側の原因を発見できるAI分析ツール。" },
  ]},
  { cat: "guide_cat_app", items: [
    { term: "朝の意図", desc: "毎日を意識的な意図と共に始める実践。短い文または一語で、その日の焦点を定めます。" },
    { term: "3つの言葉の選択", desc: "12の力ある言葉（平和、流れ、勇気、忍耐、明晰、愛、強さ、調和、自由、喜び、感謝、信頼）から3つを選び、その日のエネルギーの方向を定めます。" },
    { term: "呼吸法（4-1.5-3.5）", desc: "吸う(4秒) → 止める(1.5秒) → 吐く(3.5秒) → 休む。副交感神経を活性化し、ストレスを減らし、集中を高めます。" },
    { term: "日中のリマインダー", desc: "一日を通じた10のマイクロ実践：鏡を見る、水を飲む、呼吸の気づき、身体の運動、太陽を感じる、木を抱く、土に触れる、空を見る、チャクラの瞬間、SNS休憩。" },
    { term: "夜の締めくくり", desc: "一日を意識的に閉じる儀式。「今日何を学んだ？」と「感謝？」の問いで、その日の気づきの要約を引き出します。" },
    { term: "週の内なる地図", desc: "週の統計を示す要約画面：最もアクティブなチャクラ、呼吸の合計、意図の言葉、意識的な瞬間。AIレポートがこれらのデータから週の洞察を生成します。" },
    { term: "出生プロファイル", desc: "生年月日時から計算される個人のエネルギーマップ：星座、ライフパスナンバー、パーソナルイヤー、アセンダント、第12ハウス分析、週ごとのバイオリズムグラフ。" },
    { term: "ソルフェジオ周波数", desc: "Sakin で使う六つの基本音（396・417・528・639・741・852 Hz）と、クラウンチャクラのための 963 Hz。各周波数はひとつのチャクラに対応します。治療法ではなく、注意を体に集める助けとなる音の錨です。" },
    { term: "つながりと連続日数", desc: "一日の7つのステップ（朝、日中の小さな課題、呼吸、音、チャクラ、夜、鏡）を終えるとつながりが灯り、チャクラの柱が光のトンネルに変わります。続けた日数が連続記録を育てます。7日で第2段階（x2）、21日で第3段階（x4）。" },
    { term: "空のレポート", desc: "月の満ち欠け、太陽フレア、地磁気の活動（Kp指数）、太陽風、流星群をまとめた、その日の集合的な要約です。データは NOAA の公開宇宙天気サービスに由来し、解釈はすべての人に共通です。" },
    { term: "ギャラクティック・アイデンティティ", desc: "生まれた情報から作られる、共有できる個人カード。星座、上昇星座、ライフパスナンバー、エレメント配分をひとつの図にまとめます。" },
    { term: "エレメント配分", desc: "出生図の惑星が火・地・風・水のどこに分かれているかを示します。太陽と月は重みが大きくなります。優勢なエレメントは生まれ持った傾きを、もっとも弱いエレメントは意識して育てたい領域を教えてくれます。" },
    { term: "心を空にする（万華鏡）", desc: "四つのモード（静けさ、明晰さ、ゆだねること、広がり）を備えた全画面の視聴覚的な休息空間です。模様も音もその場で生成され、録音ではないため毎回ちがう流れになります。" },
    { term: "パニックボタン", desc: "突然の不安に素早く手が届くように用意されています。押すとそのまま 4-7-8 の呼吸モードに入ります。このリズムは吐く息を長くし、副交感神経のはたらきを支えます。医療行為ではありません。緊急時はお住まいの地域の救急番号に連絡してください。" },
  ]},
];

export const GLOSSARY_BY_LANG = {
  tr: TR,
  en: EN,
  de: DE,
  es: ES,
  pt: PT,
  fr: FR,
  ja: JA,
};

// Dile göre glossary döndür; bilinmeyen dilde EN fallback.
// "Yıldız Tohumları" kategorisi ayrı dosyada (glossary-starseed.js), en sona eklenir.
export function getGlossary(lang) {
  const base = GLOSSARY_BY_LANG[lang] || EN;
  const star = STARSEED_BY_LANG[lang] || STARSEED_BY_LANG.en;
  return [...base, { cat: "guide_cat_starseed", items: star }];
}
