// ── SAKİN ODALAR: içerik (1.4.3) ─────────────────────────────────────────────
// Kaynak: kullanıcının diğer projesi Kozmik Gemi'nin "Gemi Odaları" (kozmikgemi.
// netlify.app, data.js), Sakin'in ruhuna uyarlandı:
//  - Doğrulanamayan sağlık/bilim iddiaları ÇIKARILDI ("bağışıklığı %30 güçlendirir",
//    "528 Hz DNA onarır", "45 dk = 4 saat uyku", "titreme = saatlerce terapi"):
//    App Store 1.4.1 sağlık iddiası riski + Sakin gelenek anlatısını "anlatılır" diye
//    yazar, bilim gibi değil.
//  - Kozmik Gemi'deki rehber adları/telefonları/adresleri ve etkinlikler KOPYALANMADI
//    (örnek veri gibi duruyor; gerçekmiş gibi göstermek yanıltıcı olurdu). Rehberler ve
//    etkinlikler yönetim panelinden girilir (netlify/functions/rooms-admin.mjs).
//  - Her oda Sakin'deki bir pratiğe bağlanır (`practice`): odayı okuyan kişi o frekansı
//    uygulamada hemen deneyebilir. Orkestra metaforu: her oda bir enstrüman.
//  - Tantra yalnızca 18 yaş ve üzeri (doğum tarihinden) görünür (`minAge`).
// Metinler 7 dil. Uzun gövde (hero/teachings) tr + en asıl, diğer diller çeviri.

export const ROOMS_MOTTO = {
  tr: "Evren bir orkestradır. Senin sessizliğin bile bir nota.",
  en: "The universe is an orchestra. Even your silence is a note.",
  de: "Das Universum ist ein Orchester. Selbst deine Stille ist ein Ton.",
  es: "El universo es una orquesta. Incluso tu silencio es una nota.",
  pt: "O universo é uma orquestra. Até o teu silêncio é uma nota.",
  fr: "L'univers est un orchestre. Même ton silence est une note.",
  ja: "宇宙はオーケストラ。あなたの沈黙さえ、ひとつの音。",
};

export const ROOMS = [
  {
    id: "reiki", ico: "✋", freq: "7.83 Hz · Schumann", hue: ["#c8a2ff", "#5ad9ff"], practice: "chakra",
    title:   { tr:"Reiki Odası", en:"Reiki Room", de:"Reiki-Raum", es:"Sala de Reiki", pt:"Sala de Reiki", fr:"Salle de Reiki", ja:"レイキの部屋" },
    tagline: { tr:"Evrensel yaşam enerjisinin avuçlarındaki dansı.", en:"The dance of universal life energy in your palms.", de:"Der Tanz der universellen Lebensenergie in deinen Händen.", es:"La danza de la energía vital universal en tus manos.", pt:"A dança da energia vital universal nas tuas mãos.", fr:"La danse de l'énergie vitale universelle dans tes paumes.", ja:"手のひらで踊る、宇宙の生命エネルギー。" },
    hero: {
      tr:"Reiki, Japoncada \"rei\" (evrensel) ve \"ki\" (yaşam enerjisi) sözcüklerinden gelir. Mikao Usui'nin 1922'de Kurama Dağı'ndaki 21 günlük inzivasında yeniden hatırladığı anlatılan, ellerle yapılan bir dinginlik pratiğidir. Aynı akışın Tibet'te, eski Mısır'da ve Hint prana öğretisinde farklı adlarla anıldığı söylenir.",
      en:"Reiki comes from the Japanese \"rei\" (universal) and \"ki\" (life energy). It is a hands-on practice of stillness that Mikao Usui is said to have remembered during a 21-day retreat on Mount Kurama in 1922. The same flow is said to appear under other names in Tibet, ancient Egypt and the Indian teaching of prana.",
      de:"Reiki kommt aus dem Japanischen: „rei“ (universell) und „ki“ (Lebensenergie). Es ist eine Praxis der Stille mit den Händen, an die sich Mikao Usui 1922 während eines 21-tägigen Rückzugs auf dem Berg Kurama erinnert haben soll. Derselbe Fluss soll in Tibet, im alten Ägypten und in der indischen Lehre vom Prana unter anderen Namen bekannt sein.",
      es:"Reiki viene del japonés «rei» (universal) y «ki» (energía vital). Es una práctica de quietud con las manos que, según se cuenta, Mikao Usui recordó durante un retiro de 21 días en el monte Kurama en 1922. Se dice que el mismo flujo aparece con otros nombres en el Tíbet, en el antiguo Egipto y en la enseñanza india del prana.",
      pt:"Reiki vem do japonês «rei» (universal) e «ki» (energia vital). É uma prática de quietude feita com as mãos que, segundo se conta, Mikao Usui recordou durante um retiro de 21 dias no monte Kurama, em 1922. Diz-se que o mesmo fluxo surge com outros nomes no Tibete, no antigo Egito e no ensinamento indiano do prana.",
      fr:"Reiki vient du japonais « rei » (universel) et « ki » (énergie vitale). C'est une pratique de calme par les mains dont Mikao Usui se serait souvenu lors d'une retraite de 21 jours sur le mont Kurama en 1922. On dit que le même flux apparaît sous d'autres noms au Tibet, dans l'Égypte ancienne et dans l'enseignement indien du prana.",
      ja:"レイキは日本語の「霊」（宇宙の）と「気」（生命エネルギー）から来ています。1922年、臼井甕男（Mikao Usui）が鞍馬山での21日間の修行の中で思い出したと伝えられる、手で行う静けさの実践です。同じ流れは、チベットや古代エジプト、インドのプラーナの教えにも、別の名前で現れると言われます。",
    },
    teachings: [
      { h:{ tr:"Kadim kök", en:"Ancient root", de:"Uralte Wurzel", es:"Raíz antigua", pt:"Raiz antiga", fr:"Racine ancienne", ja:"古い根" },
        p:{ tr:"Sanskritçe \"prana\", Çincede \"qi\", Polinezyacada \"mana\": yaşam soluğunun farklı adları. Reiki bu soluğu avuçlardan akan sakin bir dikkat olarak ele alır.", en:"Sanskrit \"prana\", Chinese \"qi\", Polynesian \"mana\": different names for the breath of life. Reiki treats it as a calm attention flowing through the palms.",
          de:"Sanskrit „prana“, Chinesisch „qi“, polynesisch „mana“: verschiedene Namen für den Atem des Lebens. Reiki versteht ihn als ruhige Aufmerksamkeit, die durch die Handflächen fließt.",
          es:"«Prana» en sánscrito, «qi» en chino, «mana» en polinesio: distintos nombres para el aliento de la vida. El Reiki lo entiende como una atención serena que fluye por las palmas.",
          pt:"«Prana» em sânscrito, «qi» em chinês, «mana» em polinésio: nomes diferentes para o sopro da vida. O Reiki trata-o como uma atenção calma que flui pelas palmas das mãos.",
          fr:"« Prana » en sanskrit, « qi » en chinois, « mana » en polynésien : différents noms pour le souffle de vie. Le Reiki le considère comme une attention calme qui s'écoule par les paumes.",
          ja:"サンスクリット語の「プラーナ」、中国語の「気」、ポリネシアの「マナ」。どれも生命の息吹の別の名前です。レイキはそれを、手のひらから流れる静かな意識として扱います。" } },
      { h:{ tr:"Beş ilke (Gokai)", en:"Five principles (Gokai)", de:"Fünf Lebensregeln (Gokai)", es:"Cinco principios (Gokai)", pt:"Cinco princípios (Gokai)", fr:"Cinq principes (Gokai)", ja:"五つの原則（Gokai）" },
        p:{ tr:"Sadece bugün:", en:"Just for today:", de:"Nur für heute:", es:"Solo por hoy:", pt:"Só por hoje:", fr:"Juste pour aujourd'hui :", ja:"今日だけは：" },
        list:{ tr:["Öfkelenmeyeceğim.","Endişelenmeyeceğim.","Şükredeceğim.","İşimi dürüstçe yapacağım.","Tüm canlılara nazik olacağım."], en:["I will not be angry.","I will not worry.","I will be grateful.","I will do my work honestly.","I will be kind to every living thing."],
          de:["Ich ärgere mich nicht.","Ich sorge mich nicht.","Ich bin dankbar.","Ich tue meine Arbeit ehrlich.","Ich bin freundlich zu allen Lebewesen."],
          es:["No me enfadaré.","No me preocuparé.","Daré las gracias.","Haré mi trabajo con honestidad.","Seré amable con todo ser vivo."],
          pt:["Não me vou zangar.","Não me vou preocupar.","Vou agradecer.","Vou fazer o meu trabalho com honestidade.","Vou ser gentil com todos os seres vivos."],
          fr:["Je ne me mettrai pas en colère.","Je ne m'inquiéterai pas.","J'exprimerai ma gratitude.","Je ferai mon travail honnêtement.","Je traiterai tout être vivant avec bonté."],
          ja:["怒らない。","心配しない。","感謝する。","誠実に仕事をする。","すべての生きものにやさしくする。"] } },
      { h:{ tr:"Üç derece", en:"Three degrees", de:"Drei Grade", es:"Tres grados", pt:"Três graus", fr:"Trois degrés", ja:"三つの段階" },
        p:{ tr:"Shoden (1. derece) kendine dokunmayı, Okuden (2. derece) sembollerle çalışmayı, Shinpiden (usta) öğretmeyi kapsar.", en:"Shoden (1st degree) is about touching yourself, Okuden (2nd degree) about working with symbols, Shinpiden (master) about teaching.",
          de:"Bei Shoden (1. Grad) geht es darum, dich selbst zu berühren, bei Okuden (2. Grad) um die Arbeit mit Symbolen, bei Shinpiden (Meister) um das Lehren.",
          es:"Shoden (1.er grado) trata de tocarte a ti, Okuden (2.º grado) de trabajar con símbolos, Shinpiden (maestría) de enseñar.",
          pt:"Shoden (1.º grau) é tocar em ti próprio, Okuden (2.º grau) é trabalhar com símbolos, Shinpiden (mestre) é ensinar.",
          fr:"Shoden (1er degré) consiste à te toucher toi-même, Okuden (2e degré) à travailler avec des symboles, Shinpiden (maître) à enseigner.",
          ja:"Shoden（第1段階）は自分自身に触れること、Okuden（第2段階）はシンボルとともに取り組むこと、Shinpiden（マスター）は教えることです。" } },
      { h:{ tr:"Pratik", en:"Practice", de:"Praxis", es:"Práctica", pt:"Prática", fr:"Pratique", ja:"実践" },
        p:{ tr:"Avuçlar bedenin enerji merkezlerine sırayla konur: taç, üçüncü göz, boğaz, kalp, solar pleksus, sakral, kök. Çoğu kişi bunu derin bir gevşeme olarak anlatır.", en:"The palms rest on the body's energy centres in turn: crown, third eye, throat, heart, solar plexus, sacral, root. Most people describe it as a deep letting go.",
          de:"Die Handflächen ruhen nacheinander auf den Energiezentren des Körpers: Krone, drittes Auge, Kehle, Herz, Solarplexus, Sakral, Wurzel. Die meisten Menschen beschreiben es als tiefes Loslassen.",
          es:"Las palmas se posan por turnos sobre los centros de energía del cuerpo: corona, tercer ojo, garganta, corazón, plexo solar, sacro, raíz. La mayoría lo describe como un profundo soltar.",
          pt:"As palmas pousam, à vez, sobre os centros de energia do corpo: coroa, terceiro olho, garganta, coração, plexo solar, sacro, raiz. A maioria das pessoas descreve-o como um profundo deixar ir.",
          fr:"Les paumes se posent tour à tour sur les centres d'énergie du corps : couronne, troisième œil, gorge, cœur, plexus solaire, sacré, racine. La plupart des gens le décrivent comme un profond lâcher-prise.",
          ja:"手のひらを、からだのエネルギーセンターに順番に置いていきます。頭頂、第三の目、喉、ハート、みぞおち、仙骨、ルート。多くの人は、それを深く手放していく感覚だと語ります。" } },
    ],
  },
  {
    id: "kundalini", ico: "🐍", freq: "Mool Mantra", hue: ["#ff9ec7", "#ffd28a"], practice: "nefes",
    title:   { tr:"Kundalini Yoga", en:"Kundalini Yoga", de:"Kundalini Yoga", es:"Kundalini Yoga", pt:"Kundalini Yoga", fr:"Kundalini Yoga", ja:"クンダリーニ・ヨガ" },
    tagline: { tr:"Omurganda kıvrılan ışık yılanını uyandır.", en:"Wake the coiled serpent of light along your spine.", de:"Wecke die zusammengerollte Lichtschlange entlang deiner Wirbelsäule.", es:"Despierta la serpiente de luz enroscada en tu columna.", pt:"Desperta a serpente de luz enrolada na tua coluna.", fr:"Éveille le serpent de lumière lové le long de ta colonne.", ja:"背骨に眠る光の蛇を目覚めさせる。" },
    hero: {
      tr:"Kundalini, Sanskritçe \"kıvrılmış\" demektir. Kök çakranın derinliğinde uyuduğu anlatılan canlılık gücüdür; tantra geleneğinde Shakti olarak bilinir. Nefes, mantra, beden kilitleri (bandha) ve mudralarla yukarı yükseltildiğine inanılır. Yogi Bhajan 1968'de Batı'da açıkça öğretmeden önce kapalı kapılar ardında aktarılırdı.",
      en:"Kundalini means \"coiled\" in Sanskrit. It is described as a vital force sleeping at the base of the spine, known as Shakti in the tantric tradition, and believed to rise through breath, mantra, body locks (bandha) and mudras. Before Yogi Bhajan taught it openly in the West in 1968, it was passed on behind closed doors.",
      de:"Kundalini bedeutet auf Sanskrit „zusammengerollt“. Sie wird als Lebenskraft beschrieben, die an der Basis der Wirbelsäule schläft, in der tantrischen Tradition als Shakti bekannt, und man glaubt, dass sie durch Atem, Mantra, Körperverschlüsse (bandha) und Mudras aufsteigt. Bevor Yogi Bhajan sie 1968 im Westen offen lehrte, wurde sie hinter verschlossenen Türen weitergegeben.",
      es:"Kundalini significa «enroscada» en sánscrito. Se describe como una fuerza vital que duerme en la base de la columna, conocida como Shakti en la tradición tántrica, y se cree que asciende a través de la respiración, el mantra, los cierres corporales (bandha) y los mudras. Antes de que Yogi Bhajan la enseñara abiertamente en Occidente en 1968, se transmitía a puerta cerrada.",
      pt:"Kundalini significa «enrolada» em sânscrito. É descrita como uma força vital que dorme na base da coluna, conhecida como Shakti na tradição tântrica, e acredita-se que sobe através da respiração, do mantra, dos fechos corporais (bandha) e dos mudras. Antes de Yogi Bhajan a ensinar abertamente no Ocidente, em 1968, era transmitida à porta fechada.",
      fr:"Kundalini signifie « enroulée » en sanskrit. On la décrit comme une force vitale endormie à la base de la colonne, connue sous le nom de Shakti dans la tradition tantrique, et l'on croit qu'elle s'élève par le souffle, le mantra, les verrous corporels (bandha) et les mudras. Avant que Yogi Bhajan ne l'enseigne ouvertement en Occident en 1968, elle se transmettait à huis clos.",
      ja:"クンダリーニはサンスクリット語で「とぐろを巻いたもの」という意味です。背骨の根元で眠る生命力として語られ、タントラの伝統ではShaktiとして知られています。呼吸、マントラ、からだのロック（bandha）、ムドラーによって上昇すると信じられています。1968年にYogi Bhajanが西洋で公に教えるまで、閉ざされた扉の向こうで伝えられていました。",
    },
    teachings: [
      { h:{ tr:"Yedi çakra", en:"Seven chakras", de:"Sieben Chakren", es:"Siete chakras", pt:"Sete chakras", fr:"Sept chakras", ja:"七つのチャクラ" },
        p:{ tr:"Kök, sakral, solar pleksus, kalp, boğaz, üçüncü göz, taç. Kundalini'nin bu sütun boyunca yükseldiği anlatılır.", en:"Root, sacral, solar plexus, heart, throat, third eye, crown. Kundalini is said to rise along this column.",
          de:"Wurzel, Sakral, Solarplexus, Herz, Kehle, drittes Auge, Krone. Es heißt, dass Kundalini entlang dieser Säule aufsteigt.",
          es:"Raíz, sacro, plexo solar, corazón, garganta, tercer ojo, corona. Se dice que la Kundalini asciende a lo largo de esta columna.",
          pt:"Raiz, sacro, plexo solar, coração, garganta, terceiro olho, coroa. Diz-se que a Kundalini sobe ao longo desta coluna.",
          fr:"Racine, sacré, plexus solaire, cœur, gorge, troisième œil, couronne. On dit que la Kundalini s'élève le long de cette colonne.",
          ja:"ルート、仙骨、みぞおち、ハート、喉、第三の目、頭頂。クンダリーニはこの柱に沿って上昇すると言われます。" } },
      { h:{ tr:"Ateş nefesi", en:"Breath of fire", de:"Feueratem", es:"Respiración de fuego", pt:"Respiração de fogo", fr:"Souffle de feu", ja:"火の呼吸" },
        p:{ tr:"Burundan ritmik, hızlı ve eşit nefes; karın körük gibi çalışır. Birkaç nefesle başla, başın dönerse hemen normal nefese dön. Hamilelikte ve tansiyon sorunlarında önerilmez.", en:"Rhythmic, quick, even breathing through the nose, the belly working like bellows. Start with a few breaths and return to normal breathing if you feel dizzy. Not advised in pregnancy or with blood pressure issues.",
          de:"Rhythmisches, schnelles, gleichmäßiges Atmen durch die Nase, der Bauch arbeitet wie ein Blasebalg. Beginne mit wenigen Atemzügen und kehre zur normalen Atmung zurück, wenn dir schwindelig wird. Nicht empfohlen in der Schwangerschaft oder bei Blutdruckproblemen.",
          es:"Respiración rítmica, rápida y regular por la nariz, con el vientre trabajando como un fuelle. Empieza con unas pocas respiraciones y vuelve a respirar con normalidad si te mareas. No se recomienda durante el embarazo ni si tienes problemas de tensión arterial.",
          pt:"Respiração rítmica, rápida e regular pelo nariz, com a barriga a trabalhar como um fole. Começa com poucas respirações e volta à respiração normal se sentires tonturas. Não é aconselhada na gravidez nem com problemas de tensão arterial.",
          fr:"Respiration rythmée, rapide et régulière par le nez, le ventre travaillant comme un soufflet. Commence par quelques respirations et reviens à une respiration normale si la tête te tourne. Déconseillé pendant la grossesse ou en cas de problèmes de tension artérielle.",
          ja:"鼻から、リズミカルに速く均一に呼吸します。お腹はふいごのように動きます。数回から始め、めまいを感じたら普段の呼吸に戻りましょう。妊娠中や血圧に不安がある方にはおすすめしません。" } },
      { h:{ tr:"Kriya", en:"Kriya", de:"Kriya", es:"Kriya", pt:"Kriya", fr:"Kriya", ja:"Kriya" },
        p:{ tr:"Bir kriya; nefes, hareket, mantra ve odaktan oluşan tam bir diziliştir. Sat Kriya en temel olanıdır:", en:"A kriya is a full sequence of breath, movement, mantra and focus. Sat Kriya is the most basic one:",
          de:"Eine Kriya ist eine vollständige Abfolge aus Atem, Bewegung, Mantra und Fokus. Sat Kriya ist die grundlegendste:",
          es:"Una kriya es una secuencia completa de respiración, movimiento, mantra y enfoque. Sat Kriya es la más básica:",
          pt:"Uma kriya é uma sequência completa de respiração, movimento, mantra e foco. A Sat Kriya é a mais básica:",
          fr:"Une kriya est une séquence complète de souffle, de mouvement, de mantra et de concentration. Sat Kriya est la plus fondamentale :",
          ja:"Kriyaとは、呼吸・動き・マントラ・集中からなる、ひとまとまりの流れです。もっとも基本的なのがSat Kriyaです：" },
        list:{ tr:["Dik otur, eller başın üzerinde kenetli","İşaret parmakları yukarı","\"Sat\" derken göbeği hafifçe içeri çek, \"Nam\" derken bırak","Kısa başla, bedenin istediği kadar sür"], en:["Sit tall, hands clasped above your head","Index fingers pointing up","Gently draw the navel in on \"Sat\", release on \"Nam\"","Start short and continue as long as your body wants"],
          de:["Setz dich aufrecht hin, die Hände über dem Kopf verschränkt","Die Zeigefinger zeigen nach oben","Zieh bei „Sat“ den Nabel sanft nach innen, lass bei „Nam“ los","Beginne kurz und mach so lange weiter, wie dein Körper möchte"],
          es:["Siéntate con la espalda recta y las manos entrelazadas sobre la cabeza","Los índices apuntan hacia arriba","Al decir «Sat», lleva suavemente el ombligo hacia dentro; suéltalo al decir «Nam»","Empieza con poco tiempo y sigue tanto como tu cuerpo quiera"],
          pt:["Senta-te com as costas direitas e as mãos entrelaçadas acima da cabeça","Os indicadores apontam para cima","Ao dizer «Sat», recolhe suavemente o umbigo; ao dizer «Nam», solta","Começa por pouco tempo e continua enquanto o teu corpo quiser"],
          fr:["Assieds-toi le dos bien droit, les mains jointes au-dessus de la tête","Les index pointés vers le haut","Rentre doucement le nombril sur « Sat », relâche sur « Nam »","Commence court et continue aussi longtemps que ton corps le souhaite"],
          ja:["背すじを伸ばして座り、頭の上で両手を組む","人さし指は上に向ける","「Sat」でおへそをやさしく引き入れ、「Nam」でゆるめる","短く始め、からだが望むだけ続ける"] } },
      { h:{ tr:"Mool Mantra", en:"Mool Mantra", de:"Mool Mantra", es:"Mool Mantra", pt:"Mool Mantra", fr:"Mool Mantra", ja:"Mool Mantra" },
        p:{ tr:"\"Ek Ong Kar Sat Nam...\": yaradan ile öz arasındaki köprü olarak söylenir; sabah üç kez yüksek sesle okunduğunda kalbi hizaladığına inanılır.", en:"\"Ek Ong Kar Sat Nam...\": chanted as a bridge between the creator and the self; three times aloud in the morning is believed to realign the heart.",
          de:"„Ek Ong Kar Sat Nam...“: gesungen als Brücke zwischen dem Schöpfer und dem Selbst; man glaubt, dass es das Herz neu ausrichtet, wenn man es morgens dreimal laut singt.",
          es:"«Ek Ong Kar Sat Nam...»: se canta como un puente entre el creador y el ser; se cree que recitarlo tres veces en voz alta por la mañana realinea el corazón.",
          pt:"«Ek Ong Kar Sat Nam...»: entoado como uma ponte entre o criador e o ser; acredita-se que, dito três vezes em voz alta de manhã, realinha o coração.",
          fr:"« Ek Ong Kar Sat Nam... » : chanté comme un pont entre le créateur et le soi ; on croit que le réciter trois fois à voix haute le matin réaligne le cœur.",
          ja:"「Ek Ong Kar Sat Nam...」：創造主と自己をつなぐ橋として唱えられます。朝に三回声に出して唱えると、心が整い直すと信じられています。" } },
    ],
  },
  {
    id: "ses", ico: "🎵", freq: "432 / 528 Hz", hue: ["#5ad9ff", "#b8a2ff"], practice: "ses",
    title:   { tr:"Ses Şifası", en:"Sound Healing", de:"Klangheilung", es:"Sanación con sonido", pt:"Cura pelo som", fr:"Guérison par le son", ja:"音の癒やし" },
    tagline: { tr:"Frekans, hücrenin anadilidir.", en:"Frequency is the mother tongue of the cell.", de:"Frequenz ist die Muttersprache der Zelle.", es:"La frecuencia es la lengua materna de la célula.", pt:"A frequência é a língua materna da célula.", fr:"La fréquence est la langue maternelle de la cellule.", ja:"周波数は、細胞の母語。" },
    hero: {
      tr:"Ses şifası, evrenin titreşimsel doğasına dayanan kadim bir anlatıdır. Pisagor gezegenlerin müziğinden (musica universalis) söz etti; Tibet'te yedi metalden çanaklar döküldü; Aborjinler didgeridoo ile rüya zamanını çağırdı. Bugün de pek çok kişi sesle derin bir dinginliğe iner.",
      en:"Sound healing is an ancient story built on the vibrational nature of the universe. Pythagoras spoke of the music of the spheres (musica universalis); bowls were cast from seven metals in Tibet; Aboriginal peoples called the dreamtime with the didgeridoo. Many people still drop into deep calm through sound.",
      de:"Klangheilung ist eine uralte Erzählung, die auf der schwingenden Natur des Universums beruht. Pythagoras sprach von der Musik der Sphären (musica universalis); in Tibet wurden Klangschalen aus sieben Metallen gegossen; die Aborigines riefen mit dem Didgeridoo die Traumzeit herbei. Noch heute finden viele Menschen durch Klang in eine tiefe Ruhe.",
      es:"La sanación con sonido es un relato antiguo basado en la naturaleza vibratoria del universo. Pitágoras habló de la música de las esferas (musica universalis); en el Tíbet se fundían cuencos con siete metales; los pueblos aborígenes llamaban al tiempo del sueño con el didgeridoo. Todavía hoy muchas personas se sumergen en una calma profunda a través del sonido.",
      pt:"A cura pelo som é uma narrativa antiga assente na natureza vibratória do universo. Pitágoras falou da música das esferas (musica universalis); no Tibete fundiam-se taças de sete metais; os povos aborígenes invocavam o tempo do sonho com o didgeridoo. Ainda hoje muitas pessoas mergulham numa calma profunda através do som.",
      fr:"La guérison par le son est un récit ancien fondé sur la nature vibratoire de l'univers. Pythagore parlait de la musique des sphères (musica universalis) ; au Tibet, on coulait des bols dans sept métaux ; les peuples aborigènes appelaient le temps du rêve avec le didgeridoo. Aujourd'hui encore, beaucoup de personnes glissent dans un calme profond grâce au son.",
      ja:"音の癒やしは、宇宙が振動でできているという古い物語に根ざしています。ピタゴラスは天球の音楽（musica universalis）を語り、チベットでは七つの金属からボウルが鋳造され、アボリジニの人々はディジュリドゥでドリームタイムを呼び起こしました。いまも多くの人が、音を通して深い静けさへと降りていきます。",
    },
    teachings: [
      { h:{ tr:"Solfej frekansları", en:"Solfeggio frequencies", de:"Solfeggio-Frequenzen", es:"Frecuencias Solfeggio", pt:"Frequências Solfeggio", fr:"Fréquences Solfeggio", ja:"ソルフェジオ周波数" },
        p:{ tr:"174, 285, 396, 417, 528, 639, 741, 852, 963 Hz. Gelenekte her birinin ayrı bir kapıyı açtığı anlatılır. Sakin'in Ses ekranında hepsi var.", en:"174, 285, 396, 417, 528, 639, 741, 852, 963 Hz. Tradition says each one opens a different door. They are all in Sakin's Sound screen.",
          de:"174, 285, 396, 417, 528, 639, 741, 852, 963 Hz. Die Überlieferung sagt, dass jede eine andere Tür öffnet. Du findest sie alle in Sakin unter „Klang“.",
          es:"174, 285, 396, 417, 528, 639, 741, 852, 963 Hz. Según la tradición, cada una abre una puerta distinta. Todas están en la pantalla Sonido de Sakin.",
          pt:"174, 285, 396, 417, 528, 639, 741, 852, 963 Hz. A tradição diz que cada uma abre uma porta diferente. Estão todas no ecrã Som da Sakin.",
          fr:"174, 285, 396, 417, 528, 639, 741, 852, 963 Hz. La tradition dit que chacune ouvre une porte différente. Elles sont toutes dans l'écran Son de Sakin.",
          ja:"174、285、396、417、528、639、741、852、963 Hz。伝統では、それぞれが異なる扉を開くと言われます。Sakinの「音」画面にすべてそろっています。" } },
      { h:{ tr:"Tibet çanakları", en:"Tibetan bowls", de:"Tibetische Klangschalen", es:"Cuencos tibetanos", pt:"Taças tibetanas", fr:"Bols tibétains", ja:"チベタンボウル" },
        p:{ tr:"Yedi metalden döküldüğü anlatılır: altın (Güneş), gümüş (Ay), cıva (Merkür), bakır (Venüs), demir (Mars), kalay (Jüpiter), kurşun (Satürn). Her gezegen bir nota.", en:"Said to be cast from seven metals: gold (Sun), silver (Moon), mercury (Mercury), copper (Venus), iron (Mars), tin (Jupiter), lead (Saturn). Each planet a note.",
          de:"Sie sollen aus sieben Metallen gegossen sein: Gold (Sonne), Silber (Mond), Quecksilber (Merkur), Kupfer (Venus), Eisen (Mars), Zinn (Jupiter), Blei (Saturn). Jeder Planet ein Ton.",
          es:"Se dice que se funden con siete metales: oro (Sol), plata (Luna), mercurio (Mercurio), cobre (Venus), hierro (Marte), estaño (Júpiter), plomo (Saturno). Cada planeta, una nota.",
          pt:"Diz-se que são fundidas em sete metais: ouro (Sol), prata (Lua), mercúrio (Mercúrio), cobre (Vénus), ferro (Marte), estanho (Júpiter), chumbo (Saturno). Cada planeta, uma nota.",
          fr:"On dit qu'ils sont coulés dans sept métaux : or (Soleil), argent (Lune), mercure (Mercure), cuivre (Vénus), fer (Mars), étain (Jupiter), plomb (Saturne). Chaque planète, une note.",
          ja:"七つの金属から鋳造されると言われます。金（太陽）、銀（月）、水銀（水星）、銅（金星）、鉄（火星）、錫（木星）、鉛（土星）。惑星ひとつひとつが、ひとつの音です。" } },
      { h:{ tr:"Gong banyosu", en:"Gong bath", de:"Gongbad", es:"Baño de gong", pt:"Banho de gongo", fr:"Bain de gong", ja:"ゴングバス" },
        p:{ tr:"Uzanırsın, gözler kapalı; gong dalgaları seni yavaşça içe doğru taşır. Çoğu kişi sonrasında uykuya yakın bir dinginlik anlatır.", en:"You lie down with eyes closed while the gong's waves carry you slowly inward. Many describe a calm close to sleep afterwards.",
          de:"Du liegst mit geschlossenen Augen, während die Wellen des Gongs dich langsam nach innen tragen. Viele beschreiben danach eine Ruhe, die dem Schlaf nahekommt.",
          es:"Te tumbas con los ojos cerrados mientras las ondas del gong te llevan lentamente hacia dentro. Muchas personas describen después una calma cercana al sueño.",
          pt:"Deitas-te de olhos fechados enquanto as ondas do gongo te levam lentamente para dentro. Muitos descrevem depois uma calma próxima do sono.",
          fr:"Tu t'allonges les yeux fermés pendant que les vagues du gong te portent lentement vers l'intérieur. Beaucoup décrivent ensuite un calme proche du sommeil.",
          ja:"目を閉じて横たわると、ゴングの波がゆっくりと内側へ運んでくれます。終わったあと、眠りに近い静けさを感じたと語る人が多くいます。" } },
      { h:{ tr:"Om ile sesleme", en:"Toning with Om", de:"Tönen mit Om", es:"Entonar el Om", pt:"Entoar o Om", fr:"Chanter le Om", ja:"Omの発声" },
        p:{ tr:"\"Om\" evrenin ilk titreşimi olarak anılır. Uzun bir nefes verişiyle, diyaframdan söylenir; nefes vermeyi uzatmak bedeni yavaşlatır.", en:"\"Om\" is honoured as the first vibration of the universe. It is sung from the diaphragm on a long exhale; lengthening the exhale slows the body down.",
          de:"„Om“ wird als erste Schwingung des Universums verehrt. Es wird aus dem Zwerchfell auf einer langen Ausatmung gesungen; eine längere Ausatmung verlangsamt den Körper.",
          es:"El «Om» se honra como la primera vibración del universo. Se canta desde el diafragma en una exhalación larga; alargar la exhalación ralentiza el cuerpo.",
          pt:"O «Om» é honrado como a primeira vibração do universo. Entoa-se a partir do diafragma, numa expiração longa; alongar a expiração abranda o corpo.",
          fr:"Le « Om » est honoré comme la première vibration de l'univers. Il se chante depuis le diaphragme, sur une longue expiration ; allonger l'expiration ralentit le corps.",
          ja:"「Om」は宇宙の最初の振動として大切にされてきました。横隔膜から、長い吐く息にのせて発声します。吐く息を長くすると、からだはゆっくりになります。" } },
    ],
  },
  {
    id: "su", ico: "💧", freq: "H₂O · Hafıza", hue: ["#5ad9ff", "#6fe6c1"], practice: "sabah",
    title:   { tr:"Su Terapisi", en:"Water Therapy", de:"Wassertherapie", es:"Terapia de agua", pt:"Terapia da água", fr:"Thérapie par l'eau", ja:"水のセラピー" },
    tagline: { tr:"Su, niyetin hafızasıdır.", en:"Water is the memory of intention.", de:"Wasser ist das Gedächtnis der Absicht.", es:"El agua es la memoria de la intención.", pt:"A água é a memória da intenção.", fr:"L'eau est la mémoire de l'intention.", ja:"水は、意図の記憶。" },
    hero: {
      tr:"Suyun niyeti taşıdığına dair anlatılar çok eskidir; Masaru Emoto'nun kristal fotoğrafları bu fikri yeniden sevdirdi. Antik Roma hamamlarından Osmanlı hamamına, Kneipp'ten yüzdürme tanklarına kadar insanlar hep suya gevşemek için döndü.",
      en:"Stories that water carries intention are very old; Masaru Emoto's crystal photographs made the idea loved again. From Roman baths to the Ottoman hammam, from Kneipp to floating tanks, people have always returned to water to let go.",
      de:"Erzählungen, dass Wasser Absicht trägt, sind sehr alt; die Kristallfotografien von Masaru Emoto haben die Idee wieder beliebt gemacht. Von römischen Bädern bis zum osmanischen Hammam, von Kneipp bis zu Floating-Tanks sind Menschen immer wieder zum Wasser zurückgekehrt, um loszulassen.",
      es:"Los relatos de que el agua guarda la intención son muy antiguos; las fotografías de cristales de Masaru Emoto hicieron que la idea volviera a ser querida. De los baños romanos al hammam otomano, de Kneipp a los tanques de flotación, las personas siempre han vuelto al agua para soltar.",
      pt:"As histórias de que a água guarda a intenção são muito antigas; as fotografias de cristais de Masaru Emoto voltaram a tornar a ideia querida. Dos banhos romanos ao hammam otomano, de Kneipp aos tanques de flutuação, as pessoas sempre voltaram à água para deixar ir.",
      fr:"Les récits selon lesquels l'eau porte l'intention sont très anciens ; les photographies de cristaux de Masaru Emoto ont fait aimer à nouveau cette idée. Des thermes romains au hammam ottoman, de Kneipp aux caissons de flottaison, les humains sont toujours revenus à l'eau pour lâcher prise.",
      ja:"水が意図を運ぶという物語はとても古く、江本勝（Masaru Emoto）の結晶写真がその考えを再び愛されるものにしました。古代ローマの浴場からオスマンのハマムまで、クナイプ（Kneipp）からフローティングタンクまで、人はいつも手放すために水へと帰ってきました。",
    },
    teachings: [
      { h:{ tr:"Watsu", en:"Watsu", de:"Watsu", es:"Watsu", pt:"Watsu", fr:"Watsu", ja:"Watsu" },
        p:{ tr:"Ilık suda yapılan shiatsu. Destekli yüzdürmeyle beden ağırlığını bırakır; çoğu kişi anne karnı hissinden söz eder.", en:"Shiatsu in warm water. Supported floating lets the body drop its weight; many speak of a feeling like the womb.",
          de:"Shiatsu in warmem Wasser. Getragenes Schweben lässt den Körper sein Gewicht abgeben; viele sprechen von einem Gefühl wie im Mutterleib.",
          es:"Shiatsu en agua templada. La flotación asistida deja que el cuerpo suelte su peso; muchas personas hablan de una sensación como la del vientre materno.",
          pt:"Shiatsu em água morna. A flutuação apoiada deixa o corpo largar o seu peso; muitos falam de uma sensação parecida com a do ventre materno.",
          fr:"Du shiatsu dans une eau tiède. La flottaison soutenue laisse le corps déposer son poids ; beaucoup évoquent une sensation proche du ventre maternel.",
          ja:"温かい水の中で行う指圧です。支えられて浮かぶことで、からだは重さを手放します。母の胎内にいるような感覚だと話す人も多くいます。" } },
      { h:{ tr:"Sıcak ve serin", en:"Warm and cool", de:"Warm und kühl", es:"Templado y fresco", pt:"Morno e fresco", fr:"Chaud et frais", ja:"温かい水と冷たい水" },
        p:{ tr:"Kısa sıcak ve serin su geçişleri geleneksel bir canlanma pratiğidir. Nazik başla, bedenini dinle; sağlık sorunun varsa önce hekimine danış.", en:"Short switches between warm and cool water are a traditional way to feel refreshed. Start gently and listen to your body; if you have a health condition, ask your doctor first.",
          de:"Kurze Wechsel zwischen warmem und kühlem Wasser sind eine traditionelle Art, sich zu erfrischen. Beginne sanft und hör auf deinen Körper; wenn du gesundheitliche Beschwerden hast, frag zuerst deine Ärztin oder deinen Arzt.",
          es:"Los cambios breves entre agua templada y fresca son una forma tradicional de recuperar la frescura. Empieza con suavidad y escucha a tu cuerpo; si tienes algún problema de salud, consulta antes a tu médico.",
          pt:"Alternâncias curtas entre água morna e fresca são uma forma tradicional de te revigorares. Começa com suavidade e ouve o teu corpo; se tens algum problema de saúde, fala primeiro com o teu médico.",
          fr:"De courtes alternances entre eau chaude et eau fraîche sont une façon traditionnelle de retrouver de la fraîcheur. Commence en douceur et écoute ton corps ; si tu as un problème de santé, demande d'abord l'avis de ton médecin.",
          ja:"温かい水と冷たい水を短く切り替えるのは、すっきりするための昔ながらの方法です。やさしく始めて、からだの声を聞きましょう。持病がある場合は、まず医師に相談してください。" } },
      { h:{ tr:"Niyetli su", en:"Water with intention", de:"Wasser mit Absicht", es:"Agua con intención", pt:"Água com intenção", fr:"L'eau et l'intention", ja:"意図をこめた水" },
        p:{ tr:"Bir bardak suyu avuçlarının arasına al, üç nefes boyunca kalbindeki şükranı düşün, sonra yavaşça iç. Küçük, her yerde yapılabilen bir ritüel.", en:"Hold a glass of water between your palms, think of what you're grateful for over three breaths, then drink slowly. A small ritual you can do anywhere.",
          de:"Halte ein Glas Wasser zwischen deinen Handflächen, denk drei Atemzüge lang an etwas, wofür du dankbar bist, und trink dann langsam. Ein kleines Ritual, das du überall machen kannst.",
          es:"Sostén un vaso de agua entre las palmas, piensa durante tres respiraciones en aquello que agradeces y luego bebe despacio. Un pequeño ritual que puedes hacer en cualquier lugar.",
          pt:"Segura um copo de água entre as palmas das mãos, pensa durante três respirações naquilo que te enche de gratidão e depois bebe devagar. Um pequeno ritual que podes fazer em qualquer lugar.",
          fr:"Tiens un verre d'eau entre tes paumes, pense pendant trois respirations à ce qui t'inspire de la gratitude, puis bois lentement. Un petit rituel que tu peux faire n'importe où.",
          ja:"コップ一杯の水を両手のひらで包み、三呼吸のあいだ感謝していることを思い浮かべてから、ゆっくり飲みます。どこでもできる小さな儀式です。" } },
      { h:{ tr:"Deniz", en:"The sea", de:"Das Meer", es:"El mar", pt:"O mar", fr:"La mer", ja:"海" },
        p:{ tr:"Tuzlu suya girmek pek çok kültürde arınma ve eve dönüş olarak anlatılır.", en:"Entering salt water is told in many cultures as cleansing and coming home.",
          de:"In vielen Kulturen wird das Eintauchen in Salzwasser als Reinigung und Heimkehr erzählt.",
          es:"En muchas culturas, entrar en el agua salada se cuenta como purificación y regreso a casa.",
          pt:"Em muitas culturas, entrar na água salgada é contado como purificação e regresso a casa.",
          fr:"Dans de nombreuses cultures, entrer dans l'eau salée est raconté comme une purification et un retour chez soi.",
          ja:"塩水に入ることは、多くの文化で、清めと家に帰ることとして語られてきました。" } },
    ],
  },
  {
    id: "atolye", ico: "🛠", freq: "Birlikte yap", hue: ["#ffd28a", "#ff9ec7"], practice: "events",
    title:   { tr:"Atölyeler", en:"Workshops", de:"Workshops", es:"Talleres", pt:"Oficinas", fr:"Ateliers", ja:"ワークショップ" },
    tagline: { tr:"Eller toprakta, kalp gökyüzünde.", en:"Hands in the soil, heart in the sky.", de:"Hände in der Erde, Herz im Himmel.", es:"Las manos en la tierra, el corazón en el cielo.", pt:"Mãos na terra, coração no céu.", fr:"Les mains dans la terre, le cœur dans le ciel.", ja:"手は土に、心は空に。" },
    hero: {
      tr:"Atölye, çıraklığın ve aktarımın kadim biçimidir. Sümer rahipleri kil tabletlere yazarken, Anadolu kadınları kilim dokurken bilgiyi bedene işlerdi. Burada eller, ses ve niyet küçük dairelerde buluşur.",
      en:"The workshop is the ancient form of apprenticeship and passing on. Sumerian priests wrote on clay tablets, Anatolian women wove kilims, and knowledge was carried into the body. Here hands, voice and intention meet in small circles.",
      de:"Der Workshop ist die uralte Form von Lehre und Weitergabe. Sumerische Priester schrieben auf Tontafeln, anatolische Frauen webten Kelims, und das Wissen wurde in den Körper getragen. Hier begegnen sich Hände, Stimme und Absicht in kleinen Kreisen.",
      es:"El taller es la forma antigua del aprendizaje y la transmisión. Los sacerdotes sumerios escribían en tablillas de arcilla, las mujeres de Anatolia tejían kilims, y el saber se llevaba al cuerpo. Aquí las manos, la voz y la intención se encuentran en pequeños círculos.",
      pt:"A oficina é a forma antiga da aprendizagem e da transmissão. Os sacerdotes sumérios escreviam em tábuas de barro, as mulheres da Anatólia teciam kilims, e o saber passava para o corpo. Aqui as mãos, a voz e a intenção encontram-se em pequenos círculos.",
      fr:"L'atelier est la forme ancienne de l'apprentissage et de la transmission. Les prêtres sumériens écrivaient sur des tablettes d'argile, les femmes d'Anatolie tissaient des kilims, et le savoir passait dans le corps. Ici, les mains, la voix et l'intention se rencontrent en petits cercles.",
      ja:"ワークショップは、弟子入りと継承の古いかたちです。シュメールの神官は粘土板に文字を刻み、アナトリアの女性たちはキリムを織り、知恵はからだへと受け継がれました。ここでは、手と声と意図が小さな輪の中で出会います。",
    },
    teachings: [
      { h:{ tr:"Dönen pratikler", en:"Rotating practices", de:"Wechselnde Praktiken", es:"Prácticas rotativas", pt:"Práticas rotativas", fr:"Pratiques tournantes", ja:"めぐるプログラム" },
        p:{ tr:"", en:"", de:"", es:"", pt:"", fr:"", ja:"" },
        list:{ tr:["Çay seremonisi (Gong Fu Cha)","Bitki esansları ve aromaterapi","Kil ile çakraları tanıma","Tarot ve sembol okuma","Astroloji 101: doğum haritası"], en:["Tea ceremony (Gong Fu Cha)","Plant essences and aromatherapy","Getting to know the chakras through clay","Tarot and symbol reading","Astrology 101: the birth chart"],
          de:["Teezeremonie (Gong Fu Cha)","Pflanzenessenzen und Aromatherapie","Die Chakren durch Ton kennenlernen","Tarot und Symbole lesen","Astrologie 101: das Geburtshoroskop"],
          es:["Ceremonia del té (Gong Fu Cha)","Esencias de plantas y aromaterapia","Conocer los chakras a través del barro","Lectura de tarot y símbolos","Astrología 101: la carta natal"],
          pt:["Cerimónia do chá (Gong Fu Cha)","Essências de plantas e aromaterapia","Conhecer os chakras através do barro","Leitura de tarot e de símbolos","Astrologia 101: o mapa astral"],
          fr:["Cérémonie du thé (Gong Fu Cha)","Essences de plantes et aromathérapie","Découvrir les chakras par l'argile","Lecture du tarot et des symboles","Astrologie 101 : le thème natal"],
          ja:["茶の儀式（Gong Fu Cha）","植物のエッセンスとアロマセラピー","粘土でチャクラを知る","タロットとシンボルを読む","はじめての占星術：出生図"] } },
      { h:{ tr:"Aktarım", en:"Passing on", de:"Weitergabe", es:"Transmisión", pt:"Transmissão", fr:"Transmission", ja:"受け継ぐこと" },
        p:{ tr:"Atölyeler küçük dairelerde yapılır. Öğrenilen şey önce kendi sofrana taşınır.", en:"Workshops happen in small circles. What you learn is first carried to your own table.",
          de:"Workshops finden in kleinen Kreisen statt. Was du lernst, trägst du zuerst an deinen eigenen Tisch.",
          es:"Los talleres se hacen en pequeños círculos. Lo que aprendes lo llevas primero a tu propia mesa.",
          pt:"As oficinas acontecem em pequenos círculos. O que aprendes levas primeiro para a tua própria mesa.",
          fr:"Les ateliers se déroulent en petits cercles. Ce que tu apprends, tu le portes d'abord à ta propre table.",
          ja:"ワークショップは小さな輪で行われます。学んだことは、まず自分の食卓へと持ち帰ります。" } },
    ],
  },
  {
    id: "yaratim", ico: "✨", freq: "Sıfır nokta", hue: ["#b8a2ff", "#ffd28a"], practice: "harita",
    title:   { tr:"Yaratım Alanı", en:"Creation Space", de:"Raum der Schöpfung", es:"Espacio de creación", pt:"Espaço de criação", fr:"Espace de création", ja:"創造の場" },
    tagline: { tr:"Niyet, evrenin ham maddesidir.", en:"Intention is the raw material of the universe.", de:"Absicht ist der Rohstoff des Universums.", es:"La intención es la materia prima del universo.", pt:"A intenção é a matéria-prima do universo.", fr:"L'intention est la matière première de l'univers.", ja:"意図は、宇宙の原料。" },
    hero: {
      tr:"Hermes Trismegistos: \"Yukarıda nasılsa, aşağıda da öyle.\" Yaratım, görünmeyenden görünene geçen bir frekans olarak anlatılır. Burada niyet, ay ritüelleri ve vizyon bir araya gelir. Sen bir izleyici değil, eş-yaratıcısın.",
      en:"Hermes Trismegistus: \"As above, so below.\" Creation is described as a frequency moving from the unseen into the seen. Here intention, moon rituals and vision come together. You are not a spectator but a co-creator.",
      de:"Hermes Trismegistus: „Wie oben, so unten.“ Schöpfung wird als eine Frequenz beschrieben, die vom Unsichtbaren ins Sichtbare übergeht. Hier kommen Absicht, Mondrituale und Vision zusammen. Du schaust nicht nur zu, du erschaffst mit.",
      es:"Hermes Trismegistus: «Como es arriba, es abajo». La creación se describe como una frecuencia que pasa de lo invisible a lo visible. Aquí se unen la intención, los rituales de luna y la visión. No solo miras: tú también creas.",
      pt:"Hermes Trismegistus: «O que está em cima é como o que está em baixo.» A criação é descrita como uma frequência que passa do invisível para o visível. Aqui juntam-se a intenção, os rituais da lua e a visão. Não estás só a ver: também crias.",
      fr:"Hermes Trismegistus : « Ce qui est en haut est comme ce qui est en bas. » La création est décrite comme une fréquence qui passe de l'invisible au visible. Ici se rejoignent l'intention, les rituels de lune et la vision. Tu n'es pas là pour regarder : tu crées avec.",
      ja:"ヘルメス・トリスメギストス（Hermes Trismegistus）：「上にあるものは、下にあるもののごとし。」創造は、見えないものから見えるものへと移っていく周波数として語られます。ここでは意図、月の儀式、ビジョンがひとつになります。あなたは観客ではなく、共に創る人です。",
    },
    teachings: [
      { h:{ tr:"Üç adımlı yaratım", en:"Creation in three steps", de:"Schöpfung in drei Schritten", es:"Crear en tres pasos", pt:"Criar em três passos", fr:"Créer en trois étapes", ja:"三つのステップで創る" },
        p:{ tr:"", en:"", de:"", es:"", pt:"", fr:"", ja:"" },
        list:{ tr:["Net niyet: kelimeler açık","Bedende hissetmek: sanki olmuş gibi","Bırakmak: sonucu evrene emanet etmek"], en:["A clear intention: plain words","Feeling it in the body: as if it has happened","Letting go: entrusting the outcome to the universe"],
          de:["Eine klare Absicht: einfache Worte","Es im Körper fühlen: als wäre es schon geschehen","Loslassen: das Ergebnis dem Universum anvertrauen"],
          es:["Una intención clara: palabras sencillas","Sentirlo en el cuerpo: como si ya hubiera ocurrido","Soltar: confiar el resultado al universo"],
          pt:["Uma intenção clara: palavras simples","Senti-lo no corpo: como se já tivesse acontecido","Largar: confiar o resultado ao universo"],
          fr:["Une intention claire : des mots simples","La sentir dans le corps : comme si c'était déjà arrivé","Lâcher prise : confier le résultat à l'univers"],
          ja:["はっきりした意図：シンプルな言葉で","からだで感じる：もう叶ったかのように","手放す：結果を宇宙にゆだねる"] } },
      { h:{ tr:"Yeni ay", en:"New moon", de:"Neumond", es:"Luna nueva", pt:"Lua nova", fr:"Nouvelle lune", ja:"新月" },
        p:{ tr:"Yeni ay niyetin tohumu sayılır. Bir kâğıda \"Hayatıma çağırıyorum...\" diye başlayan üç cümle yaz, sesli oku, teşekkür et.", en:"The new moon is seen as the seed of intention. Write three sentences starting with \"I call into my life...\", read them aloud, give thanks.",
          de:"Der Neumond gilt als Samen der Absicht. Schreib drei Sätze, die mit „Ich rufe in mein Leben...“ beginnen, lies sie laut vor und bedanke dich.",
          es:"La luna nueva se considera la semilla de la intención. Escribe tres frases que empiecen con «Llamo a mi vida...», léelas en voz alta y da las gracias.",
          pt:"A lua nova é vista como a semente da intenção. Escreve três frases que comecem por «Chamo para a minha vida...», lê-as em voz alta e agradece.",
          fr:"La nouvelle lune est vue comme la graine de l'intention. Écris trois phrases qui commencent par « J'appelle dans ma vie... », lis-les à voix haute et remercie.",
          ja:"新月は意図の種とされています。「私は人生に…を呼び入れます」という形の文を三つ書き、声に出して読み、感謝を伝えましょう。" } },
      { h:{ tr:"Niyet Mektubu", en:"Intention Letter", de:"Absichtsbrief", es:"Carta de intención", pt:"Carta de intenção", fr:"Lettre d'intention", ja:"意図の手紙" },
        p:{ tr:"Sakin'deki Niyet Mektubu bu odanın pratiği: niyetini yaz, 21 gün mühürlü kalsın, sonra açıp yeniden oku.", en:"Sakin's Intention Letter is this room's practice: write your intention, keep it sealed for 21 days, then open it and read it again.",
          de:"Der Absichtsbrief in Sakin ist die Praxis dieses Raums: Schreib deine Absicht auf, lass sie 21 Tage versiegelt, dann öffne sie und lies sie noch einmal.",
          es:"La Carta de intención de Sakin es la práctica de esta sala: escribe tu intención, mantenla sellada 21 días y luego ábrela y vuelve a leerla.",
          pt:"A Carta de intenção da Sakin é a prática desta sala: escreve a tua intenção, mantém-na selada durante 21 dias e depois abre-a e lê-a outra vez.",
          fr:"La Lettre d'intention de Sakin est la pratique de cette salle : écris ton intention, garde-la scellée 21 jours, puis ouvre-la et relis-la.",
          ja:"Sakinの「意図の手紙」は、この部屋の実践です。意図を書いて21日間封をしておき、それから開いてもう一度読みます。" } },
    ],
  },
  {
    id: "tantra", ico: "🔥", freq: "Shiva · Shakti", hue: ["#ff7aa2", "#c8a2ff"], practice: "nefes", minAge: 18,
    title:   { tr:"Tantra", en:"Tantra", de:"Tantra", es:"Tantra", pt:"Tantra", fr:"Tantra", ja:"タントラ" },
    tagline: { tr:"Kutsalın ve bedenin buluştuğu eşik.", en:"The threshold where the sacred meets the body.", de:"Die Schwelle, an der sich das Heilige und der Körper begegnen.", es:"El umbral donde lo sagrado y el cuerpo se encuentran.", pt:"O limiar onde o sagrado e o corpo se encontram.", fr:"Le seuil où le sacré rencontre le corps.", ja:"聖なるものと身体が出会う敷居。" },
    hero: {
      tr:"Tantra, Sanskritçe \"dokuma\" demektir. Onu yalnızca cinsellikle eş tutmak Batı'nın bir yanlış anlamasıdır. Asıl tantra; bedenin, nefesin ve farkındalığın kutsal sayıldığı bir bütünlük yoludur. Keşmir Şivacılığında evren, Shiva'nın (saf farkındalık) ve Shakti'nin (yaratıcı güç) dansı olarak anlatılır.",
      en:"Tantra means \"weaving\" in Sanskrit. Equating it only with sexuality is a Western misunderstanding. True tantra is a path of wholeness in which the body, the breath and awareness are held as sacred. In Kashmir Shaivism the universe is told as the dance of Shiva (pure awareness) and Shakti (creative power).",
      de:"Tantra bedeutet auf Sanskrit „Gewebe“. Es nur mit Sexualität gleichzusetzen, ist ein westliches Missverständnis. Wahres Tantra ist ein Weg der Ganzheit, auf dem Körper, Atem und Bewusstsein als heilig gelten. Im kaschmirischen Shivaismus wird das Universum als Tanz von Shiva (reines Bewusstsein) und Shakti (schöpferische Kraft) erzählt.",
      es:"Tantra significa «tejido» en sánscrito. Equipararlo solo con la sexualidad es un malentendido occidental. El verdadero tantra es un camino de plenitud en el que el cuerpo, la respiración y la conciencia se consideran sagrados. En el shivaísmo de Cachemira, el universo se cuenta como la danza de Shiva (conciencia pura) y Shakti (poder creador).",
      pt:"Tantra significa «tecelagem» em sânscrito. Reduzi-lo à sexualidade é um equívoco ocidental. O verdadeiro tantra é um caminho de inteireza em que o corpo, a respiração e a consciência são tidos como sagrados. No shivaísmo da Caxemira, o universo é contado como a dança de Shiva (consciência pura) e Shakti (poder criador).",
      fr:"Tantra signifie « tissage » en sanskrit. Le réduire à la sexualité est un malentendu occidental. Le vrai tantra est un chemin de plénitude où le corps, le souffle et la conscience sont tenus pour sacrés. Dans le shivaïsme du Cachemire, l'univers est raconté comme la danse de Shiva (conscience pure) et de Shakti (puissance créatrice).",
      ja:"タントラはサンスクリット語で「織物」を意味します。それを性だけと結びつけるのは、西洋の誤解です。本来のタントラは、からだ、呼吸、気づきを聖なるものとして大切にする、全体性の道です。カシミール・シヴァ派では、宇宙はShiva（純粋な気づき）とShakti（創造の力）の舞として語られます。",
    },
    teachings: [
      { h:{ tr:"Beden tapınaktır", en:"The body is a temple", de:"Der Körper ist ein Tempel", es:"El cuerpo es un templo", pt:"O corpo é um templo", fr:"Le corps est un temple", ja:"からだは神殿" },
        p:{ tr:"Tantra utancı çözer; bedenin her hücresi tapınağın bir taşı sayılır. Saygı ve sınır temeldir.", en:"Tantra dissolves shame; every cell of the body is a stone of the temple. Respect and boundaries come first.",
          de:"Tantra löst Scham auf; jede Zelle des Körpers ist ein Stein des Tempels. Respekt und Grenzen kommen zuerst.",
          es:"El tantra disuelve la vergüenza; cada célula del cuerpo es una piedra del templo. El respeto y los límites van primero.",
          pt:"O tantra dissolve a vergonha; cada célula do corpo é uma pedra do templo. O respeito e os limites vêm primeiro.",
          fr:"Le tantra dissout la honte ; chaque cellule du corps est une pierre du temple. Le respect et les limites passent en premier.",
          ja:"タントラは恥の感覚をほどきます。からだの細胞ひとつひとつが神殿の石。敬意と境界線がまず先にあります。" } },
      { h:{ tr:"Nefes dansı", en:"Breath dance", de:"Atemtanz", es:"Danza de la respiración", pt:"Dança da respiração", fr:"Danse du souffle", ja:"呼吸のダンス" },
        p:{ tr:"Burundan dairesel nefes: verirken kalbe selam, alırken karna iniş. Yalnız da yapılabilir.", en:"Circular breathing through the nose: greet the heart on the exhale, drop into the belly on the inhale. It can be done alone.",
          de:"Kreisförmiges Atmen durch die Nase: Grüße beim Ausatmen das Herz, sinke beim Einatmen in den Bauch. Du kannst es auch allein üben.",
          es:"Respiración circular por la nariz: saluda al corazón al exhalar, desciende al vientre al inhalar. También puedes hacerlo a solas.",
          pt:"Respiração circular pelo nariz: saúda o coração ao expirar, desce até à barriga ao inspirar. Também se pode fazer a sós.",
          fr:"Respiration circulaire par le nez : salue le cœur à l'expiration, descends dans le ventre à l'inspiration. Tu peux aussi la pratiquer en solo.",
          ja:"鼻からの循環する呼吸。吐く息でハートにあいさつし、吸う息でお腹へと降りていきます。ひとりでも行えます。" } },
      { h:{ tr:"Trataka", en:"Trataka", de:"Trataka", es:"Trataka", pt:"Trataka", fr:"Trataka", ja:"Trataka" },
        p:{ tr:"Bir mum alevine ya da bir noktaya yumuşak, kesintisiz bakış. Önce huzursuzluk, sonra erime, sonra dinginlik.", en:"A soft, unbroken gaze at a candle flame or a point. First restlessness, then melting, then stillness.",
          de:"Ein weicher, ununterbrochener Blick auf eine Kerzenflamme oder einen Punkt. Erst Unruhe, dann Schmelzen, dann Stille.",
          es:"Una mirada suave e ininterrumpida a la llama de una vela o a un punto. Primero inquietud, después disolución, después quietud.",
          pt:"Um olhar suave e contínuo para a chama de uma vela ou para um ponto. Primeiro inquietação, depois dissolução, depois quietude.",
          fr:"Un regard doux et continu posé sur la flamme d'une bougie ou sur un point. D'abord l'agitation, puis la fonte, puis le calme.",
          ja:"ろうそくの炎や一点を、やわらかく途切れずに見つめます。はじめは落ち着かなさ、やがてほどけ、そして静けさへ。" } },
      { h:{ tr:"Kutsal sınır", en:"Sacred boundary", de:"Heilige Grenze", es:"Límite sagrado", pt:"Limite sagrado", fr:"Limite sacrée", ja:"聖なる境界" },
        p:{ tr:"Her pratik rıza ve \"durmak her zaman serbesttir\" ilkesiyle başlar. Kapı her zaman açıktır.", en:"Every practice begins with consent and the principle that stopping is always free. The door is always open.",
          de:"Jede Praxis beginnt mit Einverständnis und dem Grundsatz, dass Aufhören immer erlaubt ist. Die Tür steht immer offen.",
          es:"Cada práctica empieza con consentimiento y con el principio de que parar siempre es libre. La puerta está siempre abierta.",
          pt:"Cada prática começa com consentimento e com o princípio de que parar é sempre livre. A porta está sempre aberta.",
          fr:"Chaque pratique commence par le consentement et par le principe qu'on est toujours libre d'arrêter. La porte est toujours ouverte.",
          ja:"どの実践も、同意と「いつでもやめてよい」という原則から始まります。扉はいつも開いています。" } },
    ],
  },
  {
    id: "beden", ico: "🌀", freq: "Fasya · Akış", hue: ["#6fe6c1", "#5ad9ff"], practice: "nefes",
    title:   { tr:"Beden Egzersizleri", en:"Body Practices", de:"Körperübungen", es:"Prácticas corporales", pt:"Práticas corporais", fr:"Pratiques corporelles", ja:"からだのワーク" },
    tagline: { tr:"Beden, ruhun ilk dilidir.", en:"The body is the soul's first language.", de:"Der Körper ist die erste Sprache der Seele.", es:"El cuerpo es el primer idioma del alma.", pt:"O corpo é a primeira língua da alma.", fr:"Le corps est la première langue de l'âme.", ja:"からだは、魂の最初の言葉。" },
    hero: {
      tr:"Hareket, antik şamandan bugünün beden terapistine kadar şifanın anahtarlarından biri olarak anlatılır. Wilhelm Reich \"karakter zırhı\"ndan söz etti. Tai Chi yüzyıllardır qi'yi bedende dolaştıran bir akış olarak yaşar. Bu odada nefes, fasya ve titreşim buluşur.",
      en:"From the ancient shaman to today's body therapist, movement is told as one of the keys to healing. Wilhelm Reich spoke of \"character armour\". Tai Chi has lived for centuries as a flow that moves qi through the body. In this room breath, fascia and vibration meet.",
      de:"Vom alten Schamanen bis zur heutigen Körpertherapie wird Bewegung als einer der Schlüssel zur Heilung erzählt. Wilhelm Reich sprach vom „Charakterpanzer“. Tai Chi lebt seit Jahrhunderten als Fluss, der das Qi durch den Körper bewegt. In diesem Raum begegnen sich Atem, Faszien und Schwingung.",
      es:"Del antiguo chamán al terapeuta corporal de hoy, el movimiento se cuenta como una de las llaves de la sanación. Wilhelm Reich habló de la «coraza del carácter». El Tai Chi vive desde hace siglos como un flujo que mueve el qi por el cuerpo. En esta sala se encuentran la respiración, la fascia y la vibración.",
      pt:"Do xamã antigo ao terapeuta corporal de hoje, o movimento é contado como uma das chaves da cura. Wilhelm Reich falou da «couraça do carácter». O Tai Chi vive há séculos como um fluxo que move o qi pelo corpo. Nesta sala encontram-se a respiração, a fáscia e a vibração.",
      fr:"Du chaman ancien au thérapeute corporel d'aujourd'hui, le mouvement est raconté comme l'une des clés de la guérison. Wilhelm Reich parlait de « cuirasse caractérielle ». Le Tai Chi vit depuis des siècles comme un flux qui fait circuler le qi dans le corps. Dans cette salle se rencontrent le souffle, les fascias et la vibration.",
      ja:"古代のシャーマンから今日のボディセラピストまで、動きは癒やしの鍵のひとつとして語られてきました。ヴィルヘルム・ライヒ（Wilhelm Reich）は「性格の鎧」について語りました。Tai Chi（太極拳）は何世紀にもわたり、からだに気をめぐらせる流れとして受け継がれています。この部屋では、呼吸と筋膜と振動が出会います。",
    },
    teachings: [
      { h:{ tr:"Beş Tibet ritüeli", en:"The Five Tibetan Rites", de:"Die Fünf Tibeter", es:"Los cinco ritos tibetanos", pt:"Os cinco ritos tibetanos", fr:"Les Cinq Tibétains", ja:"五つのチベット体操" },
        p:{ tr:"Sabahları yapılan beş hareket; az tekrarla başla, bedenine göre artır:", en:"Five morning movements; start with few repetitions and increase as your body allows:",
          de:"Fünf Bewegungen für den Morgen; beginne mit wenigen Wiederholungen und steigere sie, so wie dein Körper es zulässt:",
          es:"Cinco movimientos para la mañana; empieza con pocas repeticiones y aumenta según lo permita tu cuerpo:",
          pt:"Cinco movimentos para a manhã; começa com poucas repetições e aumenta conforme o teu corpo permitir:",
          fr:"Cinq mouvements du matin ; commence avec peu de répétitions et augmente selon ce que ton corps permet :",
          ja:"朝に行う五つの動き。少ない回数から始め、からだに合わせて増やしていきましょう：" },
        list:{ tr:["Kendi etrafında dönme","Bacak kaldırma","Deve duruşu","Köprü","Yukarı ve aşağı bakan köpek geçişi"], en:["Spinning in place","Leg raises","Camel pose","Bridge","Moving between upward and downward dog"],
          de:["Drehen auf der Stelle","Beine heben","Kamelhaltung","Brücke","Wechsel zwischen heraufschauendem und herabschauendem Hund"],
          es:["Girar sobre el sitio","Elevación de piernas","Postura del camello","Puente","Pasar del perro bocarriba al perro bocabajo"],
          pt:["Girar no mesmo sítio","Elevação das pernas","Postura do camelo","Ponte","Alternar entre o cão virado para cima e o cão virado para baixo"],
          fr:["Tourner sur place","Élévations des jambes","Posture du chameau","Pont","Passer du chien tête en haut au chien tête en bas"],
          ja:["その場で回る","脚を上げる","ラクダのポーズ","ブリッジ","上向きの犬と下向きの犬を行き来する"] } },
      { h:{ tr:"Titreyiş (TRE)", en:"Shaking (TRE)", de:"Zittern (TRE)", es:"Temblor (TRE)", pt:"Tremor (TRE)", fr:"Tremblement (TRE)", ja:"ふるえ（TRE）" },
        p:{ tr:"Beden gerginliği titreyerek bırakabilir; hayvanlar bunu doğal olarak yapar. Nazik başla, istediğin an dur.", en:"The body can release tension by shaking; animals do it naturally. Begin gently and stop whenever you like.",
          de:"Der Körper kann Anspannung durch Zittern lösen; Tiere tun das ganz natürlich. Beginne sanft und hör auf, wann immer du möchtest.",
          es:"El cuerpo puede soltar tensión temblando; los animales lo hacen de forma natural. Empieza con suavidad y para cuando quieras.",
          pt:"O corpo pode libertar tensão ao tremer; os animais fazem-no naturalmente. Começa com suavidade e para sempre que quiseres.",
          fr:"Le corps peut relâcher les tensions en tremblant ; les animaux le font naturellement. Commence en douceur et arrête-toi quand tu veux.",
          ja:"からだは、ふるえることで緊張を手放すことがあります。動物は自然にそうしています。やさしく始めて、いつでも好きなときにやめてください。" } },
      { h:{ tr:"Qi Gong", en:"Qi Gong", de:"Qi Gong", es:"Qi Gong", pt:"Qi Gong", fr:"Qi Gong", ja:"Qi Gong（気功）" },
        p:{ tr:"\"Kucakta altın taşımak\", \"bulutu elle dağıtmak\" gibi yavaş formlar. Eklemleri akıcı tutar.", en:"Slow forms such as \"carrying gold in your arms\" and \"parting the clouds\". They keep the joints flowing.",
          de:"Langsame Formen wie „Gold in den Armen tragen“ und „die Wolken teilen“. Sie halten die Gelenke im Fluss.",
          es:"Formas lentas como «llevar oro en los brazos» y «separar las nubes». Mantienen las articulaciones fluidas.",
          pt:"Formas lentas como «carregar ouro nos braços» e «afastar as nuvens». Mantêm as articulações fluidas.",
          fr:"Des formes lentes comme « porter de l'or dans les bras » et « écarter les nuages ». Elles gardent les articulations fluides.",
          ja:"「腕に金を抱える」「雲を分ける」といった、ゆっくりとした型。関節の流れをなめらかに保ちます。" } },
    ],
  },
];

// Oda arayüz metinleri (7 dil).
export const ROOMS_TXT = {
  title:    { tr:"Sakin Odalar", en:"Sakin Rooms", de:"Sakin-Räume", es:"Salas Sakin", pt:"Salas Sakin", fr:"Salles Sakin", ja:"Sakinの部屋" },
  lead:     { tr:"Her oda bir frekans. Senin notan hangisi? Orkestrada yerini al, Sakin senin sesini bekliyor.", en:"Every room is a frequency. Which note is yours? Take your place in the orchestra, Sakin is waiting for your voice.", de:"Jeder Raum ist eine Frequenz. Welcher Ton ist deiner? Nimm deinen Platz im Orchester ein, Sakin wartet auf deine Stimme.", es:"Cada sala es una frecuencia. ¿Cuál es tu nota? Ocupa tu lugar en la orquesta, Sakin espera tu voz.", pt:"Cada sala é uma frequência. Qual é a tua nota? Toma o teu lugar na orquestra, a Sakin espera a tua voz.", fr:"Chaque salle est une fréquence. Quelle est ta note ? Prends ta place dans l'orchestre, Sakin attend ta voix.", ja:"部屋ごとに、ひとつの周波数。あなたの音はどれ？オーケストラに加わって。Sakinはあなたの声を待っています。" },
  sub:      { tr:"{n} oda, yaklaşan buluşmalar", en:"{n} rooms, upcoming gatherings", de:"{n} Räume, kommende Treffen", es:"{n} salas, próximos encuentros", pt:"{n} salas, próximos encontros", fr:"{n} salles, rencontres à venir", ja:"{n}つの部屋と、これからの集い" },
  rooms:    { tr:"Odalar", en:"Rooms", de:"Räume", es:"Salas", pt:"Salas", fr:"Salles", ja:"部屋" },
  events:   { tr:"Yaklaşan buluşmalar", en:"Upcoming gatherings", de:"Kommende Treffen", es:"Próximos encuentros", pt:"Próximos encontros", fr:"Rencontres à venir", ja:"これからの集い" },
  all:      { tr:"Tümü", en:"All", de:"Alle", es:"Todas", pt:"Todas", fr:"Toutes", ja:"すべて" },
  noEvents: { tr:"Şimdilik planlanmış bir buluşma yok. Yeni buluşmalar burada görünecek.", en:"No gatherings planned yet. New ones will appear here.", de:"Noch keine Treffen geplant. Neue erscheinen hier.", es:"Aún no hay encuentros previstos. Los nuevos aparecerán aquí.", pt:"Ainda não há encontros marcados. Os novos vão aparecer aqui.", fr:"Aucune rencontre prévue pour l'instant. Les nouvelles apparaîtront ici.", ja:"いまは予定された集いはありません。新しい集いはここに表示されます。" },
  guides:   { tr:"Rehberler", en:"Guides", de:"Begleiter", es:"Guías", pt:"Guias", fr:"Guides", ja:"ガイド" },
  noGuides: { tr:"Bu odanın rehberleri yakında burada.", en:"This room's guides will be here soon.", de:"Die Begleiter dieses Raums sind bald hier.", es:"Los guías de esta sala estarán aquí pronto.", pt:"Os guias desta sala vão estar aqui em breve.", fr:"Les guides de cette salle seront bientôt ici.", ja:"この部屋のガイドはまもなくここに。" },
  practice: { tr:"Bu frekansı Sakin'de dene", en:"Try this frequency in Sakin", de:"Probier diese Frequenz in Sakin", es:"Prueba esta frecuencia en Sakin", pt:"Experimenta esta frequência na Sakin", fr:"Essaie cette fréquence dans Sakin", ja:"この周波数をSakinで試す" },
  practiceName: {
    chakra: { tr:"Çakra", en:"Chakra", de:"Chakra", es:"Chakra", pt:"Chakra", fr:"Chakra", ja:"チャクラ" },
    nefes:  { tr:"Nefes", en:"Breath", de:"Atem", es:"Respiración", pt:"Respiração", fr:"Souffle", ja:"呼吸" },
    ses:    { tr:"Ses", en:"Sound", de:"Klang", es:"Sonido", pt:"Som", fr:"Son", ja:"音" },
    sabah:  { tr:"Sabah niyeti", en:"Morning intention", de:"Morgenabsicht", es:"Intención de la mañana", pt:"Intenção da manhã", fr:"Intention du matin", ja:"朝の意図" },
    harita: { tr:"Niyet Mektubu", en:"Intention Letter", de:"Absichtsbrief", es:"Carta de intención", pt:"Carta de intenção", fr:"Lettre d'intention", ja:"意図の手紙" },
    events: { tr:"Buluşmalar", en:"Gatherings", de:"Treffen", es:"Encuentros", pt:"Encontros", fr:"Rencontres", ja:"集い" },
  },
  back:     { tr:"Geri", en:"Back", de:"Zurück", es:"Atrás", pt:"Voltar", fr:"Retour", ja:"戻る" },
  call:     { tr:"Ara", en:"Call", de:"Anrufen", es:"Llamar", pt:"Ligar", fr:"Appeler", ja:"電話" },
  open:     { tr:"Aç", en:"Open", de:"Öffnen", es:"Abrir", pt:"Abrir", fr:"Ouvrir", ja:"開く" },
  details:  { tr:"Ayrıntı", en:"Details", de:"Details", es:"Detalles", pt:"Detalhes", fr:"Détails", ja:"詳細" },
};

// SABİT BAŞLANGIÇ BULUŞMALARI (kullanıcı: "örnek bir etkinlik gir: 1 Ekim 21:00
// tanışma çemberine bir selam ver"). Sunucudaki (panel) buluşmalarla BİRLEŞİR; tarihi
// geçince kendiliğinden gizlenir. `room: "cember"` = dokununca canlı oda açılır.
export const SEED_EVENTS = [
  {
    id: "seed-tanisma-2026-10-01", room: "cember", date: "2026-10-01T18:00:00.000Z", // 21:00 İstanbul
    title: { tr:"Tanışma çemberi: bir selam ver", en:"Welcome circle: come say hello", de:"Kennenlern-Kreis: sag Hallo", es:"Círculo de bienvenida: ven a saludar", pt:"Círculo de boas-vindas: vem dizer olá", fr:"Cercle de bienvenue : viens dire bonjour", ja:"はじめましての輪：あいさつしに来てね" },
    where: { tr:"Çember · Canlı oda", en:"Circle · Live room", de:"Kreis · Live-Raum", es:"Círculo · Sala en vivo", pt:"Círculo · Sala ao vivo", fr:"Cercle · Salon en direct", ja:"サークル・ライブルーム" },
  },
];
